//! Shared core for the generated `extern js` JavaScript glue (Phase 2.5 decision
//! C — "one shared marshalling core; per-backend encode/decode plugins").
//!
//! Both WASM bindings — wasm32-linear ([`super::js_glue`]) and wasm32-gc
//! ([`super::wasm_gc::js_glue`]) — emit a `.js` sidecar that *satisfies* a
//! module's custom `js.*` imports. The two share everything that doesn't depend
//! on the value ABI: the minimal WASI preview1 shim, the `instantiate`
//! scaffolding, the required-host fail-fast check, the thunk/factory *structure*,
//! and the JS-string escaper. They differ only in **marshalling** — how a
//! `JsValue` / `String` / closure crosses the boundary — which each backend
//! provides as a [`GlueBackend`] plugin: the per-type encode/decode expressions
//! plus the JS helper blocks those expressions call (a handle table vs. direct
//! `externref`, `phx_string_alloc` vs. the scratch-region helpers, a pinned
//! retention table vs. host-VM-traced refs).
//!
//! [`generate`] walks the same [`ExternSig`] / [`CallbackSig`] tables the import
//! section + trampolines were built from, so the imports, the trampolines, and
//! their glue can never drift — on either backend.

use crate::error::CompileError;
use crate::extern_abi::{
    CallbackSig, ExternSig, callback_sigs_in_externs, wasm_closure_trampoline_name,
};
use phoenix_ir::types::IrType;
use std::collections::BTreeMap;

/// Sentinel header every generated glue file begins with (both backends). The
/// driver uses it to recognise a build-owned sidecar: when a program that
/// previously used `extern js` is rebuilt with no externs, the driver removes the
/// now-stale sidecar only if it carries this marker, so a hand-written `.js` the
/// user keeps next to the `.wasm` is never clobbered. Kept in sync with
/// [`SHARED_TEMPLATE`]'s first line (a unit test pins this).
pub(crate) const GENERATED_MARKER: &str =
    "// Code-generated by Phoenix (phoenix-cranelift) — do not edit.";

/// A per-backend marshalling plugin: the encode/decode expressions for each
/// boundary type, plus the JS helper blocks those expressions reference. The
/// shared [`generate`] supplies the scaffolding and the thunk/factory structure;
/// a `GlueBackend` supplies only what depends on the value ABI.
pub(super) trait GlueBackend {
    /// The target name for the generated file header (`"wasm32-linear"` /
    /// `"wasm32-gc"`).
    fn target_name(&self) -> &'static str;

    /// JS injected into the `instantiate` body after the WASI shim and before the
    /// callback factories: the backend's `let` declarations and helper functions
    /// (the handle table / string builders / callback retention on linear; the
    /// scratch-string helpers on gc). Returned owned so a backend can interpolate
    /// compile-time constants (e.g. gc's scratch-buffer offset). May be empty.
    fn instantiate_helpers(&self) -> String;

    /// JS injected right after `WebAssembly.instantiate` (and `memory = …`): the
    /// backend's binding of the exports its helpers call (e.g.
    /// `stringAlloc = instance.exports.phx_string_alloc || null;`). May be empty.
    fn post_instantiate(&self) -> String;

    /// Extra members on the object `instantiate` returns (e.g. linear's
    /// `retainedCallbackCount()` diagnostic). Each must end with a trailing comma.
    /// May be empty.
    fn extra_return_members(&self) -> String {
        String::new()
    }

    /// Wasm→host marshalling for one extern parameter: the JS expression
    /// reconstructing the host argument from the flattened wasm params `p{slot}`…,
    /// and the number of wasm slots it consumes (kept in lockstep with the import
    /// signature's flattening so the `p{n}` indices can't desync). `Err(reason)`
    /// for a not-yet-supported type — the caller emits a throwing thunk.
    fn inbound_arg(&self, ty: &IrType, slot: usize) -> Result<(String, usize), String>;

    /// Host→wasm marshalling for an extern return: the JS statement that invokes
    /// `call` (the `host.<name>(...)` expression) and returns the wasm result.
    fn outbound_return(&self, ty: &IrType, call: &str) -> Result<String, String>;

    /// Host→wasm marshalling for a callback parameter: the JS expression(s)
    /// feeding `args[idx]` into the trampoline call (a `String` may spread to
    /// multiple wasm args on a backend whose strings flatten to several slots).
    fn callback_arg_to_wasm(&self, ty: &IrType, idx: usize) -> Result<String, CompileError>;

    /// Wasm→host marshalling for a callback return: the JS expression turning the
    /// trampoline result `__r` into the value the host callback returns.
    fn callback_wasm_to_host(&self, ty: &IrType) -> Result<String, CompileError>;

    /// Wrap a callback's `inner_body` in the backend's retention wrapper +
    /// argument-marshalling arrow. `inner_body` is a statement list that
    /// references the closure handle `ptr` and the host arguments as an array
    /// `args`. Linear wraps it as `__retainCallback(ptr, (args) => { … })` (pin +
    /// stable identity); gc returns a bare `(...args) => { … }` (the host VM
    /// traces the held closure ref — no pin, no retention table).
    fn wrap_callback(&self, inner_body: &str) -> String;
}

/// Generate the JS glue for a program's `extern js` imports, using `backend` for
/// all value-ABI-specific marshalling. Shared by both WASM backends.
pub(super) fn generate(
    externs: &[ExternSig],
    backend: &dyn GlueBackend,
) -> Result<String, CompileError> {
    // Group thunks by host module so each becomes its own import namespace
    // (`js: { ... }`). Only `js` exists today, but grouping keeps the generator
    // correct if npm-package modules ever land (Phase 3.1).
    let mut by_module: BTreeMap<&str, String> = BTreeMap::new();
    // Names the caller's `host` object must provide: an extern only needs a
    // binding if it got a real marshalling thunk. A deferred extern (throwing
    // thunk) needs none — its thunk never touches `host`.
    let mut required: Vec<&str> = Vec::new();
    for sig in externs {
        let thunk = match build_thunk(sig, backend) {
            Ok(t) => {
                required.push(sig.name.as_str());
                t
            }
            Err(reason) => {
                let msg = format!(
                    "phoenix glue: extern `{}.{}` is not supported yet — {reason}",
                    sig.module, sig.name
                );
                // A throwing thunk keeps instantiation valid (the import is
                // satisfied); only an actual call to this extern fails.
                format!(
                    "      {}(/* ...args */) {{ throw new Error({}); }},\n",
                    sig.name,
                    js_string(&msg)
                )
            }
        };
        by_module
            .entry(sig.module.as_str())
            .or_default()
            .push_str(&thunk);
    }

    let mut namespaces = String::new();
    for (module, thunks) in &by_module {
        namespaces.push_str(&format!(
            "    {}: {{\n{}    }},\n",
            js_string(module),
            thunks
        ));
    }

    let required_list = required
        .iter()
        .map(|n| js_string(n))
        .collect::<Vec<_>>()
        .join(", ");

    // One factory per distinct glue-supported callback signature handed to a host,
    // in first-seen order. Derived from the *same* helper as the trampoline
    // emitter ([`callback_sigs_in_externs`]), so every factory has a matching
    // exported trampoline and the two sets cannot drift.
    let mut factories = String::new();
    for cb in callback_sigs_in_externs(externs) {
        factories.push_str(&build_callback_factory(&cb, backend)?);
    }

    Ok(SHARED_TEMPLATE
        .replace("/*__TARGET__*/", backend.target_name())
        .replace(
            "/*__INSTANTIATE_HELPERS__*/",
            backend.instantiate_helpers().trim_end(),
        )
        .replace(
            "/*__POST_INSTANTIATE__*/",
            backend.post_instantiate().trim_end(),
        )
        .replace(
            "/*__EXTRA_RETURN_MEMBERS__*/",
            backend.extra_return_members().trim_end(),
        )
        .replace("/*__EXTERN_NAMESPACES__*/", namespaces.trim_end())
        .replace("/*__CALLBACK_FACTORIES__*/", factories.trim_end())
        .replace("/*__REQUIRED_HOST__*/", &required_list))
}

/// The JS factory-function name for a callback signature: the trampoline export
/// name with the `__phoenix_invoke_closure_` prefix swapped for a short `__cb_`.
/// Both the factory definition and the call site ([`GlueBackend::inbound_arg`]'s
/// `ClosureRef` arm) derive it the same way, from the shared
/// [`wasm_closure_trampoline_name`], so they cannot drift. Shared by both
/// backends (both use the same trampoline names — decision C).
pub(super) fn callback_factory_name(sig: &CallbackSig) -> Option<String> {
    wasm_closure_trampoline_name(sig).map(|t| t.replace("__phoenix_invoke_closure_", "__cb_"))
}

/// Build the marshalling thunk for one extern, or `Err(reason)` if the signature
/// needs marshalling that isn't implemented yet (caller emits a throwing thunk).
/// The per-param/return marshalling is the backend's; the thunk *structure* (the
/// `p{slot}` accumulation, the `host.<name>(...)` call) is shared.
fn build_thunk(sig: &ExternSig, backend: &dyn GlueBackend) -> Result<String, String> {
    let mut slot = 0usize;
    let mut host_args = Vec::with_capacity(sig.params.len());
    for ty in &sig.params {
        let (expr, slots) = backend.inbound_arg(ty, slot)?;
        host_args.push(expr);
        slot += slots;
    }
    let params: Vec<String> = (0..slot).map(|i| format!("p{i}")).collect();
    // Host bindings are looked up flat (`host.<name>`), matching the flat
    // required-host guard, not namespaced by module the way the import section is.
    // Sound while `js` is the only host module; if npm-package modules land (Phase
    // 3.1), two modules exporting the same name would collide here, so this must
    // become `host.<module>.<name>`.
    let call = format!("host.{}({})", sig.name, host_args.join(", "));
    let stmt = backend.outbound_return(&sig.return_type, &call)?;
    Ok(format!(
        "      {}({}) {{\n        {}\n      }},\n",
        sig.name,
        params.join(", "),
        stmt
    ))
}

/// Build the JS factory for one callback signature: `__cb_<sig>(ptr)` returns the
/// backend's retained callable that, when the host invokes it with JS arguments,
/// marshals them into the exported trampoline call and marshals the trampoline's
/// result back. The marshalling is the backend's; the dispatch *structure* is
/// shared.
fn build_callback_factory(
    sig: &CallbackSig,
    backend: &dyn GlueBackend,
) -> Result<String, CompileError> {
    // These names exist because the caller already filtered to glue-supported
    // signatures; an internal-bug guard rather than a user error.
    let trampoline = wasm_closure_trampoline_name(sig).ok_or_else(|| {
        CompileError::new("glue: callback factory for a non-marshallable signature".to_string())
    })?;
    let factory = callback_factory_name(sig).ok_or_else(|| {
        CompileError::new(
            "glue: callback factory name for a non-marshallable signature".to_string(),
        )
    })?;

    let mut arg_exprs = Vec::with_capacity(sig.param_types.len());
    for (i, ty) in sig.param_types.iter().enumerate() {
        arg_exprs.push(backend.callback_arg_to_wasm(ty, i)?);
    }
    let args_suffix = if arg_exprs.is_empty() {
        String::new()
    } else {
        format!(", {}", arg_exprs.join(", "))
    };
    let call = format!("{}(ptr{args_suffix})", js_index("exports", &trampoline));

    let inner = match &sig.return_type {
        IrType::Void => format!("{call};"),
        ret => format!(
            "const __r = {call}; return {};",
            backend.callback_wasm_to_host(ret)?
        ),
    };

    Ok(format!(
        "    function {factory}(ptr) {{\n      return {};\n    }}\n",
        backend.wrap_callback(&inner)
    ))
}

/// Render a JS property access `obj["key"]`, with `key` as a string literal so
/// any character in a generated export name stays valid.
pub(super) fn js_index(obj: &str, key: &str) -> String {
    format!("{obj}[{}]", js_string(key))
}

/// Render `s` as a JS double-quoted string literal.
pub(super) fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // U+2028 LINE SEPARATOR / U+2029 PARAGRAPH SEPARATOR are legal in JS
            // string literals only since ES2019; escape them so the glue parses
            // even on an older loader if a host name or message ever carries one.
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// The backend-neutral glue scaffolding. Placeholders (`/*__…__*/`) are filled by
/// [`generate`]: `__TARGET__` (header), `__INSTANTIATE_HELPERS__` /
/// `__POST_INSTANTIATE__` / `__EXTRA_RETURN_MEMBERS__` (backend JS blocks),
/// `__CALLBACK_FACTORIES__` / `__EXTERN_NAMESPACES__` / `__REQUIRED_HOST__`
/// (generated thunks/factories). Everything outside the placeholders — the WASI
/// preview1 shim, the `instantiate` frame, `readString`, `run()` — is identical
/// on both backends.
const SHARED_TEMPLATE: &str = r#"// Code-generated by Phoenix (phoenix-cranelift) — do not edit.
// JavaScript glue for an `extern js` /*__TARGET__*/ module (Phase 2.5 interop).
//
// Provide a `host` object with one JS function per declared `extern js`
// function. `Int` crosses as a JS Number (exact up to 2**53); a `JsValue`
// crosses as a host reference; the host functions never see wasm internals.
//
// Node:
//   import { readFile } from "node:fs/promises";
//   import { instantiate } from "./app.js";
//   const wasm = await readFile("./app.wasm");
//   const { run } = await instantiate({ wasm, host: { alert: (m) => console.log(m) } });
//   run();
//
// Browser:
//   import { instantiate } from "./app.js";
//   const wasm = await (await fetch("./app.wasm")).arrayBuffer();
//   const { run } = await instantiate({ wasm, host: { /* ... */ } });
//   run();

/** Thrown by the WASI `proc_exit` shim to unwind `_start` cleanly. */
class ExitStatus extends Error {
  constructor(code) { super("phoenix: proc_exit(" + code + ")"); this.code = code; }
}

const __decoder = new TextDecoder("utf-8");
const __encoder = new TextEncoder();

function __defaultWriteStdout() {
  if (typeof process !== "undefined" && process.stdout && process.stderr) {
    return (text, fd) => { (fd === 2 ? process.stderr : process.stdout).write(text); };
  }
  // Browser fallback: TextDecoder output already has trailing newlines; strip
  // one so console.log (which adds its own) doesn't double-space.
  return (text) => { console.log(text.replace(/\n$/, "")); };
}

/**
 * Instantiate the paired wasm module with WASI + the `extern js` host bindings.
 *
 * @param {{ wasm: BufferSource, host?: object, writeStdout?: (text: string, fd: number) => void }} opts
 * @returns {Promise<{ instance: WebAssembly.Instance, run: () => void }>}
 */
export async function instantiate({ wasm, host = {}, writeStdout } = {}) {
  if (!wasm) throw new Error("phoenix glue: `wasm` bytes are required");
  // Fail fast if `host` is missing a function some thunk needs, so a missing
  // binding surfaces as a clear error at instantiate time rather than a cryptic
  // `host.<name> is not a function` partway through a run. Only externs with a
  // real marshalling thunk are listed; a deferred (throwing) thunk needs no
  // host binding, so requiring one would force a pointless stub.
  for (const __name of [/*__REQUIRED_HOST__*/]) {
    if (typeof host[__name] !== "function") {
      throw new Error(
        "phoenix glue: host is missing required `extern js` function `" + __name + "`",
      );
    }
  }
  const out = writeStdout || __defaultWriteStdout();
  let memory = null;
  // Set after instantiation (below): the module's exports, used by the callback
  // trampolines and the backend's marshalling helpers.
  let exports = null;
  const view = () => new DataView(memory.buffer);
  const u8 = () => new Uint8Array(memory.buffer);
  const readString = (ptr, len) =>
    __decoder.decode(new Uint8Array(memory.buffer, ptr, len));

  // A decoder dedicated to `fd_write`, kept separate from the module-level
  // `__decoder` that extern thunks use for `readString`: `fd_write` decodes with
  // `stream: true` and carries partial-sequence state across iovecs, so it must
  // not share a decoder with the non-streaming string reads.
  const fdDecoder = new TextDecoder("utf-8");

  // Minimal WASI preview1 surface: only the calls the Phoenix runtime actually
  // imports. Its completeness is coupled to the runtime's WASI usage — if the
  // runtime grows to need another preview1 call (e.g. `clock_time_get`),
  // `WebAssembly.instantiate` fails loudly with a missing-import error until it
  // is shimmed here, rather than degrading silently.
  const wasi_snapshot_preview1 = {
    fd_write(fd, iovs, iovsLen, nwritten) {
      const v = view();
      let text = "";
      let written = 0;
      for (let i = 0; i < iovsLen; i++) {
        const base = iovs + i * 8;
        const ptr = v.getUint32(base, true);
        const len = v.getUint32(base + 4, true);
        // Decode with `stream: true` so a multi-byte UTF-8 sequence split
        // across two iovecs is reassembled rather than turned into replacement
        // characters; the final flush below drains any trailing partial bytes.
        text += fdDecoder.decode(new Uint8Array(memory.buffer, ptr, len), { stream: true });
        written += len;
      }
      // Drain any partial sequence buffered across iovecs. This also resets the
      // decoder, so a sequence split across *separate* fd_write calls is not
      // reassembled — fine because the runtime emits each print as one fd_write.
      text += fdDecoder.decode();
      out(text, fd);
      // Reuse the `v` from above: nothing in this call grows linear memory, so
      // its buffer can't have detached.
      v.setUint32(nwritten, written, true);
      return 0;
    },
    proc_exit(code) { throw new ExitStatus(code); },
    environ_get() { return 0; },
    environ_sizes_get(countPtr, sizePtr) {
      const v = view();
      v.setUint32(countPtr, 0, true);
      v.setUint32(sizePtr, 0, true);
      return 0;
    },
    random_get(ptr, len) {
      const bytes = u8().subarray(ptr, ptr + len);
      // WASI random_get is contractually a CSPRNG. Use the platform one
      // (Node >=18 and browsers both expose globalThis.crypto); fall back to
      // Math.random only where it is genuinely absent. getRandomValues caps at
      // 65536 bytes per call, so fill in chunks.
      if (typeof crypto !== "undefined" && crypto.getRandomValues) {
        for (let off = 0; off < len; off += 65536) {
          crypto.getRandomValues(bytes.subarray(off, Math.min(off + 65536, len)));
        }
      } else {
        for (let i = 0; i < len; i++) bytes[i] = (Math.random() * 256) | 0;
      }
      return 0;
    },
  };

  // Coerce a host-supplied JS value into the `i64` a callback's `Int` parameter
  // expects (backend-neutral). Mirrors the lenient `Int↔Number` contract of the
  // extern-return arm: go through `Number` so a `BigInt` doesn't make `Math.trunc`
  // throw, and guard a non-finite value so the bug surfaces as a clear glue error
  // rather than an opaque `RangeError` from `BigInt(NaN)`.
  function __intArg(v) {
    const n = Number(v);
    if (!Number.isFinite(n))
      throw new Error(
        "phoenix glue: a callback `Int` argument was passed a non-numeric value",
      );
    return BigInt(Math.trunc(n));
  }

  // --- Backend marshalling helpers (per the value ABI) ---
/*__INSTANTIATE_HELPERS__*/

  // One factory per distinct callback signature, each wrapping a closure handle
  // in a callable that marshals the host's JS arguments into the trampoline call
  // and marshals its result back. Generated from the same signature table as the
  // trampolines, so the names match.
/*__CALLBACK_FACTORIES__*/

  const imports = {
    wasi_snapshot_preview1,
/*__EXTERN_NAMESPACES__*/
  };

  const { instance } = await WebAssembly.instantiate(
    wasm instanceof Uint8Array ? wasm : new Uint8Array(wasm),
    imports,
  );
  memory = instance.exports.memory;
  exports = instance.exports;
/*__POST_INSTANTIATE__*/
  return {
    instance,
    run() {
      try {
        instance.exports._start();
      } catch (e) {
        if (e instanceof ExitStatus) {
          if (e.code !== 0) throw e;
          return;
        }
        throw e;
      }
    },
/*__EXTRA_RETURN_MEMBERS__*/
  };
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_begins_with_the_generated_marker() {
        // The driver keys stale-sidecar removal off this exact prefix, so the
        // template's first line must stay equal to the published marker.
        assert!(
            SHARED_TEMPLATE.starts_with(GENERATED_MARKER),
            "SHARED_TEMPLATE must begin with GENERATED_MARKER so the driver can \
             recognise a build-owned sidecar"
        );
    }

    #[test]
    fn js_string_escapes_special_characters() {
        assert_eq!(js_string("plain"), r#""plain""#);
        assert_eq!(js_string("a\"b"), r#""a\"b""#);
        assert_eq!(js_string("a\\b"), r#""a\\b""#);
        assert_eq!(js_string("a\nb"), r#""a\nb""#);
        assert_eq!(js_string("a\rb"), r#""a\rb""#);
        assert_eq!(js_string("a\tb"), r#""a\tb""#);
        assert_eq!(js_string("\u{2028}\u{2029}"), r#""\u2028\u2029""#);
        assert_eq!(js_string("\u{0}\u{1f}"), r#""\u0000\u001f""#);
    }
}
