//! Generated JavaScript glue for `extern js` wasm32-linear modules.
//!
//! `phoenix build --target wasm32-linear` pairs the emitted `.wasm` with a `.js`
//! glue module (this generator's output) that *satisfies* the custom `js.*`
//! imports. The glue is driven by the same [`ExternSig`] table the
//! import section was built from ([`super::translate::collect_externs`]), so the
//! import signatures and their glue thunks can never drift.
//!
//! The glue provides a minimal WASI preview1 shim (so the merged runtime
//! instantiates under Node and the browser without a WASI dependency) and one
//! marshalling thunk per declared extern. Marshalling follows the linear ABI
//! (design-decisions §Phase 2.5 decisions D/E/F): `Int`↔Number (exact to 2^53),
//! `Float`↔number, `Bool`↔0/1, `String` read from linear memory via
//! `TextDecoder`, `JsValue`↔an opaque handle into a glue-owned table mapping
//! i32 handles to real JS objects.
//!
//! A host function *returning* a `String` builds a GC-managed Phoenix
//! string from the returned JS string: the module exports `phx_string_alloc`
//! (gated on having externs), and the glue allocates `byteLen` bytes, copies the
//! UTF-8 in, and returns the `(ptr, len)` fat pointer. Strings are **copied**,
//! never shared (decision F).
//!
//! A *closure-typed* extern parameter (a callback — Phase 2.5 decision G) crosses
//! as the closure's `i32` env pointer. The glue wraps it in a JS callable that
//! invokes the module's exported `__phoenix_invoke_closure_<sig>` trampoline,
//! and roots the closure across the boundary: it calls `phx_gc_pin` when it
//! wraps the callback so a host-retained callback survives the GC after the
//! extern returns, and `phx_gc_unpin` when the host releases it (explicitly via
//! the wrapper's `release()`, or via a `FinalizationRegistry` when the wrapper is
//! collected). A callback the host never releases stays pinned for the program's
//! life — the documented, linear-only retained-callback leak.
//!
//! **Still deferred:** a closure *returned* from a host to Phoenix (the reverse
//! direction), and a *nested* callback (a closure whose own parameter/return is
//! itself a closure). The generator never fails the build for such a signature —
//! it emits a throwing thunk so the rest of the program still links and runs;
//! only an actual call to that extern fails.

use super::translate::{
    CallbackSig, ExternSig, callback_sigs_in_externs, closure_trampoline_name, wasm_valtypes_for,
};
use crate::error::CompileError;
use phoenix_ir::types::IrType;
use std::collections::BTreeMap;

/// Sentinel header every generated glue file begins with. The driver uses it to
/// recognise a build-owned sidecar: when a program that previously used `extern
/// js` is rebuilt with no externs, the driver removes the now-stale sidecar only
/// if it carries this marker, so a hand-written `.js` the user keeps next to the
/// `.wasm` is never clobbered. Keep in sync with [`GLUE_TEMPLATE`]'s first line
/// (a unit test pins this).
pub(crate) const GENERATED_MARKER: &str =
    "// Code-generated by Phoenix (phoenix-cranelift) — do not edit.";

/// The static glue scaffolding. `/*__EXTERN_NAMESPACES__*/` is replaced with the
/// generated per-module import namespaces (each holding the extern thunks).
const GLUE_TEMPLATE: &str = r#"// Code-generated by Phoenix (phoenix-cranelift) — do not edit.
// JavaScript glue for an `extern js` wasm32-linear module (Phase 2.5 interop).
//
// Provide a `host` object with one JS function per declared `extern js`
// function. `Int` crosses as a JS Number (exact up to 2**53); `JsValue` crosses
// as an opaque handle the glue maps to/from the real JS object you return or
// receive. The host functions never see wasm pointers.
//
// Node:
//   import { readFile } from "node:fs/promises";
//   import { instantiate } from "./app.js";
//   const wasm = await readFile("./app.wasm");
//   const { run } = await instantiate({ wasm, host: { alert: (m) => console.log(m) } });
//   run();
//
// Browser:
//   import { instantiate } from "./app.js";
//   const wasm = await (await fetch("./app.wasm")).arrayBuffer();
//   const { run } = await instantiate({ wasm, host: { /* ... */ } });
//   run();

/** Thrown by the WASI `proc_exit` shim to unwind `_start` cleanly. */
class ExitStatus extends Error {
  constructor(code) { super("phoenix: proc_exit(" + code + ")"); this.code = code; }
}

const __decoder = new TextDecoder("utf-8");
const __encoder = new TextEncoder();

/**
 * Host-owned JsValue handle table (design-decisions §Phase 2.5 decision D):
 * maps an i32 handle to/from a real JS object. Handle 0 is the null sentinel —
 * `null`/`undefined` map to 0 (and `get(0)` yields `undefined`), so a wasm-side
 * `== 0` null check matches a host that returns nothing.
 *
 * Handles are never reclaimed: each non-null `put` grows the table by one slot,
 * so a long-running program that returns many JsValues accumulates them. This is
 * acceptable for the current interop scope; a freeing/scoping scheme would land
 * with the wasm32-gc JsValue path (PR 14).
 */
function __makeHandles() {
  const objs = [undefined];
  return {
    put(obj) {
      if (obj === null || obj === undefined) return 0;
      const h = objs.length;
      objs.push(obj);
      return h;
    },
    get(h) { return objs[h]; },
  };
}

function __defaultWriteStdout() {
  if (typeof process !== "undefined" && process.stdout && process.stderr) {
    return (text, fd) => { (fd === 2 ? process.stderr : process.stdout).write(text); };
  }
  // Browser fallback: TextDecoder output already has trailing newlines; strip
  // one so console.log (which adds its own) doesn't double-space.
  return (text) => { console.log(text.replace(/\n$/, "")); };
}

/**
 * Instantiate the paired wasm module with WASI + the `extern js` host bindings.
 *
 * @param {{ wasm: BufferSource, host?: object, writeStdout?: (text: string, fd: number) => void }} opts
 * @returns {Promise<{ instance: WebAssembly.Instance, run: () => void }>}
 */
export async function instantiate({ wasm, host = {}, writeStdout } = {}) {
  if (!wasm) throw new Error("phoenix glue: `wasm` bytes are required");
  // Fail fast if `host` is missing a function some thunk needs, so a missing
  // binding surfaces as a clear error at instantiate time rather than a cryptic
  // `host.<name> is not a function` partway through a run. Only externs with a
  // real marshalling thunk are listed; a deferred (throwing) thunk needs no
  // host binding, so requiring one would force a pointless stub.
  for (const __name of [/*__REQUIRED_HOST__*/]) {
    if (typeof host[__name] !== "function") {
      throw new Error(
        "phoenix glue: host is missing required `extern js` function `" + __name + "`",
      );
    }
  }
  const out = writeStdout || __defaultWriteStdout();
  const handles = __makeHandles();
  let memory = null;
  // Set after instantiation (below): the exported `phx_string_alloc` the glue
  // calls to build a GC-managed Phoenix string from host bytes when a host
  // function returns a `String`. A module with no string-returning extern never
  // calls it; a build that uses externs always exports it (PR 7).
  let stringAlloc = null;
  // Set after instantiation: the module's exports (the callback trampolines the
  // wrapped callables invoke) and the GC pin/unpin hooks that root a host-
  // retained callback. A module that passes no closures to a host never sets the
  // pin hooks; a build that does always exports them.
  let exports = null;
  let gcPin = null;
  let gcUnpin = null;
  /**
   * Build a Phoenix `String` (a `(ptr, len)` fat pointer) in linear memory from
   * a JS string: allocate `phx_string_alloc(byteLen)` (returns the writable
   * payload pointer — the GC header sits just before it) and copy the UTF-8
   * bytes in. The bytes are *copied*, never shared (design-decisions §Phase 2.5
   * decision F): the GC owns the Phoenix copy, the JS engine owns the original.
   * The result is rooted by the calling Phoenix function the instant the extern
   * call returns (the backend roots every ref-typed `Op::ExternCall` result), so
   * a GC triggered by a later allocation can't collect it.
   */
  const buildString = (s) => {
    if (typeof stringAlloc !== "function") {
      throw new Error(
        "phoenix glue: this module did not export `phx_string_alloc`; a host " +
          "function returning a String needs it (rebuild with a current runtime)",
      );
    }
    const bytes = __encoder.encode(s);
    const ptr = stringAlloc(bytes.length);
    new Uint8Array(memory.buffer, ptr, bytes.length).set(bytes);
    return [ptr, bytes.length];
  };
  const view = () => new DataView(memory.buffer);
  const u8 = () => new Uint8Array(memory.buffer);
  const readString = (ptr, len) =>
    __decoder.decode(new Uint8Array(memory.buffer, ptr, len));

  // A decoder dedicated to `fd_write`, kept separate from the module-level
  // `__decoder` that extern thunks use for `readString`: `fd_write` decodes with
  // `stream: true` and carries partial-sequence state across iovecs, so it must
  // not share a decoder with the non-streaming string reads.
  const fdDecoder = new TextDecoder("utf-8");

  // Minimal WASI preview1 surface: only the calls the merged Phoenix runtime
  // actually imports. Its completeness is coupled to the runtime's WASI usage —
  // if the runtime grows to need another preview1 call (e.g. `clock_time_get`),
  // `WebAssembly.instantiate` fails loudly with a missing-import error until it
  // is shimmed here, rather than degrading silently.
  const wasi_snapshot_preview1 = {
    fd_write(fd, iovs, iovsLen, nwritten) {
      const v = view();
      let text = "";
      let written = 0;
      for (let i = 0; i < iovsLen; i++) {
        const base = iovs + i * 8;
        const ptr = v.getUint32(base, true);
        const len = v.getUint32(base + 4, true);
        // Decode with `stream: true` so a multi-byte UTF-8 sequence split
        // across two iovecs is reassembled rather than turned into replacement
        // characters; the final flush below drains any trailing partial bytes.
        text += fdDecoder.decode(new Uint8Array(memory.buffer, ptr, len), { stream: true });
        written += len;
      }
      // Drain any partial sequence buffered across iovecs. This also resets the
      // decoder, so a sequence split across *separate* fd_write calls is not
      // reassembled — fine because the runtime emits each print as one fd_write.
      text += fdDecoder.decode();
      out(text, fd);
      // Reuse the `v` from above: nothing in this call grows linear memory, so
      // its buffer can't have detached.
      v.setUint32(nwritten, written, true);
      return 0;
    },
    proc_exit(code) { throw new ExitStatus(code); },
    environ_get() { return 0; },
    environ_sizes_get(countPtr, sizePtr) {
      const v = view();
      v.setUint32(countPtr, 0, true);
      v.setUint32(sizePtr, 0, true);
      return 0;
    },
    random_get(ptr, len) {
      const bytes = u8().subarray(ptr, ptr + len);
      // WASI random_get is contractually a CSPRNG. Use the platform one
      // (Node >=18 and browsers both expose globalThis.crypto); fall back to
      // Math.random only where it is genuinely absent. getRandomValues caps at
      // 65536 bytes per call, so fill in chunks.
      if (typeof crypto !== "undefined" && crypto.getRandomValues) {
        for (let off = 0; off < len; off += 65536) {
          crypto.getRandomValues(bytes.subarray(off, Math.min(off + 65536, len)));
        }
      } else {
        for (let i = 0; i < len; i++) bytes[i] = (Math.random() * 256) | 0;
      }
      return 0;
    },
  };

  // Coerce a host-supplied JS value into the `i64` a callback's `Int` parameter
  // expects. Mirrors the lenient `Int↔Number` contract of the extern-return arm
  // (`outbound_return`): go through `Number` so a `BigInt` doesn't make
  // `Math.trunc` throw, and guard a non-finite value (`undefined`, an object,
  // `NaN`) so the bug surfaces as a clear glue error rather than an opaque
  // `RangeError` from `BigInt(NaN)`.
  function __intArg(v) {
    const n = Number(v);
    if (!Number.isFinite(n))
      throw new Error(
        "phoenix glue: a callback `Int` argument was passed a non-numeric value",
      );
    return BigInt(Math.trunc(n));
  }

  // Callback retention (design-decisions §Phase 2.5 decision G). A Phoenix
  // closure handed to a host crosses as its `i32` env pointer. `__retainCallback`
  // wraps it in a JS callable (invoking the relevant trampoline), pins the
  // closure so a host-retained callback survives a GC after the extern returns,
  // and tracks it so the *same* env pointer yields the *same* callable (stable
  // identity, one pin per live closure). `__releaseCallback` unpins it — called
  // explicitly via the wrapper's `release()` or by the `FinalizationRegistry`
  // when the wrapper is collected. A callback the host never releases stays
  // pinned for the program's life (the documented, linear-only leak).
  //
  // The map holds the wrapper *weakly* (`WeakRef`): a strong reference would keep
  // the wrapper reachable forever, so the `FinalizationRegistry` could never fire
  // and the dominant reclaim path (the host simply drops the callback) would
  // leak. Weak storage lets the wrapper be collected once the host releases its
  // own reference; the finalizer then unpins.
  //
  // Each wrapper gets a fresh identity object `token = { ptr }` used three ways:
  // as the `FinalizationRegistry` held value (so the finalizer knows which
  // pointer to unpin), as the unregister token, and as the staleness key stored
  // on the map entry. Two hazards this guards:
  //   * Env-pointer recycling after release. Once unpinned+collected, a pointer's
  //     address can be reused by a later allocation. An explicit `release()`
  //     therefore *unregisters* the still-armed finalizer, so it can't fire later
  //     and unpin a *different* live closure now at the same address.
  //   * Re-handing a still-pinned closure whose previous wrapper was collected but
  //     whose finalizer hasn't run yet ("stale" entry). We must not double-pin:
  //     the pin is still held, so the fresh wrapper reuses it (pin only when there
  //     is no entry at all). The superseded finalizer then fires with the old
  //     token, which no longer matches the entry, so it no-ops — the new wrapper
  //     owns the single pin until it is itself released.
  const __hasWeakRef = typeof WeakRef !== "undefined";
  const __callbacks = new Map(); // env pointer -> { ref, token }
  const __finalizers =
    typeof FinalizationRegistry !== "undefined"
      ? new FinalizationRegistry((token) => __releaseCallback(token))
      : null;
  function __releaseCallback(token) {
    const entry = __callbacks.get(token.ptr);
    // Ignore a finalizer superseded by a fresh retain of the same still-pinned
    // pointer: the newer entry (different token) owns the pin now.
    if (!entry || entry.token !== token) return;
    __callbacks.delete(token.ptr);
    if (__finalizers) __finalizers.unregister(token);
    if (typeof gcUnpin === "function") gcUnpin(token.ptr);
  }
  function __retainCallback(ptr, invoke) {
    if (ptr === 0) return null; // a null Phoenix closure crosses as 0
    const entry = __callbacks.get(ptr);
    // A live wrapper for this pointer => reuse it (stable identity, one pin). A
    // stale entry (wrapper collected, finalizer pending) falls through to a fresh
    // wrapper that reuses the still-held pin.
    const alive = entry && (__hasWeakRef ? entry.ref.deref() : entry.ref);
    if (alive) return alive;
    const fn = (...args) => invoke(args);
    const token = { ptr };
    fn.release = () => __releaseCallback(token);
    // Pin only on a genuinely fresh pointer; a stale entry means it is still
    // pinned (see the hazard note above).
    if (!entry && typeof gcPin === "function") gcPin(ptr);
    __callbacks.set(ptr, { ref: __hasWeakRef ? new WeakRef(fn) : fn, token });
    if (__finalizers) __finalizers.register(fn, token, token);
    return fn;
  }
  // One factory per distinct callback signature, each wrapping an env pointer in
  // a callable that marshals the host's JS arguments into the trampoline call
  // and marshals its result back. Generated from the same signature table as the
  // trampolines, so the names match.
/*__CALLBACK_FACTORIES__*/

  const imports = {
    wasi_snapshot_preview1,
/*__EXTERN_NAMESPACES__*/
  };

  const { instance } = await WebAssembly.instantiate(
    wasm instanceof Uint8Array ? wasm : new Uint8Array(wasm),
    imports,
  );
  memory = instance.exports.memory;
  stringAlloc = instance.exports.phx_string_alloc || null;
  exports = instance.exports;
  gcPin = instance.exports.phx_gc_pin || null;
  gcUnpin = instance.exports.phx_gc_unpin || null;
  return {
    instance,
    run() {
      try {
        instance.exports._start();
      } catch (e) {
        if (e instanceof ExitStatus) {
          if (e.code !== 0) throw e;
          return;
        }
        throw e;
      }
    },
    // Diagnostic introspection (not part of the stable embedding API): the number
    // of host-retained Phoenix callbacks still tracked — one map entry per pinned
    // closure, including any whose wrapper was collected but whose finalizer has
    // not yet run. Drops to zero once every retained callback has been released
    // (explicitly or via the `FinalizationRegistry`). Exposed so tests can
    // observe reclamation rather than only a clean exit.
    retainedCallbackCount() {
      return __callbacks.size;
    },
  };
}
"#;

/// Generate the JS glue module for the program's `extern js` imports.
pub(super) fn generate(externs: &[ExternSig]) -> Result<String, CompileError> {
    // Group thunks by host module so each becomes its own import namespace
    // (`js: { ... }`). Only `js` exists today, but grouping keeps the generator
    // correct if npm-package modules ever land (Phase 3.1).
    let mut by_module: BTreeMap<&str, String> = BTreeMap::new();
    // Names the caller's `host` object must provide: an extern only needs a
    // binding if it got a real marshalling thunk. A deferred extern (throwing
    // thunk) needs none — its thunk never touches `host`.
    let mut required: Vec<&str> = Vec::new();
    for sig in externs {
        let thunk = match build_thunk(sig) {
            Ok(t) => {
                required.push(sig.name.as_str());
                t
            }
            Err(reason) => {
                let msg = format!(
                    "phoenix glue: extern `{}.{}` is not supported yet — {reason}",
                    sig.module, sig.name
                );
                // A throwing thunk keeps instantiation valid (the import is
                // satisfied); only an actual call to this extern fails.
                format!(
                    "      {}(/* ...args */) {{ throw new Error({}); }},\n",
                    sig.name,
                    js_string(&msg)
                )
            }
        };
        by_module
            .entry(sig.module.as_str())
            .or_default()
            .push_str(&thunk);
    }

    let mut namespaces = String::new();
    for (module, thunks) in &by_module {
        namespaces.push_str(&format!(
            "    {}: {{\n{}    }},\n",
            js_string(module),
            thunks
        ));
    }

    let required_list = required
        .iter()
        .map(|n| js_string(n))
        .collect::<Vec<_>>()
        .join(", ");

    // One factory per distinct glue-supported callback signature handed to a
    // host, in first-seen order. Derived from the *same* helper as the trampoline
    // emitter (`translate::callback_sigs_in_externs`), so every factory has a
    // matching exported trampoline and the two sets cannot drift.
    let mut factories = String::new();
    for cb in callback_sigs_in_externs(externs) {
        factories.push_str(&build_callback_factory(&cb)?);
    }

    // Trim the trailing newline so the placeholder line's indentation is clean.
    Ok(GLUE_TEMPLATE
        .replace("/*__EXTERN_NAMESPACES__*/", namespaces.trim_end())
        .replace("/*__CALLBACK_FACTORIES__*/", factories.trim_end())
        .replace("/*__REQUIRED_HOST__*/", &required_list))
}

/// The JS factory-function name for a callback signature: the trampoline export
/// name with the `__phoenix_invoke_closure_` prefix swapped for a short `__cb_`.
/// Both the factory definition (in [`build_callback_factory`]) and the call site
/// (in [`inbound_arg`]) derive it the same way, from the shared
/// [`closure_trampoline_name`], so they cannot drift.
fn callback_factory_name(sig: &CallbackSig) -> Option<String> {
    closure_trampoline_name(sig).map(|t| t.replace("__phoenix_invoke_closure_", "__cb_"))
}

/// Build the JS factory for one callback signature: `__cb_<sig>(ptr)` returns a
/// retained callable that, when the host invokes it with JS arguments, marshals
/// them into the exported trampoline call and marshals the trampoline's result
/// back to a JS value.
fn build_callback_factory(sig: &CallbackSig) -> Result<String, CompileError> {
    // These names exist because the caller already filtered to glue-supported
    // signatures; an internal-bug guard rather than a user error.
    let trampoline = closure_trampoline_name(sig).ok_or_else(|| {
        CompileError::new(
            "wasm32-linear: callback factory for a non-marshallable signature \
             (internal compiler bug)"
                .to_string(),
        )
    })?;
    let factory = callback_factory_name(sig).ok_or_else(|| {
        CompileError::new(
            "wasm32-linear: callback factory name for a non-marshallable \
             signature (internal compiler bug)"
                .to_string(),
        )
    })?;

    // Marshal each host argument (`args[i]`) into the trampoline's wasm args. A
    // `String` arg spreads to two slots (ptr, len), so each entry is a full
    // expression list fragment.
    let mut arg_exprs = Vec::with_capacity(sig.param_types.len());
    for (i, ty) in sig.param_types.iter().enumerate() {
        arg_exprs.push(callback_arg_to_wasm(ty, i)?);
    }
    let args_suffix = if arg_exprs.is_empty() {
        String::new()
    } else {
        format!(", {}", arg_exprs.join(", "))
    };
    let call = format!("{}(ptr{args_suffix})", js_index("exports", &trampoline));

    let body = match &sig.return_type {
        IrType::Void => format!("{call};"),
        ret => format!(
            "const __r = {call}; return {};",
            callback_wasm_to_host(ret)?
        ),
    };

    Ok(format!(
        "    function {factory}(ptr) {{\n      \
         return __retainCallback(ptr, (args) => {{ {body} }});\n    }}\n"
    ))
}

/// Host→wasm marshalling for a callback parameter: the JS expression(s) feeding
/// `args[idx]` into the trampoline call. A `String` yields a *spread* of the
/// `(ptr, len)` pair (two wasm args from one host argument); every other type
/// yields a single expression. Mirrors [`outbound_return`]'s host→wasm coercions.
fn callback_arg_to_wasm(ty: &IrType, idx: usize) -> Result<String, CompileError> {
    let a = format!("args[{idx}]");
    Ok(match ty {
        // Trampoline `Int` param is i64; `__intArg` applies the same lenient
        // Int↔Number coercion the extern-return arm uses, with the non-finite
        // guard so a bad host value gives a clear glue error, not `BigInt(NaN)`.
        IrType::I64 => format!("__intArg({a})"),
        IrType::F64 => a,
        IrType::Bool => format!("({a}) ? 1 : 0"),
        // A `String` callback arg is copied into a GC string and spread to the
        // trampoline's `(ptr, len)` pair.
        IrType::StringRef => format!("...buildString(String({a}))"),
        // Each invocation interns a fresh handle; `handles` has no free path yet
        // (see `__makeHandles`), so a callback fired in a loop accumulates one
        // handle per call — to be reclaimed when the freeing/scoping scheme lands.
        // Tracked in known-issues.md ("A `JsValue` argument to an `extern js`
        // callback interns a handle per invocation on wasm32-linear").
        IrType::JsValue => format!("handles.put({a})"),
        other => {
            return Err(CompileError::new(format!(
                "wasm32-linear: callback parameter type `{other}` is not \
                 marshallable (internal compiler bug — \
                 `callback_sig_is_glue_supported` should have rejected it)"
            )));
        }
    })
}

/// Wasm→host marshalling for a callback's return type: the JS expression turning
/// the trampoline result `__r` into the value the host callback returns. A
/// `String` return is a 2-value wasm result (a `[ptr, len]` array on the JS
/// side); every other type is a single value. Mirrors [`inbound_arg`]'s
/// wasm→host reconstructions. `Void` never reaches here (its factory emits no
/// `return`).
fn callback_wasm_to_host(ty: &IrType) -> Result<String, CompileError> {
    Ok(match ty {
        IrType::I64 => "Number(__r)".to_string(),
        IrType::F64 => "__r".to_string(),
        IrType::Bool => "(__r !== 0)".to_string(),
        IrType::JsValue => "handles.get(__r)".to_string(),
        // Multi-value wasm result surfaces as a JS array `[ptr, len]`.
        IrType::StringRef => "readString(__r[0], __r[1])".to_string(),
        other => {
            return Err(CompileError::new(format!(
                "wasm32-linear: callback return type `{other}` is not \
                 marshallable (internal compiler bug — \
                 `callback_sig_is_glue_supported` should have rejected it)"
            )));
        }
    })
}

/// Render a JS property access `obj["key"]`, with `key` as a string literal so
/// any character in a generated export name stays valid.
fn js_index(obj: &str, key: &str) -> String {
    format!("{obj}[{}]", js_string(key))
}

/// Build the marshalling thunk for one extern, or `Err(reason)` if the signature
/// needs marshalling that isn't implemented yet (caller emits a throwing thunk).
fn build_thunk(sig: &ExternSig) -> Result<String, String> {
    let mut slot = 0usize;
    let mut host_args = Vec::with_capacity(sig.params.len());
    for ty in &sig.params {
        let (expr, slots) = inbound_arg(ty, slot)?;
        host_args.push(expr);
        slot += slots;
    }
    let params: Vec<String> = (0..slot).map(|i| format!("p{i}")).collect();
    // Host bindings are looked up flat (`host.<name>`), matching the flat
    // required-host guard in `generate`, not namespaced by module the way the
    // import section is. Sound while `js` is the only host module; if
    // npm-package modules land (Phase 3.1), two modules exporting the same name
    // would collide here, so this must become `host.<module>.<name>` (the import
    // grouping in `generate` already keeps the modules separate).
    let call = format!("host.{}({})", sig.name, host_args.join(", "));
    let stmt = outbound_return(&sig.return_type, &call)?;
    Ok(format!(
        "      {}({}) {{\n        {}\n      }},\n",
        sig.name,
        params.join(", "),
        stmt
    ))
}

/// Inbound (wasm → host) marshalling for one parameter: the JS expression
/// reconstructing the host argument from flattened wasm params `p{slot}`…, and
/// the number of slots consumed.
///
/// The slot count is taken from [`wasm_valtypes_for`] — the *same* function that
/// flattened this type into the WASM import signature — rather than re-encoded
/// here, so a thunk's `p{n}` indices cannot silently desync from the params the
/// import actually declares. (A multi-slot expression like `StringRef`'s still
/// hardcodes its slot layout; the shared count keeps that layout honest.)
fn inbound_arg(ty: &IrType, slot: usize) -> Result<(String, usize), String> {
    let expr = match ty {
        // Inbound `Int` is unguarded by design: a wasm-side i64 above 2**53 loses
        // precision silently here, matching the documented Int↔Number contract.
        // (The outbound arm guards only against a *non-numeric* host return, not
        // precision.)
        IrType::I64 => format!("Number(p{slot})"),
        IrType::F64 => format!("p{slot}"),
        IrType::Bool => format!("(p{slot} !== 0)"),
        IrType::StringRef => {
            // The `(ptr, len)` layout below hardcodes 2 slots; pin it to the
            // shared flattening so a future change to `wasm_valtypes_for` that
            // altered StringRef's slot count would trip here rather than silently
            // desync the `p{slot+1}` index from the params the import declares.
            debug_assert_eq!(
                wasm_valtypes_for(ty).map(|v| v.len()).unwrap_or(0),
                2,
                "StringRef must flatten to exactly 2 wasm slots (ptr, len)"
            );
            format!("readString(p{slot}, p{})", slot + 1)
        }
        IrType::JsValue => {
            // The handle reads a single `p{slot}`; pin that to the shared
            // flattening so a future change to `wasm_valtypes_for` that gave
            // `JsValue` more than one slot would trip here rather than silently
            // drop the extra slot from the import the params declare.
            debug_assert_eq!(
                wasm_valtypes_for(ty).map(|v| v.len()).unwrap_or(0),
                1,
                "JsValue must flatten to exactly 1 wasm slot (an i32 handle)"
            );
            format!("handles.get(p{slot})")
        }
        IrType::ClosureRef {
            param_types,
            return_type,
        } => {
            // A closure crosses as its single `i32` env pointer (a GC-pointer
            // type → 1 slot via `wasm_valtypes_for`). Wrap it through the
            // signature's factory, which retains + pins it and dispatches to the
            // exported trampoline. A signature the linear glue can't marshal (a
            // nested closure) has no factory name — fall back to the throwing-
            // thunk deferral, same as a non-marshallable return type.
            let sig = CallbackSig {
                param_types: param_types.clone(),
                return_type: (**return_type).clone(),
            };
            debug_assert_eq!(
                wasm_valtypes_for(ty).map(|v| v.len()).unwrap_or(0),
                1,
                "a closure must flatten to exactly 1 wasm slot (its env pointer)"
            );
            match callback_factory_name(&sig) {
                Some(factory) => format!("{factory}(p{slot})"),
                None => {
                    return Err("callback parameter with a non-marshallable signature \
                         (nested closures are not supported yet)"
                        .to_string());
                }
            }
        }
        other => return Err(format!("parameter type `{other}` is not marshallable")),
    };
    // Slot count from the shared flattening (the same function that built the
    // import signature), so a thunk's `p{n}` indices can't desync from the
    // params the import declares. Computed *after* the match so an unmarshallable
    // parameter reports the tailored reason above rather than a flattening error.
    let slots = wasm_valtypes_for(ty).map_err(|e| e.message)?.len();
    Ok((expr, slots))
}

/// Outbound (host → wasm) marshalling for the return type: the JS statement that
/// invokes `call` (the `host.<name>(...)` expression) and returns the wasm
/// result.
fn outbound_return(ty: &IrType, call: &str) -> Result<String, String> {
    Ok(match ty {
        IrType::Void => format!("{call};"),
        // Coerce through `Number` first so a host that returns a `BigInt` (rather
        // than the contracted `Number`) doesn't make `Math.trunc` throw a
        // `TypeError`; precision above 2**53 is lost either way (the `Int↔Number`
        // limit), but the call succeeds. Guard against a non-numeric result
        // (`undefined`, an object, `NaN`): `BigInt(NaN)` would otherwise throw an
        // opaque `RangeError`, so surface a clear glue error naming the cause.
        IrType::I64 => format!(
            "const __r = Number({call}); \
             if (!Number.isFinite(__r)) throw new Error(\"phoenix glue: an `Int`-returning host function returned a non-numeric value\"); \
             return BigInt(Math.trunc(__r));"
        ),
        IrType::F64 => format!("return {call};"),
        IrType::Bool => format!("return ({call}) ? 1 : 0;"),
        IrType::JsValue => format!("return handles.put({call});"),
        // String return: the host returns a JS string; the glue
        // builds a GC-managed Phoenix string in linear memory (UTF-8 bytes copied
        // in) and returns its `(ptr, len)` fat pointer as a 2-value result.
        // `String(...)` coerces a meaningfully-typed result (a number, say)
        // rather than producing a torn value — matching the lenient `Int↔Number`
        // coercion above. But `null`/`undefined` mean the host returned *no*
        // value; guard those (as the `Int` arm guards non-finite) so the bug
        // surfaces as a clear glue error instead of the literal string
        // `"undefined"` silently flowing into the program.
        IrType::StringRef => format!(
            "const __r = {call}; \
             if (__r == null) throw new Error(\"phoenix glue: a `String`-returning host function returned no value (null or undefined)\"); \
             return buildString(String(__r));"
        ),
        other => return Err(format!("return type `{other}` is not marshallable")),
    })
}

/// Render `s` as a JS double-quoted string literal.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // U+2028 LINE SEPARATOR / U+2029 PARAGRAPH SEPARATOR are legal in JS
            // string literals only since ES2019; escape them so the glue parses
            // even on an older loader if a host name or message ever carries one.
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sig(name: &str, params: Vec<IrType>, return_type: IrType) -> ExternSig {
        ExternSig {
            module: "js".to_string(),
            name: name.to_string(),
            params,
            return_type,
        }
    }

    #[test]
    fn template_begins_with_the_generated_marker() {
        // The driver keys stale-sidecar removal off this exact prefix, so the
        // template's first line must stay equal to the published marker.
        assert!(
            GLUE_TEMPLATE.starts_with(GENERATED_MARKER),
            "GLUE_TEMPLATE must begin with GENERATED_MARKER so the driver can \
             recognise a build-owned sidecar"
        );
    }

    #[test]
    fn generates_thunks_and_wasi_shim() {
        let externs = vec![
            sig("alert", vec![IrType::StringRef], IrType::Void),
            sig("getLength", vec![IrType::StringRef], IrType::I64),
        ];
        let glue = generate(&externs).unwrap();
        // Shared scaffolding.
        assert!(glue.contains("export async function instantiate"));
        assert!(glue.contains("fd_write"));
        assert!(glue.contains("proc_exit"));
        // The `js` import namespace with a thunk per extern.
        assert!(glue.contains("\"js\": {"));
        assert!(glue.contains("alert(p0, p1)"));
        assert!(glue.contains("host.alert(readString(p0, p1))"));
        assert!(glue.contains("getLength(p0, p1)"));
        assert!(glue.contains("const __r = Number(host.getLength(readString(p0, p1)));"));
        assert!(glue.contains("return BigInt(Math.trunc(__r));"));
        // Both externs have real thunks, so both are required host bindings.
        assert!(glue.contains(r#"for (const __name of ["alert", "getLength"])"#));
    }

    #[test]
    fn no_externs_yields_an_empty_required_host_list() {
        let glue = generate(&[]).unwrap();
        // The placeholder must still be substituted (to an empty list), never
        // left as a literal comment in the shipped glue.
        assert!(glue.contains("for (const __name of [])"));
        assert!(!glue.contains("__REQUIRED_HOST__"));
    }

    #[test]
    fn jsvalue_marshals_through_handle_table() {
        let externs = vec![
            sig("getEl", vec![IrType::StringRef], IrType::JsValue),
            sig("tagOf", vec![IrType::JsValue], IrType::I64),
        ];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("return handles.put(host.getEl(readString(p0, p1)));"));
        assert!(glue.contains("host.tagOf(handles.get(p0))"));
    }

    #[test]
    fn scalar_arg_marshalling() {
        let externs = vec![sig(
            "config",
            vec![IrType::I64, IrType::F64, IrType::Bool],
            IrType::Void,
        )];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("host.config(Number(p0), p1, (p2 !== 0))"));
    }

    #[test]
    fn slot_index_advances_past_a_multi_slot_param() {
        // A `String` (2 slots: ptr, len) followed by an `Int` must put the Int at
        // `p2`, not `p1` — i.e. `build_thunk` must advance `slot` by the param's
        // flattened width, not by one. A regression in that accumulation would
        // re-read the string's length word as the Int (`Number(p1)`), so pin the
        // exact post-string slot index here. The end-to-end Node tests only use
        // single-argument externs, so this is the only coverage of the offset.
        let externs = vec![sig(
            "tag",
            vec![IrType::StringRef, IrType::I64],
            IrType::Void,
        )];
        let glue = generate(&externs).unwrap();
        // Three flattened wasm params (ptr, len, i64), and the Int marshals from
        // the slot *after* the string's two.
        assert!(glue.contains("tag(p0, p1, p2)"));
        assert!(glue.contains("host.tag(readString(p0, p1), Number(p2))"));
    }

    #[test]
    fn js_string_escapes_special_characters() {
        // The escaping keeps generated host names / error messages valid JS
        // string literals; pin each branch.
        assert_eq!(js_string("plain"), r#""plain""#);
        assert_eq!(js_string("a\"b"), r#""a\"b""#);
        assert_eq!(js_string("a\\b"), r#""a\\b""#);
        assert_eq!(js_string("a\nb"), r#""a\nb""#);
        assert_eq!(js_string("a\rb"), r#""a\rb""#);
        assert_eq!(js_string("a\tb"), r#""a\tb""#);
        // U+2028 / U+2029 are escaped so the glue parses on pre-ES2019 loaders.
        assert_eq!(js_string("\u{2028}\u{2029}"), r#""\u2028\u2029""#);
        // Other C0 control chars get a `\u00xx` escape.
        assert_eq!(js_string("\u{0}\u{1f}"), r#""\u0000\u001f""#);
    }

    #[test]
    fn string_return_builds_a_gc_string_via_phx_string_alloc() {
        // A host function returning a String gets a real marshalling thunk
        // that routes through `buildString` (which calls the exported
        // `phx_string_alloc`), not a throwing stub.
        let externs = vec![sig("greet", vec![IrType::StringRef], IrType::StringRef)];
        let glue = generate(&externs).unwrap();
        assert!(
            glue.contains("const __r = host.greet(readString(p0, p1));")
                && glue.contains("return buildString(String(__r));"),
            "string-return thunk should build a GC string from the host result, \
             not a throwing stub"
        );
        // A `null`/`undefined` host return is rejected with a clear error rather
        // than silently coerced to the literal string `\"undefined\"`.
        assert!(
            glue.contains("returned no value (null or undefined)"),
            "string-return thunk should guard a missing host result"
        );
        // `buildString` allocates via the exported runtime function.
        assert!(glue.contains("stringAlloc(bytes.length)"));
        // …and it's a required host binding (it has a real thunk).
        assert!(glue.contains(r#"for (const __name of ["greet"])"#));
    }

    #[test]
    fn callback_params_wrap_through_a_factory_and_are_required() {
        // A `() -> Void` and an `(Int) -> Void` callback both get real thunks
        // that wrap the crossing closure pointer through the matching factory,
        // and both become required host bindings (the host receives the wrapped
        // callable).
        let externs = vec![
            sig(
                "onTick",
                vec![IrType::ClosureRef {
                    param_types: vec![],
                    return_type: Box::new(IrType::Void),
                }],
                IrType::Void,
            ),
            sig(
                "withValue",
                vec![IrType::ClosureRef {
                    param_types: vec![IrType::I64],
                    return_type: Box::new(IrType::Void),
                }],
                IrType::Void,
            ),
        ];
        let glue = generate(&externs).unwrap();
        // One factory per distinct signature.
        assert!(glue.contains("function __cb__to_v(ptr)"));
        assert!(glue.contains("function __cb_i_to_v(ptr)"));
        // The thunk wraps the closure pointer through its factory.
        assert!(glue.contains("host.onTick(__cb__to_v(p0))"));
        assert!(glue.contains("host.withValue(__cb_i_to_v(p0))"));
        // The factory dispatches to the exported trampoline, marshalling the
        // host's argument to the i64 the trampoline expects, and retains+pins it.
        assert!(
            glue.contains(r#"exports["__phoenix_invoke_closure_i_to_v"](ptr, __intArg(args[0]))"#)
        );
        assert!(glue.contains(r#"exports["__phoenix_invoke_closure__to_v"](ptr)"#));
        assert!(glue.contains("__retainCallback(ptr, (args) =>"));
        // Both real thunks => both required host bindings.
        assert!(glue.contains(r#"for (const __name of ["onTick", "withValue"])"#));
    }

    #[test]
    fn callback_with_return_and_string_arg_marshals_both_directions() {
        // A `(String) -> Bool` predicate exercises a string arg copied in
        // (spread to a `(ptr, len)` pair) and a bool result marshalled back.
        let externs = vec![sig(
            "keep",
            vec![IrType::ClosureRef {
                param_types: vec![IrType::StringRef],
                return_type: Box::new(IrType::Bool),
            }],
            IrType::Void,
        )];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("function __cb_s_to_b(ptr)"));
        // String arg copied into a GC string and spread to (ptr, len).
        assert!(glue.contains("...buildString(String(args[0]))"));
        // Bool result marshalled wasm→host, guarded by the `const __r` capture.
        assert!(glue.contains("const __r = ") && glue.contains("return (__r !== 0);"));
        assert!(glue.contains("host.keep(__cb_s_to_b(p0))"));
    }

    #[test]
    fn retention_holds_wrappers_weakly_and_disarms_the_finalizer_on_release() {
        // Two structural guarantees of the retention layer:
        //   1. The map holds the wrapper *weakly* (`WeakRef`), so a strong
        //      reference can't keep it alive forever and starve the
        //      `FinalizationRegistry` — the dominant reclaim path.
        //   2. Env pointers are recycled, so an explicit `release()` must
        //      unregister the still-armed finalizer (keyed on the per-wrapper
        //      `token`) — otherwise it could later fire for the same numeric
        //      pointer now bound to a *different* live closure (a use-after-free).
        let glue = generate(&[]).unwrap();
        assert!(
            glue.contains("new WeakRef(fn)"),
            "the wrapper must be stored weakly so it can be collected and finalized"
        );
        assert!(
            glue.contains("__finalizers.register(fn, token, token)"),
            "the wrapper must be registered with a per-wrapper token as both held \
             value and unregister token"
        );
        assert!(
            glue.contains("if (__finalizers) __finalizers.unregister(token);"),
            "an explicit release must unregister the still-armed finalizer before \
             the env pointer can be recycled"
        );
        // The fresh-pin guard: a stale entry (collected wrapper, pending
        // finalizer) must reuse the existing pin rather than double-pinning.
        assert!(
            glue.contains("if (!entry && typeof gcPin === \"function\") gcPin(ptr);"),
            "a fresh pin must be taken only when there is no existing entry"
        );
    }

    #[test]
    fn callback_marshals_jsvalue_through_the_handle_table_both_directions() {
        // A `(JsValue) -> JsValue` callback: the host's argument is interned into
        // the handle table (host→wasm) and the trampoline's handle result is
        // resolved back to the JS object (wasm→host), mirroring the extern-thunk
        // `JsValue` path.
        let externs = vec![sig(
            "map",
            vec![IrType::ClosureRef {
                param_types: vec![IrType::JsValue],
                return_type: Box::new(IrType::JsValue),
            }],
            IrType::Void,
        )];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("function __cb_j_to_j(ptr)"));
        // Arg interned host→wasm, result resolved wasm→host.
        assert!(
            glue.contains(
                r#"exports["__phoenix_invoke_closure_j_to_j"](ptr, handles.put(args[0]))"#
            )
        );
        assert!(glue.contains("const __r = ") && glue.contains("return handles.get(__r);"));
        assert!(glue.contains("host.map(__cb_j_to_j(p0))"));
    }

    #[test]
    fn nested_callback_param_emits_throwing_thunk_and_is_not_required() {
        // A callback whose own parameter is itself a closure is not marshallable
        // in this phase, so `weird` falls back to a throwing thunk (the deferral
        // pattern) and needs no host binding — only `alert` is required.
        let nested = IrType::ClosureRef {
            param_types: vec![IrType::ClosureRef {
                param_types: vec![],
                return_type: Box::new(IrType::Void),
            }],
            return_type: Box::new(IrType::Void),
        };
        let externs = vec![
            sig("weird", vec![nested], IrType::Void),
            sig("alert", vec![IrType::StringRef], IrType::Void),
        ];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("weird(/* ...args */) { throw new Error("));
        assert!(glue.contains("nested closures are not supported yet"));
        assert!(glue.contains(r#"for (const __name of ["alert"])"#));
        // No factory emitted for the unsupported signature.
        assert!(!glue.contains("__cb_"));
    }
}
