//! Generated JavaScript glue for `extern js` wasm32-linear modules.
//!
//! `phoenix build --target wasm32-linear` pairs the emitted `.wasm` with a `.js`
//! glue module (this generator's output) that *satisfies* the custom `js.*`
//! imports. The glue is driven by the same [`ExternSig`] table the
//! import section was built from ([`super::translate::collect_externs`]), so the
//! import signatures and their glue thunks can never drift.
//!
//! The glue provides a minimal WASI preview1 shim (so the merged runtime
//! instantiates under Node and the browser without a WASI dependency) and one
//! marshalling thunk per declared extern. Marshalling follows the linear ABI
//! (design-decisions §Phase 2.5 decisions D/E/F): `Int`↔Number (exact to 2^53),
//! `Float`↔number, `Bool`↔0/1, `String` read from linear memory via
//! `TextDecoder`, `JsValue`↔an opaque handle into a glue-owned table mapping
//! i32 handles to real JS objects.
//!
//! **Deferred to PR 7:** a host function *returning* a `String` needs to
//! allocate it in linear memory via `phx_string_alloc` (which the merged module
//! does not yet export); such a thunk is generated as a clear runtime throw.
//! Closure-typed extern parameters are PR 8. The generator never fails the
//! build for these — it emits a throwing thunk so the rest of the program still
//! links and runs.

use super::translate::{ExternSig, wasm_valtypes_for};
use crate::error::CompileError;
use phoenix_ir::types::IrType;
use std::collections::BTreeMap;

/// Sentinel header every generated glue file begins with. The driver uses it to
/// recognise a build-owned sidecar: when a program that previously used `extern
/// js` is rebuilt with no externs, the driver removes the now-stale sidecar only
/// if it carries this marker, so a hand-written `.js` the user keeps next to the
/// `.wasm` is never clobbered. Keep in sync with [`GLUE_TEMPLATE`]'s first line
/// (a unit test pins this).
pub(crate) const GENERATED_MARKER: &str =
    "// Code-generated by Phoenix (phoenix-cranelift) — do not edit.";

/// The static glue scaffolding. `/*__EXTERN_NAMESPACES__*/` is replaced with the
/// generated per-module import namespaces (each holding the extern thunks).
const GLUE_TEMPLATE: &str = r#"// Code-generated by Phoenix (phoenix-cranelift) — do not edit.
// JavaScript glue for an `extern js` wasm32-linear module (Phase 2.5 interop).
//
// Provide a `host` object with one JS function per declared `extern js`
// function. `Int` crosses as a JS Number (exact up to 2**53); `JsValue` crosses
// as an opaque handle the glue maps to/from the real JS object you return or
// receive. The host functions never see wasm pointers.
//
// Node:
//   import { readFile } from "node:fs/promises";
//   import { instantiate } from "./app.js";
//   const wasm = await readFile("./app.wasm");
//   const { run } = await instantiate({ wasm, host: { alert: (m) => console.log(m) } });
//   run();
//
// Browser:
//   import { instantiate } from "./app.js";
//   const wasm = await (await fetch("./app.wasm")).arrayBuffer();
//   const { run } = await instantiate({ wasm, host: { /* ... */ } });
//   run();

/** Thrown by the WASI `proc_exit` shim to unwind `_start` cleanly. */
class ExitStatus extends Error {
  constructor(code) { super("phoenix: proc_exit(" + code + ")"); this.code = code; }
}

const __decoder = new TextDecoder("utf-8");

/**
 * Host-owned JsValue handle table (design-decisions §Phase 2.5 decision D):
 * maps an i32 handle to/from a real JS object. Handle 0 is the null sentinel —
 * `null`/`undefined` map to 0 (and `get(0)` yields `undefined`), so a wasm-side
 * `== 0` null check matches a host that returns nothing.
 *
 * Handles are never reclaimed: each non-null `put` grows the table by one slot,
 * so a long-running program that returns many JsValues accumulates them. This is
 * acceptable for the current interop scope; a freeing/scoping scheme would land
 * with the wasm32-gc JsValue path (PR 14).
 */
function __makeHandles() {
  const objs = [undefined];
  return {
    put(obj) {
      if (obj === null || obj === undefined) return 0;
      const h = objs.length;
      objs.push(obj);
      return h;
    },
    get(h) { return objs[h]; },
  };
}

function __defaultWriteStdout() {
  if (typeof process !== "undefined" && process.stdout && process.stderr) {
    return (text, fd) => { (fd === 2 ? process.stderr : process.stdout).write(text); };
  }
  // Browser fallback: TextDecoder output already has trailing newlines; strip
  // one so console.log (which adds its own) doesn't double-space.
  return (text) => { console.log(text.replace(/\n$/, "")); };
}

/**
 * Instantiate the paired wasm module with WASI + the `extern js` host bindings.
 *
 * @param {{ wasm: BufferSource, host?: object, writeStdout?: (text: string, fd: number) => void }} opts
 * @returns {Promise<{ instance: WebAssembly.Instance, run: () => void }>}
 */
export async function instantiate({ wasm, host = {}, writeStdout } = {}) {
  if (!wasm) throw new Error("phoenix glue: `wasm` bytes are required");
  // Fail fast if `host` is missing a function some thunk needs, so a missing
  // binding surfaces as a clear error at instantiate time rather than a cryptic
  // `host.<name> is not a function` partway through a run. Only externs with a
  // real marshalling thunk are listed; a deferred (throwing) thunk needs no
  // host binding, so requiring one would force a pointless stub.
  for (const __name of [/*__REQUIRED_HOST__*/]) {
    if (typeof host[__name] !== "function") {
      throw new Error(
        "phoenix glue: host is missing required `extern js` function `" + __name + "`",
      );
    }
  }
  const out = writeStdout || __defaultWriteStdout();
  const handles = __makeHandles();
  let memory = null;
  const view = () => new DataView(memory.buffer);
  const u8 = () => new Uint8Array(memory.buffer);
  const readString = (ptr, len) =>
    __decoder.decode(new Uint8Array(memory.buffer, ptr, len));

  // A decoder dedicated to `fd_write`, kept separate from the module-level
  // `__decoder` that extern thunks use for `readString`: `fd_write` decodes with
  // `stream: true` and carries partial-sequence state across iovecs, so it must
  // not share a decoder with the non-streaming string reads.
  const fdDecoder = new TextDecoder("utf-8");

  // Minimal WASI preview1 surface: only the calls the merged Phoenix runtime
  // actually imports. Its completeness is coupled to the runtime's WASI usage —
  // if the runtime grows to need another preview1 call (e.g. `clock_time_get`),
  // `WebAssembly.instantiate` fails loudly with a missing-import error until it
  // is shimmed here, rather than degrading silently.
  const wasi_snapshot_preview1 = {
    fd_write(fd, iovs, iovsLen, nwritten) {
      const v = view();
      let text = "";
      let written = 0;
      for (let i = 0; i < iovsLen; i++) {
        const base = iovs + i * 8;
        const ptr = v.getUint32(base, true);
        const len = v.getUint32(base + 4, true);
        // Decode with `stream: true` so a multi-byte UTF-8 sequence split
        // across two iovecs is reassembled rather than turned into replacement
        // characters; the final flush below drains any trailing partial bytes.
        text += fdDecoder.decode(new Uint8Array(memory.buffer, ptr, len), { stream: true });
        written += len;
      }
      // Drain any partial sequence buffered across iovecs. This also resets the
      // decoder, so a sequence split across *separate* fd_write calls is not
      // reassembled — fine because the runtime emits each print as one fd_write.
      text += fdDecoder.decode();
      out(text, fd);
      // Reuse the `v` from above: nothing in this call grows linear memory, so
      // its buffer can't have detached.
      v.setUint32(nwritten, written, true);
      return 0;
    },
    proc_exit(code) { throw new ExitStatus(code); },
    environ_get() { return 0; },
    environ_sizes_get(countPtr, sizePtr) {
      const v = view();
      v.setUint32(countPtr, 0, true);
      v.setUint32(sizePtr, 0, true);
      return 0;
    },
    random_get(ptr, len) {
      const bytes = u8().subarray(ptr, ptr + len);
      // WASI random_get is contractually a CSPRNG. Use the platform one
      // (Node >=18 and browsers both expose globalThis.crypto); fall back to
      // Math.random only where it is genuinely absent. getRandomValues caps at
      // 65536 bytes per call, so fill in chunks.
      if (typeof crypto !== "undefined" && crypto.getRandomValues) {
        for (let off = 0; off < len; off += 65536) {
          crypto.getRandomValues(bytes.subarray(off, Math.min(off + 65536, len)));
        }
      } else {
        for (let i = 0; i < len; i++) bytes[i] = (Math.random() * 256) | 0;
      }
      return 0;
    },
  };

  const imports = {
    wasi_snapshot_preview1,
/*__EXTERN_NAMESPACES__*/
  };

  const { instance } = await WebAssembly.instantiate(
    wasm instanceof Uint8Array ? wasm : new Uint8Array(wasm),
    imports,
  );
  memory = instance.exports.memory;
  return {
    instance,
    run() {
      try {
        instance.exports._start();
      } catch (e) {
        if (e instanceof ExitStatus) {
          if (e.code !== 0) throw e;
          return;
        }
        throw e;
      }
    },
  };
}
"#;

/// Generate the JS glue module for the program's `extern js` imports.
pub(super) fn generate(externs: &[ExternSig]) -> Result<String, CompileError> {
    // Group thunks by host module so each becomes its own import namespace
    // (`js: { ... }`). Only `js` exists today, but grouping keeps the generator
    // correct if npm-package modules ever land (Phase 3.1).
    let mut by_module: BTreeMap<&str, String> = BTreeMap::new();
    // Names the caller's `host` object must provide: an extern only needs a
    // binding if it got a real marshalling thunk. A deferred extern (throwing
    // thunk) needs none — its thunk never touches `host`.
    let mut required: Vec<&str> = Vec::new();
    for sig in externs {
        let thunk = match build_thunk(sig) {
            Ok(t) => {
                required.push(sig.name.as_str());
                t
            }
            Err(reason) => {
                let msg = format!(
                    "phoenix glue: extern `{}.{}` is not supported yet — {reason}",
                    sig.module, sig.name
                );
                // A throwing thunk keeps instantiation valid (the import is
                // satisfied); only an actual call to this extern fails.
                format!(
                    "      {}(/* ...args */) {{ throw new Error({}); }},\n",
                    sig.name,
                    js_string(&msg)
                )
            }
        };
        by_module
            .entry(sig.module.as_str())
            .or_default()
            .push_str(&thunk);
    }

    let mut namespaces = String::new();
    for (module, thunks) in &by_module {
        namespaces.push_str(&format!(
            "    {}: {{\n{}    }},\n",
            js_string(module),
            thunks
        ));
    }

    let required_list = required
        .iter()
        .map(|n| js_string(n))
        .collect::<Vec<_>>()
        .join(", ");
    // Trim the trailing newline so the placeholder line's indentation is clean.
    Ok(GLUE_TEMPLATE
        .replace("/*__EXTERN_NAMESPACES__*/", namespaces.trim_end())
        .replace("/*__REQUIRED_HOST__*/", &required_list))
}

/// Build the marshalling thunk for one extern, or `Err(reason)` if the signature
/// needs marshalling that isn't implemented yet (caller emits a throwing thunk).
fn build_thunk(sig: &ExternSig) -> Result<String, String> {
    let mut slot = 0usize;
    let mut host_args = Vec::with_capacity(sig.params.len());
    for ty in &sig.params {
        let (expr, slots) = inbound_arg(ty, slot)?;
        host_args.push(expr);
        slot += slots;
    }
    let params: Vec<String> = (0..slot).map(|i| format!("p{i}")).collect();
    // Host bindings are looked up flat (`host.<name>`), matching the flat
    // required-host guard in `generate`, not namespaced by module the way the
    // import section is. Sound while `js` is the only host module; if
    // npm-package modules land (Phase 3.1), two modules exporting the same name
    // would collide here, so this must become `host.<module>.<name>` (the import
    // grouping in `generate` already keeps the modules separate).
    let call = format!("host.{}({})", sig.name, host_args.join(", "));
    let stmt = outbound_return(&sig.return_type, &call)?;
    Ok(format!(
        "      {}({}) {{\n        {}\n      }},\n",
        sig.name,
        params.join(", "),
        stmt
    ))
}

/// Inbound (wasm → host) marshalling for one parameter: the JS expression
/// reconstructing the host argument from flattened wasm params `p{slot}`…, and
/// the number of slots consumed.
///
/// The slot count is taken from [`wasm_valtypes_for`] — the *same* function that
/// flattened this type into the WASM import signature — rather than re-encoded
/// here, so a thunk's `p{n}` indices cannot silently desync from the params the
/// import actually declares. (A multi-slot expression like `StringRef`'s still
/// hardcodes its slot layout; the shared count keeps that layout honest.)
fn inbound_arg(ty: &IrType, slot: usize) -> Result<(String, usize), String> {
    let expr = match ty {
        // Inbound `Int` is unguarded by design: a wasm-side i64 above 2**53 loses
        // precision silently here, matching the documented Int↔Number contract.
        // (The outbound arm guards only against a *non-numeric* host return, not
        // precision.)
        IrType::I64 => format!("Number(p{slot})"),
        IrType::F64 => format!("p{slot}"),
        IrType::Bool => format!("(p{slot} !== 0)"),
        IrType::StringRef => {
            // The `(ptr, len)` layout below hardcodes 2 slots; pin it to the
            // shared flattening so a future change to `wasm_valtypes_for` that
            // altered StringRef's slot count would trip here rather than silently
            // desync the `p{slot+1}` index from the params the import declares.
            debug_assert_eq!(
                wasm_valtypes_for(ty).map(|v| v.len()).unwrap_or(0),
                2,
                "StringRef must flatten to exactly 2 wasm slots (ptr, len)"
            );
            format!("readString(p{slot}, p{})", slot + 1)
        }
        IrType::JsValue => {
            // The handle reads a single `p{slot}`; pin that to the shared
            // flattening so a future change to `wasm_valtypes_for` that gave
            // `JsValue` more than one slot would trip here rather than silently
            // drop the extra slot from the import the params declare.
            debug_assert_eq!(
                wasm_valtypes_for(ty).map(|v| v.len()).unwrap_or(0),
                1,
                "JsValue must flatten to exactly 1 wasm slot (an i32 handle)"
            );
            format!("handles.get(p{slot})")
        }
        IrType::ClosureRef { .. } => {
            return Err("closure (callback) parameters land in PR 8".to_string());
        }
        other => return Err(format!("parameter type `{other}` is not marshallable")),
    };
    // Slot count from the shared flattening (the same function that built the
    // import signature), so a thunk's `p{n}` indices can't desync from the
    // params the import declares. Computed *after* the match so an unmarshallable
    // parameter reports the tailored reason above rather than a flattening error.
    let slots = wasm_valtypes_for(ty).map_err(|e| e.message)?.len();
    Ok((expr, slots))
}

/// Outbound (host → wasm) marshalling for the return type: the JS statement that
/// invokes `call` (the `host.<name>(...)` expression) and returns the wasm
/// result.
fn outbound_return(ty: &IrType, call: &str) -> Result<String, String> {
    Ok(match ty {
        IrType::Void => format!("{call};"),
        // Coerce through `Number` first so a host that returns a `BigInt` (rather
        // than the contracted `Number`) doesn't make `Math.trunc` throw a
        // `TypeError`; precision above 2**53 is lost either way (the `Int↔Number`
        // limit), but the call succeeds. Guard against a non-numeric result
        // (`undefined`, an object, `NaN`): `BigInt(NaN)` would otherwise throw an
        // opaque `RangeError`, so surface a clear glue error naming the cause.
        IrType::I64 => format!(
            "const __r = Number({call}); \
             if (!Number.isFinite(__r)) throw new Error(\"phoenix glue: an `Int`-returning host function returned a non-numeric value\"); \
             return BigInt(Math.trunc(__r));"
        ),
        IrType::F64 => format!("return {call};"),
        IrType::Bool => format!("return ({call}) ? 1 : 0;"),
        IrType::JsValue => format!("return handles.put({call});"),
        IrType::StringRef => {
            return Err(
                "returning a String from a host function needs phx_string_alloc \
                 (lands in PR 7)"
                    .to_string(),
            );
        }
        other => return Err(format!("return type `{other}` is not marshallable")),
    })
}

/// Render `s` as a JS double-quoted string literal.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // U+2028 LINE SEPARATOR / U+2029 PARAGRAPH SEPARATOR are legal in JS
            // string literals only since ES2019; escape them so the glue parses
            // even on an older loader if a host name or message ever carries one.
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sig(name: &str, params: Vec<IrType>, return_type: IrType) -> ExternSig {
        ExternSig {
            module: "js".to_string(),
            name: name.to_string(),
            params,
            return_type,
        }
    }

    #[test]
    fn template_begins_with_the_generated_marker() {
        // The driver keys stale-sidecar removal off this exact prefix, so the
        // template's first line must stay equal to the published marker.
        assert!(
            GLUE_TEMPLATE.starts_with(GENERATED_MARKER),
            "GLUE_TEMPLATE must begin with GENERATED_MARKER so the driver can \
             recognise a build-owned sidecar"
        );
    }

    #[test]
    fn generates_thunks_and_wasi_shim() {
        let externs = vec![
            sig("alert", vec![IrType::StringRef], IrType::Void),
            sig("getLength", vec![IrType::StringRef], IrType::I64),
        ];
        let glue = generate(&externs).unwrap();
        // Shared scaffolding.
        assert!(glue.contains("export async function instantiate"));
        assert!(glue.contains("fd_write"));
        assert!(glue.contains("proc_exit"));
        // The `js` import namespace with a thunk per extern.
        assert!(glue.contains("\"js\": {"));
        assert!(glue.contains("alert(p0, p1)"));
        assert!(glue.contains("host.alert(readString(p0, p1))"));
        assert!(glue.contains("getLength(p0, p1)"));
        assert!(glue.contains("const __r = Number(host.getLength(readString(p0, p1)));"));
        assert!(glue.contains("return BigInt(Math.trunc(__r));"));
        // Both externs have real thunks, so both are required host bindings.
        assert!(glue.contains(r#"for (const __name of ["alert", "getLength"])"#));
    }

    #[test]
    fn only_real_thunks_are_required_host_bindings() {
        // `getText` returns a String (deferred → throwing thunk), so it needs no
        // host binding; `alert` does. The required-host list must list only
        // `alert`, or instantiate would force a pointless `getText` stub.
        let externs = vec![
            sig("alert", vec![IrType::StringRef], IrType::Void),
            sig("getText", vec![], IrType::StringRef),
        ];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains(r#"for (const __name of ["alert"])"#));
    }

    #[test]
    fn no_externs_yields_an_empty_required_host_list() {
        let glue = generate(&[]).unwrap();
        // The placeholder must still be substituted (to an empty list), never
        // left as a literal comment in the shipped glue.
        assert!(glue.contains("for (const __name of [])"));
        assert!(!glue.contains("__REQUIRED_HOST__"));
    }

    #[test]
    fn jsvalue_marshals_through_handle_table() {
        let externs = vec![
            sig("getEl", vec![IrType::StringRef], IrType::JsValue),
            sig("tagOf", vec![IrType::JsValue], IrType::I64),
        ];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("return handles.put(host.getEl(readString(p0, p1)));"));
        assert!(glue.contains("host.tagOf(handles.get(p0))"));
    }

    #[test]
    fn scalar_arg_marshalling() {
        let externs = vec![sig(
            "config",
            vec![IrType::I64, IrType::F64, IrType::Bool],
            IrType::Void,
        )];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("host.config(Number(p0), p1, (p2 !== 0))"));
    }

    #[test]
    fn slot_index_advances_past_a_multi_slot_param() {
        // A `String` (2 slots: ptr, len) followed by an `Int` must put the Int at
        // `p2`, not `p1` — i.e. `build_thunk` must advance `slot` by the param's
        // flattened width, not by one. A regression in that accumulation would
        // re-read the string's length word as the Int (`Number(p1)`), so pin the
        // exact post-string slot index here. The end-to-end Node tests only use
        // single-argument externs, so this is the only coverage of the offset.
        let externs = vec![sig(
            "tag",
            vec![IrType::StringRef, IrType::I64],
            IrType::Void,
        )];
        let glue = generate(&externs).unwrap();
        // Three flattened wasm params (ptr, len, i64), and the Int marshals from
        // the slot *after* the string's two.
        assert!(glue.contains("tag(p0, p1, p2)"));
        assert!(glue.contains("host.tag(readString(p0, p1), Number(p2))"));
    }

    #[test]
    fn js_string_escapes_special_characters() {
        // The escaping keeps generated host names / error messages valid JS
        // string literals; pin each branch.
        assert_eq!(js_string("plain"), r#""plain""#);
        assert_eq!(js_string("a\"b"), r#""a\"b""#);
        assert_eq!(js_string("a\\b"), r#""a\\b""#);
        assert_eq!(js_string("a\nb"), r#""a\nb""#);
        assert_eq!(js_string("a\rb"), r#""a\rb""#);
        assert_eq!(js_string("a\tb"), r#""a\tb""#);
        // U+2028 / U+2029 are escaped so the glue parses on pre-ES2019 loaders.
        assert_eq!(js_string("\u{2028}\u{2029}"), r#""\u2028\u2029""#);
        // Other C0 control chars get a `\u00xx` escape.
        assert_eq!(js_string("\u{0}\u{1f}"), r#""\u0000\u001f""#);
    }

    #[test]
    fn string_return_emits_throwing_thunk_deferred_to_pr7() {
        let externs = vec![sig("getText", vec![], IrType::StringRef)];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("getText(/* ...args */) { throw new Error("));
        assert!(glue.contains("phx_string_alloc"));
    }

    #[test]
    fn closure_param_emits_throwing_thunk_and_is_not_required() {
        // A closure (callback) parameter is deferred to PR 8, so `onClick` gets
        // a throwing thunk rather than a real marshalling thunk. Symmetric to
        // the deferred-*return* case above: the throwing thunk keeps the import
        // satisfied, but the extern needs no host binding, so it must be absent
        // from the required-host list (else instantiate would force a pointless
        // stub for an extern that can never actually be called).
        let externs = vec![
            sig(
                "onClick",
                vec![IrType::ClosureRef {
                    param_types: vec![],
                    return_type: Box::new(IrType::Void),
                }],
                IrType::Void,
            ),
            sig("alert", vec![IrType::StringRef], IrType::Void),
        ];
        let glue = generate(&externs).unwrap();
        assert!(glue.contains("onClick(/* ...args */) { throw new Error("));
        assert!(glue.contains("closure (callback) parameters land in PR 8"));
        // Only `alert` (a real thunk) is a required host binding; `onClick` is not.
        assert!(glue.contains(r#"for (const __name of ["alert"])"#));
    }
}
