#!/bin/sh
# This hook was set by cargo-husky v1: https://github.com/rhysd/cargo-husky#readme

set -e

echo "[pre-commit] cargo fmt --all --check"
cargo fmt --all --check

echo "[pre-commit] cargo clippy --all-targets -- -D warnings"
cargo clippy --all-targets -- -D warnings
