//! Integration tests for TypeScript code generation.
//!
//! These tests exercise the full pipeline: parse → type-check → generate,
//! verifying that the generated TypeScript is structurally correct for
//! realistic multi-endpoint schemas.

use phoenix_common::span::SourceId;
use phoenix_lexer::lexer::tokenize;
use phoenix_parser::parser;
use phoenix_sema::checker;

/// A realistic API schema with multiple structs, enums, and endpoints
/// covering all major Gen features.
const FULL_SCHEMA: &str = r#"
/** A registered user */
struct User {
    Int id
    String name
    String email
    Int age
    Option<String> bio
}

/** User permission levels */
enum Role { Admin  Editor  Viewer }

/** List all users, optionally filtered by search query */
endpoint listUsers: GET "/api/users" {
    query {
        Int page = 1
        Int limit = 20
        Option<String> search
    }
    response List<User>
}

/** Create a new user */
endpoint createUser: POST "/api/users" {
    body User omit { id, bio }
    response User
    error {
        ValidationError(400)
        Conflict(409)
    }
}

/** Update an existing user — all fields optional */
endpoint updateUser: PUT "/api/users/{id}" {
    body User omit { id } partial
    response User
    error { NotFound(404) }
}

/** Get a user by ID */
endpoint getUser: GET "/api/users/{id}" {
    response User
    error { NotFound(404) }
}

/** Delete a user */
endpoint deleteUser: DELETE "/api/users/{id}" {
    error { NotFound(404) }
}
"#;

fn generate_full_schema() -> phoenix_codegen::GeneratedFiles {
    let tokens = tokenize(FULL_SCHEMA, SourceId(0));
    let (program, parse_errors) = parser::parse(&tokens);
    assert!(parse_errors.is_empty(), "parse errors: {parse_errors:?}");
    let result = checker::check(&program);
    assert!(
        result.diagnostics.is_empty(),
        "check errors: {:?}",
        result.diagnostics
    );
    phoenix_codegen::generate_typescript(&program, &result)
}

// ── types.ts integration tests ──────────────────────────────────────

#[test]
fn types_contains_user_interface() {
    let files = generate_full_schema();
    assert!(files.types.contains("export interface User {"));
    assert!(files.types.contains("  id: number;"));
    assert!(files.types.contains("  name: string;"));
    assert!(files.types.contains("  email: string;"));
    assert!(files.types.contains("  age: number;"));
    assert!(files.types.contains("  bio?: string | undefined;"));
}

#[test]
fn types_contains_role_enum() {
    let files = generate_full_schema();
    assert!(
        files
            .types
            .contains(r#"export type Role = "Admin" | "Editor" | "Viewer";"#)
    );
}

#[test]
fn types_contains_derived_body_types() {
    let files = generate_full_schema();
    assert!(files.types.contains("export type CreateUserBody ="));
    assert!(files.types.contains("export type UpdateUserBody ="));
}

#[test]
fn types_contains_error_definitions() {
    let files = generate_full_schema();
    assert!(
        files
            .types
            .contains(r#"export type CreateUserError = "ValidationError" | "Conflict";"#)
    );
    assert!(files.types.contains("export const CreateUserErrors ="));
    assert!(files.types.contains("ValidationError: 400"));
    assert!(files.types.contains("Conflict: 409"));
}

#[test]
fn types_contains_doc_comments() {
    let files = generate_full_schema();
    assert!(files.types.contains("/** A registered user */"));
    assert!(files.types.contains("/** User permission levels */"));
}

#[test]
fn types_header_is_present() {
    let files = generate_full_schema();
    assert!(files.types.starts_with("// Generated by Phoenix Gen"));
}

// ── client.ts integration tests ─────────────────────────────────────

#[test]
fn client_imports_correct_types() {
    let files = generate_full_schema();
    assert!(files.client.contains("import type {"));
    assert!(files.client.contains("User"));
    assert!(files.client.contains("CreateUserBody"));
    assert!(files.client.contains("UpdateUserBody"));
    assert!(files.client.contains("from \"./types\""));
}

#[test]
fn client_has_api_error_class() {
    let files = generate_full_schema();
    assert!(files.client.contains("export class ApiError extends Error"));
    assert!(files.client.contains("public readonly code: string"));
    assert!(files.client.contains("public readonly status: number"));
}

#[test]
fn client_has_base_url_config() {
    let files = generate_full_schema();
    assert!(files.client.contains("export let baseUrl = \"\""));
    assert!(
        files
            .client
            .contains("export function setBaseUrl(url: string): void")
    );
}

#[test]
fn client_list_users_has_query_params() {
    let files = generate_full_schema();
    assert!(files.client.contains("async listUsers(opts?:"));
    assert!(files.client.contains("page?: number"));
    assert!(files.client.contains("limit?: number"));
    assert!(files.client.contains("search?: string"));
    assert!(files.client.contains("new URLSearchParams()"));
    assert!(files.client.contains("params.set(\"page\""));
}

#[test]
fn client_create_user_has_body_and_errors() {
    let files = generate_full_schema();
    assert!(
        files
            .client
            .contains("async createUser(body: CreateUserBody): Promise<User>")
    );
    assert!(files.client.contains("JSON.stringify(body)"));
    assert!(files.client.contains("Content-Type"));
    assert!(files.client.contains("ApiError(\"ValidationError\", 400"));
    assert!(files.client.contains("ApiError(\"Conflict\", 409"));
}

#[test]
fn client_update_user_has_path_param_and_body() {
    let files = generate_full_schema();
    assert!(
        files
            .client
            .contains("async updateUser(id: string, body: UpdateUserBody): Promise<User>")
    );
    assert!(files.client.contains("/api/users/${id}"));
}

#[test]
fn client_get_user_has_path_param() {
    let files = generate_full_schema();
    assert!(
        files
            .client
            .contains("async getUser(id: string): Promise<User>")
    );
}

#[test]
fn client_delete_user_has_void_return() {
    let files = generate_full_schema();
    assert!(
        files
            .client
            .contains("async deleteUser(id: string): Promise<void>")
    );
    // void response should not have return await response.json()
    // Check that the deleteUser function block doesn't contain response.json()
    let delete_start = files.client.find("async deleteUser").unwrap();
    let delete_end = files.client[delete_start..].find("},").unwrap() + delete_start;
    let delete_fn = &files.client[delete_start..delete_end];
    assert!(!delete_fn.contains("response.json()"));
}

#[test]
fn client_has_doc_comments() {
    let files = generate_full_schema();
    assert!(files.client.contains("/** List all users"));
    assert!(files.client.contains("/** Create a new user */"));
    assert!(files.client.contains("/** Get a user by ID */"));
}

#[test]
fn client_header_is_present() {
    let files = generate_full_schema();
    assert!(files.client.starts_with("// Generated by Phoenix Gen"));
}

// ── handlers.ts integration tests ───────────────────────────────────

#[test]
fn handlers_has_interface() {
    let files = generate_full_schema();
    assert!(files.handlers.contains("export interface Handlers {"));
    assert!(files.handlers.contains("}"));
}

#[test]
fn handlers_imports_correct_types() {
    let files = generate_full_schema();
    assert!(files.handlers.contains("import type {"));
    assert!(files.handlers.contains("User"));
    assert!(files.handlers.contains("CreateUserBody"));
    assert!(files.handlers.contains("from \"./types\""));
}

#[test]
fn handlers_list_users_has_query_param() {
    let files = generate_full_schema();
    assert!(files.handlers.contains("listUsers(query:"));
    assert!(files.handlers.contains("page: number"));
    assert!(files.handlers.contains("limit: number"));
}

#[test]
fn handlers_create_user_has_body() {
    let files = generate_full_schema();
    assert!(
        files
            .handlers
            .contains("createUser(body: CreateUserBody): Promise<User>")
    );
}

#[test]
fn handlers_update_user_has_path_and_body() {
    let files = generate_full_schema();
    assert!(
        files
            .handlers
            .contains("updateUser(id: string, body: UpdateUserBody): Promise<User>")
    );
}

#[test]
fn handlers_get_user_has_path_param() {
    let files = generate_full_schema();
    assert!(
        files
            .handlers
            .contains("getUser(id: string): Promise<User>")
    );
}

#[test]
fn handlers_delete_user_returns_void() {
    let files = generate_full_schema();
    assert!(
        files
            .handlers
            .contains("deleteUser(id: string): Promise<void>")
    );
}

#[test]
fn handlers_has_doc_comments() {
    let files = generate_full_schema();
    assert!(files.handlers.contains("/** List all users"));
    assert!(files.handlers.contains("/** Create a new user */"));
}

#[test]
fn handlers_header_is_present() {
    let files = generate_full_schema();
    assert!(files.handlers.starts_with("// Generated by Phoenix Gen"));
}

// ── Cross-file consistency tests ────────────────────────────────────

#[test]
fn all_files_are_non_empty() {
    let files = generate_full_schema();
    assert!(!files.types.is_empty());
    assert!(!files.client.is_empty());
    assert!(!files.handlers.is_empty());
    assert!(!files.server.is_empty());
}

#[test]
fn derived_types_in_types_match_client_usage() {
    let files = generate_full_schema();
    // Every body type used in client.ts should be defined in types.ts
    if files.client.contains("CreateUserBody") {
        assert!(files.types.contains("export type CreateUserBody"));
    }
    if files.client.contains("UpdateUserBody") {
        assert!(files.types.contains("export type UpdateUserBody"));
    }
}

#[test]
fn regeneration_is_deterministic() {
    let files1 = generate_full_schema();
    let files2 = generate_full_schema();
    assert_eq!(files1.types, files2.types, "types.ts is not deterministic");
    assert_eq!(
        files1.client, files2.client,
        "client.ts is not deterministic"
    );
    assert_eq!(
        files1.handlers, files2.handlers,
        "handlers.ts is not deterministic"
    );
    assert_eq!(
        files1.server, files2.server,
        "server.ts is not deterministic"
    );
}

// ── server.ts integration tests ─────────────────────────────────────

#[test]
fn server_has_create_router() {
    let files = generate_full_schema();
    assert!(
        files
            .server
            .contains("export function createRouter(handlers: Handlers): Router")
    );
}

#[test]
fn server_imports_express() {
    let files = generate_full_schema();
    assert!(files.server.contains("import { Router } from \"express\""));
    assert!(
        files
            .server
            .contains("import type { Request, Response } from \"express\"")
    );
    assert!(
        files
            .server
            .contains("import type { Handlers } from \"./handlers\"")
    );
}

#[test]
fn server_has_routes_for_all_endpoints() {
    let files = generate_full_schema();
    assert!(files.server.contains("router.get(\"/api/users\""));
    assert!(files.server.contains("router.post(\"/api/users\""));
    assert!(files.server.contains("router.put(\"/api/users/:id\""));
    assert!(files.server.contains("router.get(\"/api/users/:id\""));
    assert!(files.server.contains("router.delete(\"/api/users/:id\""));
}

#[test]
fn server_parses_query_params_with_defaults() {
    let files = generate_full_schema();
    // listUsers has query { Int page = 1, Int limit = 20, Option<String> search }
    assert!(files.server.contains("handlers.listUsers("));
}

#[test]
fn server_parses_path_params() {
    let files = generate_full_schema();
    assert!(files.server.contains("req.params.id"));
}

#[test]
fn server_handles_json_body() {
    let files = generate_full_schema();
    assert!(files.server.contains("const body = req.body"));
}

#[test]
fn server_maps_errors_to_status_codes() {
    let files = generate_full_schema();
    // createUser has error { ValidationError(400), Conflict(409) }
    assert!(files.server.contains("res.status(400)"));
    assert!(files.server.contains("res.status(409)"));
    assert!(files.server.contains("res.status(404)"));
}

#[test]
fn server_returns_json_for_response_endpoints() {
    let files = generate_full_schema();
    assert!(files.server.contains("res.json(result)"));
}

#[test]
fn server_returns_204_for_void_endpoints() {
    let files = generate_full_schema();
    assert!(files.server.contains("res.status(204).end()"));
}

// ── OpenAPI integration tests ───────────────────────────────────────

fn generate_full_openapi() -> String {
    let tokens = tokenize(FULL_SCHEMA, SourceId(0));
    let (program, parse_errors) = parser::parse(&tokens);
    assert!(parse_errors.is_empty(), "parse errors: {parse_errors:?}");
    let result = checker::check(&program);
    assert!(
        result.diagnostics.is_empty(),
        "check errors: {:?}",
        result.diagnostics
    );
    phoenix_codegen::generate_openapi(&program, &result)
}

#[test]
fn openapi_is_valid_json() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).expect("should be valid JSON");
    assert!(parsed.is_object());
}

#[test]
fn openapi_has_version() {
    let spec = generate_full_openapi();
    assert!(spec.contains("\"openapi\": \"3.1.0\""));
}

#[test]
fn openapi_has_paths() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let paths = parsed["paths"].as_object().unwrap();
    assert!(paths.contains_key("/api/users"));
    assert!(paths.contains_key("/api/users/{id}"));
}

#[test]
fn openapi_has_operations() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    assert!(parsed["paths"]["/api/users"]["get"].is_object());
    assert!(parsed["paths"]["/api/users"]["post"].is_object());
    assert!(parsed["paths"]["/api/users/{id}"]["get"].is_object());
    assert!(parsed["paths"]["/api/users/{id}"]["put"].is_object());
    assert!(parsed["paths"]["/api/users/{id}"]["delete"].is_object());
}

#[test]
fn openapi_has_operation_ids() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    assert_eq!(
        parsed["paths"]["/api/users"]["get"]["operationId"],
        "listUsers"
    );
    assert_eq!(
        parsed["paths"]["/api/users"]["post"]["operationId"],
        "createUser"
    );
}

#[test]
fn openapi_has_component_schemas() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let schemas = parsed["components"]["schemas"].as_object().unwrap();
    assert!(schemas.contains_key("User"));
    assert!(schemas.contains_key("Role"));
    assert!(schemas.contains_key("CreateUserBody"));
    assert!(schemas.contains_key("UpdateUserBody"));
}

#[test]
fn openapi_user_schema_has_fields() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let user = &parsed["components"]["schemas"]["User"];
    assert_eq!(user["type"], "object");
    assert!(user["properties"]["id"]["type"] == "integer");
    assert!(user["properties"]["name"]["type"] == "string");
    assert!(user["properties"]["email"]["type"] == "string");
}

#[test]
fn openapi_role_enum_is_string() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let role = &parsed["components"]["schemas"]["Role"];
    assert_eq!(role["type"], "string");
    let values = role["enum"].as_array().unwrap();
    assert_eq!(values.len(), 3);
}

#[test]
fn openapi_query_params_have_defaults() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let params = parsed["paths"]["/api/users"]["get"]["parameters"]
        .as_array()
        .unwrap();
    // Find the "page" param
    let page = params.iter().find(|p| p["name"] == "page").unwrap();
    assert_eq!(page["schema"]["default"], 1);
    assert_eq!(page["required"], false);
}

#[test]
fn openapi_path_params_are_required() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let params = parsed["paths"]["/api/users/{id}"]["get"]["parameters"]
        .as_array()
        .unwrap();
    let id = params.iter().find(|p| p["name"] == "id").unwrap();
    assert_eq!(id["in"], "path");
    assert_eq!(id["required"], true);
}

#[test]
fn openapi_error_responses_have_status_codes() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let responses = parsed["paths"]["/api/users"]["post"]["responses"]
        .as_object()
        .unwrap();
    assert!(responses.contains_key("200"));
    assert!(responses.contains_key("400"));
    assert!(responses.contains_key("409"));
}

#[test]
fn openapi_post_has_request_body() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let body = &parsed["paths"]["/api/users"]["post"]["requestBody"];
    assert_eq!(body["required"], true);
    assert!(
        body["content"]["application/json"]["schema"]["$ref"]
            .as_str()
            .unwrap()
            .contains("CreateUserBody")
    );
}

#[test]
fn openapi_descriptions_from_doc_comments() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let list_desc = parsed["paths"]["/api/users"]["get"]["description"]
        .as_str()
        .unwrap();
    assert!(list_desc.contains("List all users"));
    let user_desc = parsed["components"]["schemas"]["User"]["description"]
        .as_str()
        .unwrap();
    assert!(user_desc.contains("registered user"));
}

#[test]
fn openapi_void_response_is_204() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let responses = parsed["paths"]["/api/users/{id}"]["delete"]["responses"]
        .as_object()
        .unwrap();
    assert!(responses.contains_key("204"));
}

#[test]
fn openapi_regeneration_is_deterministic() {
    let spec1 = generate_full_openapi();
    let spec2 = generate_full_openapi();
    assert_eq!(spec1, spec2, "OpenAPI spec is not deterministic");
}

#[test]
fn openapi_list_response_is_array() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    // listUsers response is List<User> → type: array, items: $ref User
    let schema = &parsed["paths"]["/api/users"]["get"]["responses"]["200"]["content"]["application/json"]
        ["schema"];
    assert_eq!(schema["type"], "array");
    assert!(schema["items"]["$ref"].as_str().unwrap().contains("User"));
}

#[test]
fn openapi_optional_field_is_nullable() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    // User.bio is Option<String> → anyOf with null
    let bio = &parsed["components"]["schemas"]["User"]["properties"]["bio"];
    assert!(
        bio["anyOf"].is_array(),
        "Option<String> should use anyOf for nullable"
    );
}

#[test]
fn openapi_optional_field_not_required() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let required = parsed["components"]["schemas"]["User"]["required"]
        .as_array()
        .unwrap();
    let required_names: Vec<&str> = required.iter().filter_map(|v| v.as_str()).collect();
    assert!(required_names.contains(&"id"));
    assert!(required_names.contains(&"name"));
    assert!(
        !required_names.contains(&"bio"),
        "bio is Option<String> and should not be required"
    );
}

#[test]
fn openapi_query_without_default_is_required() {
    // Build a schema with a required query param (no default, not Option)
    let source = r#"
struct Item { Int id  String name }
endpoint search: GET "/api/search" {
    query { String term }
    response List<Item>
}
"#;
    let tokens = tokenize(source, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    let spec_str = phoenix_codegen::generate_openapi(&program, &result);
    let parsed: serde_json::Value = serde_json::from_str(&spec_str).unwrap();
    let params = parsed["paths"]["/api/search"]["get"]["parameters"]
        .as_array()
        .unwrap();
    let term = params.iter().find(|p| p["name"] == "term").unwrap();
    assert_eq!(term["required"], true);
}

#[test]
fn openapi_option_query_param_not_required() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let params = parsed["paths"]["/api/users"]["get"]["parameters"]
        .as_array()
        .unwrap();
    let search = params.iter().find(|p| p["name"] == "search").unwrap();
    assert_eq!(
        search["required"], false,
        "Option<String> query param should not be required"
    );
}

#[test]
fn openapi_derived_body_has_correct_required() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    // CreateUserBody = User omit { id, bio } → name, email, age are required
    let body_schema = &parsed["components"]["schemas"]["CreateUserBody"];
    let required = body_schema["required"].as_array().unwrap();
    let names: Vec<&str> = required.iter().filter_map(|v| v.as_str()).collect();
    assert!(names.contains(&"name"));
    assert!(names.contains(&"email"));
    assert!(names.contains(&"age"));
    assert!(!names.contains(&"id"), "id should be omitted");
}

#[test]
fn openapi_partial_body_has_no_required() {
    let spec = generate_full_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    // UpdateUserBody = User omit { id } partial → all fields optional
    let body_schema = &parsed["components"]["schemas"]["UpdateUserBody"];
    // Either "required" is absent or empty
    let has_required = body_schema
        .get("required")
        .map(|r| r.as_array().map(|a| !a.is_empty()).unwrap_or(false))
        .unwrap_or(false);
    assert!(!has_required, "partial body should have no required fields");
}

// ── server.ts integration: additional coverage ──────────────────────

#[test]
fn server_handles_endpoint_with_no_errors() {
    let files = generate_full_schema();
    // getUser has error { NotFound(404) } but listUsers has no errors
    // Check that listUsers route still has a catch block with 500 fallback
    let server_str = &files.server;
    assert!(server_str.contains("res.status(500).json({ error: \"Internal Server Error\" })"));
}

#[test]
fn server_has_correct_route_count() {
    let files = generate_full_schema();
    let get_count = files.server.matches("router.get(").count();
    let post_count = files.server.matches("router.post(").count();
    let put_count = files.server.matches("router.put(").count();
    let delete_count = files.server.matches("router.delete(").count();
    assert_eq!(
        get_count, 2,
        "should have 2 GET routes (listUsers, getUser)"
    );
    assert_eq!(post_count, 1, "should have 1 POST route (createUser)");
    assert_eq!(put_count, 1, "should have 1 PUT route (updateUser)");
    assert_eq!(delete_count, 1, "should have 1 DELETE route (deleteUser)");
}

// ── Where constraint integration tests ──────────────────────────────

const CONSTRAINED_SCHEMA: &str = r#"
struct User {
    Int id
    String name where self.length > 0 && self.length <= 100
    String email where self.contains("@") && self.length > 3
    Int age where self >= 0 && self <= 150
}

endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
"#;

fn generate_constrained() -> phoenix_codegen::GeneratedFiles {
    let tokens = tokenize(CONSTRAINED_SCHEMA, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    assert!(
        result.diagnostics.is_empty(),
        "check errors: {:?}",
        result.diagnostics
    );
    phoenix_codegen::generate_typescript(&program, &result)
}

fn generate_constrained_openapi() -> String {
    let tokens = tokenize(CONSTRAINED_SCHEMA, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    assert!(
        result.diagnostics.is_empty(),
        "check errors: {:?}",
        result.diagnostics
    );
    phoenix_codegen::generate_openapi(&program, &result)
}

#[test]
fn constraint_types_has_validation_error_class() {
    let files = generate_constrained();
    assert!(
        files
            .types
            .contains("export class ValidationError extends Error")
    );
}

#[test]
fn constraint_types_has_validate_function() {
    let files = generate_constrained();
    assert!(
        files
            .types
            .contains("export function validateCreateUserBody(input: unknown): CreateUserBody")
    );
}

#[test]
fn constraint_validate_checks_type() {
    let files = generate_constrained();
    assert!(files.types.contains("typeof obj.name !== 'string'"));
    assert!(files.types.contains("typeof obj.age !== 'number'"));
}

#[test]
fn constraint_validate_checks_constraint() {
    let files = generate_constrained();
    // name: self.length > 0 && self.length <= 100
    assert!(files.types.contains("obj.name.length"));
    // email: self.contains("@")
    assert!(files.types.contains("obj.email.includes"));
    // age: self >= 0 && self <= 150
    assert!(files.types.contains("obj.age >= 0"));
    assert!(files.types.contains("obj.age <= 150"));
}

#[test]
fn constraint_server_calls_validate() {
    let files = generate_constrained();
    assert!(files.server.contains("validateCreateUserBody(req.body)"));
}

#[test]
fn constraint_server_imports_validation() {
    let files = generate_constrained();
    assert!(
        files
            .server
            .contains("import { ValidationError, validateCreateUserBody } from \"./types\"")
    );
}

#[test]
fn constraint_server_catches_validation_error() {
    let files = generate_constrained();
    assert!(files.server.contains("instanceof ValidationError"));
    assert!(files.server.contains("res.status(400)"));
}

#[test]
fn constraint_openapi_has_minimum_maximum() {
    let spec = generate_constrained_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let age = &parsed["components"]["schemas"]["User"]["properties"]["age"];
    assert_eq!(age["minimum"], 0);
    assert_eq!(age["maximum"], 150);
}

#[test]
fn constraint_openapi_has_min_max_length() {
    let spec = generate_constrained_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let name = &parsed["components"]["schemas"]["User"]["properties"]["name"];
    assert_eq!(
        name["minLength"], 1,
        "self.length > 0 should become minLength: 1"
    );
    assert_eq!(name["maxLength"], 100);
}

#[test]
fn constraint_openapi_derived_body_inherits_constraints() {
    let spec = generate_constrained_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    // CreateUserBody = User omit { id }, so name/email/age should have constraints
    let body = &parsed["components"]["schemas"]["CreateUserBody"];
    let age = &body["properties"]["age"];
    assert_eq!(age["minimum"], 0);
    assert_eq!(age["maximum"], 150);
}

#[test]
fn constraint_openapi_exclusive_bounds() {
    // self > 0 → exclusiveMinimum, self < 100 → exclusiveMaximum
    let source = r#"
struct Item { Int id  Int score where self > 0 && self < 100 }
endpoint create: POST "/api/items" { body Item omit { id }  response Item }
"#;
    let tokens = tokenize(source, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    let spec = phoenix_codegen::generate_openapi(&program, &result);
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let score = &parsed["components"]["schemas"]["Item"]["properties"]["score"];
    assert_eq!(score["exclusiveMinimum"], 0);
    assert_eq!(score["exclusiveMaximum"], 100);
}

#[test]
fn constraint_openapi_float_bounds() {
    let source = r#"
struct Item { Float price where self >= 0.5 && self <= 999.99 }
"#;
    let tokens = tokenize(source, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    let spec = phoenix_codegen::generate_openapi(&program, &result);
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let price = &parsed["components"]["schemas"]["Item"]["properties"]["price"];
    assert_eq!(price["minimum"], 0.5);
    assert_eq!(price["maximum"], 999.99);
}

#[test]
fn constraint_openapi_pick_inherits_constraints() {
    let source = r#"
struct User {
    Int id
    String name where self.length > 0 && self.length <= 50
    String email where self.contains("@")
    Int age where self >= 0
}
endpoint updateName: PATCH "/api/users/{id}" {
    body User pick { name }
    response User
}
"#;
    let tokens = tokenize(source, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    let spec = phoenix_codegen::generate_openapi(&program, &result);
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let body = &parsed["components"]["schemas"]["UpdateNameBody"];
    let name = &body["properties"]["name"];
    assert_eq!(name["minLength"], 1, "self.length > 0 → minLength: 1");
    assert_eq!(name["maxLength"], 50);
}

#[test]
fn constraint_openapi_field_without_constraint_no_extra_keywords() {
    let spec = generate_constrained_openapi();
    let parsed: serde_json::Value = serde_json::from_str(&spec).unwrap();
    let id = &parsed["components"]["schemas"]["User"]["properties"]["id"];
    // id has no constraint, should just be { "type": "integer" }
    assert_eq!(id["type"], "integer");
    assert!(
        id.get("minimum").is_none(),
        "unconstrained field should have no minimum"
    );
    assert!(
        id.get("maximum").is_none(),
        "unconstrained field should have no maximum"
    );
}

// ── Schema declaration codegen tests (no-op) ────────────────────────

const SCHEMA_SOURCE: &str = r#"
struct User { Int id  String name  String email }

endpoint listUsers: GET "/api/users" {
    response List<User>
}

schema db {
    table users from User {
        primary key id
        unique email
    }
}
"#;

fn generate_with_schema() -> phoenix_codegen::GeneratedFiles {
    let tokens = tokenize(SCHEMA_SOURCE, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    assert!(
        result.diagnostics.is_empty(),
        "check errors: {:?}",
        result.diagnostics
    );
    phoenix_codegen::generate_typescript(&program, &result)
}

fn generate_without_schema() -> phoenix_codegen::GeneratedFiles {
    let source = r#"
struct User { Int id  String name  String email }

endpoint listUsers: GET "/api/users" {
    response List<User>
}
"#;
    let tokens = tokenize(source, SourceId(0));
    let (program, _) = parser::parse(&tokens);
    let result = checker::check(&program);
    phoenix_codegen::generate_typescript(&program, &result)
}

#[test]
fn schema_does_not_affect_types_ts() {
    let with = generate_with_schema();
    let without = generate_without_schema();
    assert_eq!(
        with.types, without.types,
        "schema should not affect types.ts"
    );
}

#[test]
fn schema_does_not_affect_client_ts() {
    let with = generate_with_schema();
    let without = generate_without_schema();
    assert_eq!(
        with.client, without.client,
        "schema should not affect client.ts"
    );
}

#[test]
fn schema_does_not_affect_handlers_ts() {
    let with = generate_with_schema();
    let without = generate_without_schema();
    assert_eq!(
        with.handlers, without.handlers,
        "schema should not affect handlers.ts"
    );
}

#[test]
fn schema_does_not_affect_server_ts() {
    let with = generate_with_schema();
    let without = generate_without_schema();
    assert_eq!(
        with.server, without.server,
        "schema should not affect server.ts"
    );
}

#[test]
fn schema_does_not_affect_openapi() {
    let tokens_with = tokenize(SCHEMA_SOURCE, SourceId(0));
    let (program_with, _) = parser::parse(&tokens_with);
    let result_with = checker::check(&program_with);
    let openapi_with = phoenix_codegen::generate_openapi(&program_with, &result_with);

    let source_without = r#"
struct User { Int id  String name  String email }
endpoint listUsers: GET "/api/users" {
    response List<User>
}
"#;
    let tokens_without = tokenize(source_without, SourceId(0));
    let (program_without, _) = parser::parse(&tokens_without);
    let result_without = checker::check(&program_without);
    let openapi_without = phoenix_codegen::generate_openapi(&program_without, &result_without);

    assert_eq!(
        openapi_with, openapi_without,
        "schema should not affect OpenAPI output"
    );
}
