//! Go code generation for Phoenix Gen.
//!
//! Generates four files from a Phoenix program:
//! - **types.go** — Go structs with JSON tags, string-typed enums with constants,
//!   and derived body types.
//! - **client.go** — an HTTP client with typed methods for each endpoint.
//! - **handlers.go** — a `Handlers` interface that server implementations must
//!   satisfy.
//! - **server.go** — a `net/http`-compatible router that wires HTTP routes to
//!   handler methods with parameter parsing and error mapping.

use std::collections::BTreeSet;

use phoenix_parser::ast::{Declaration, EnumDecl, Program, StructDecl};
use phoenix_sema::Analysis;
use phoenix_sema::checker::{DefaultValue, EndpointInfo, QueryParamInfo};
use phoenix_sema::types::Type;

/// The output of Go code generation: four file contents.
pub struct GoFiles {
    /// Content for `types.go` — structs, enums, derived body types.
    pub types: String,
    /// Content for `client.go` — HTTP client SDK.
    pub client: String,
    /// Content for `handlers.go` — handler interface.
    pub handlers: String,
    /// Content for `server.go` — net/http router wiring.
    pub server: String,
}

/// Generates Go code from a parsed and type-checked Phoenix program.
pub fn generate_go(program: &Program, check_result: &Analysis) -> GoFiles {
    let generator = GoGenerator::new(check_result);
    generator.generate(program)
}

/// Internal Go code generator.
struct GoGenerator<'a> {
    check_result: &'a Analysis,
    types_out: String,
    client_out: String,
    handlers_out: String,
    server_out: String,
    emitted_derived_types: BTreeSet<String>,
    /// Whether types.go needs a `"fmt"` import (for Validate methods).
    types_needs_fmt: bool,
    /// Whether types.go needs a `"strings"` import (for contains constraints).
    types_needs_strings: bool,
    /// Whether client.go needs a `"fmt"` import. Every client method formats its
    /// URL with `fmt.Sprintf` and wraps HTTP errors with `fmt.Errorf`, so this is
    /// true iff at least one endpoint exists — a schema with types but no
    /// endpoints would otherwise emit an unused `fmt` import.
    client_needs_fmt: bool,
    /// Whether client.go needs a `"net/url"` import (any endpoint has query params).
    client_needs_url: bool,
    /// Whether client.go needs a `"strconv"` import (any non-String query param).
    client_needs_strconv: bool,
    /// Whether client.go needs a `"bytes"` import (any endpoint has a request body).
    client_needs_bytes: bool,
    /// Whether client.go needs an `"encoding/json"` import (any endpoint has a
    /// request body to marshal or a response to decode).
    client_needs_json: bool,
    /// Whether server.go needs an `"encoding/json"` import (any endpoint has a
    /// body to decode or a response to encode).
    server_needs_json: bool,
    /// Whether server.go needs a `"strconv"` import (any numeric/bool query param).
    server_needs_strconv: bool,
    /// Whether server.go needs a `"strings"` import (any endpoint maps errors).
    server_needs_strings: bool,
}

impl<'a> GoGenerator<'a> {
    /// Creates a new Go generator with the given semantic analysis results.
    fn new(check_result: &'a Analysis) -> Self {
        Self {
            check_result,
            types_out: String::new(),
            client_out: String::new(),
            handlers_out: String::new(),
            server_out: String::new(),
            emitted_derived_types: BTreeSet::new(),
            types_needs_fmt: false,
            types_needs_strings: false,
            client_needs_fmt: false,
            client_needs_url: false,
            client_needs_strconv: false,
            client_needs_bytes: false,
            client_needs_json: false,
            server_needs_json: false,
            server_needs_strconv: false,
            server_needs_strings: false,
        }
    }

    /// Generates `types.go`, `client.go`, `handlers.go`, and `server.go`
    /// from the program AST.
    fn generate(mut self, program: &Program) -> GoFiles {
        // ── types.go (body — header/imports composed at end) ────
        for decl in &program.declarations {
            match decl {
                Declaration::Struct(s) => {
                    self.emit_struct(s);
                    self.emit_validate_method(s);
                }
                Declaration::Enum(e) => self.emit_enum(e),
                _ => {}
            }
        }

        for ep in &self.check_result.endpoints {
            self.emit_derived_type(ep);
        }

        // Compose types.go with header and conditional imports
        let types_body = std::mem::take(&mut self.types_out);
        self.types_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");
        self.types_out.push_str("package api\n\n");
        if self.types_needs_fmt {
            let mut imports = vec!["\"fmt\""];
            if self.types_needs_strings {
                imports.push("\"strings\"");
            }
            self.types_out.push_str(&format!(
                "import (\n{}\n)\n\n",
                imports
                    .iter()
                    .map(|i| format!("\t{i}"))
                    .collect::<Vec<_>>()
                    .join("\n")
            ));
        }
        // Each emitted type ends with `}\n\n`, leaving a trailing blank line at
        // EOF. gofmt requires exactly one trailing newline, so trim and re-add.
        self.types_out.push_str(types_body.trim_end());
        self.types_out.push('\n');

        // ── client.go ───────────────────────────────────────────────
        // client.go body (struct, constructor, methods) is buffered first so the
        // import block can be composed conditionally afterward.
        self.client_out
            .push_str("// ApiClient is a typed HTTP client for the API.\n");
        self.client_out
            .push_str("type ApiClient struct {\n\tBaseURL string\n\tClient  *http.Client\n}\n\n");
        self.client_out
            .push_str("// NewApiClient creates a new API client with the given base URL.\n");
        self.client_out.push_str(
            "func NewApiClient(baseURL string) *ApiClient {\n\treturn &ApiClient{BaseURL: baseURL, Client: http.DefaultClient}\n}\n",
        );

        for ep in &self.check_result.endpoints {
            self.emit_client_method(ep);
        }

        // Compose client.go with header and conditional imports. `net/http` is
        // always used (the client struct holds a `*http.Client`); the rest are
        // emitted only when referenced so the output has no unused imports:
        // `fmt` for URL formatting + error wrapping (any endpoint), `bytes` for a
        // request-body reader, `encoding/json` for body/response (de)serialization,
        // `net/url` for query params, and `strconv` for non-String query-param
        // formatting.
        let client_body = std::mem::take(&mut self.client_out);
        self.client_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");
        self.client_out.push_str("package api\n\n");
        {
            let mut imports = vec!["\"net/http\""];
            if self.client_needs_fmt {
                imports.push("\"fmt\"");
            }
            if self.client_needs_bytes {
                imports.push("\"bytes\"");
            }
            if self.client_needs_json {
                imports.push("\"encoding/json\"");
            }
            if self.client_needs_url {
                imports.push("\"net/url\"");
            }
            if self.client_needs_strconv {
                imports.push("\"strconv\"");
            }
            imports.sort_unstable();
            self.client_out.push_str(&format!(
                "import (\n{}\n)\n\n",
                imports
                    .iter()
                    .map(|i| format!("\t{i}"))
                    .collect::<Vec<_>>()
                    .join("\n")
            ));
        }
        self.client_out.push_str(&client_body);

        // ── handlers.go ─────────────────────────────────────────────
        self.handlers_out
            .push_str("// Generated by Phoenix Gen — implement the handler methods below.\n\n");
        self.handlers_out.push_str("package api\n\n");
        self.handlers_out.push_str(
            "// Handlers defines the interface that server implementations must satisfy.\n",
        );
        self.handlers_out.push_str("type Handlers interface {\n");

        for ep in &self.check_result.endpoints {
            self.emit_handler_method(ep);
        }

        self.handlers_out.push_str("}\n");

        // ── server.go (body — header/imports composed at end) ───────
        self.server_out.push_str(
            "// NewRouter creates an http.ServeMux that routes requests to the given handlers.\n",
        );
        self.server_out
            .push_str("func NewRouter(h Handlers) *http.ServeMux {\n");
        self.server_out.push_str("\tmux := http.NewServeMux()\n");

        for ep in &self.check_result.endpoints {
            self.emit_server_route(ep);
        }

        self.server_out.push_str("\treturn mux\n}\n");

        // Compose server.go with header and conditional imports. `net/http` is
        // always used (the router and `http.Error`); the rest are emitted only
        // when actually referenced so the output is free of unused imports:
        // `encoding/json` for body/response (de)serialization, `strconv` for
        // numeric/bool query-param parsing, `strings` for error mapping.
        let server_body = std::mem::take(&mut self.server_out);
        self.server_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");
        self.server_out.push_str("package api\n\n");
        {
            let mut imports = vec!["\"net/http\""];
            if self.server_needs_json {
                imports.push("\"encoding/json\"");
            }
            if self.server_needs_strconv {
                imports.push("\"strconv\"");
            }
            if self.server_needs_strings {
                imports.push("\"strings\"");
            }
            imports.sort_unstable();
            self.server_out.push_str(&format!(
                "import (\n{}\n)\n\n",
                imports
                    .iter()
                    .map(|i| format!("\t{i}"))
                    .collect::<Vec<_>>()
                    .join("\n")
            ));
        }
        self.server_out.push_str(&server_body);

        GoFiles {
            types: self.types_out,
            client: self.client_out,
            handlers: self.handlers_out,
            server: self.server_out,
        }
    }

    // ── types.go emission ───────────────────────────────────────────

    /// Emits a Go struct with JSON tags for a Phoenix struct.
    fn emit_struct(&mut self, s: &StructDecl) {
        if let Some(ref doc) = s.doc_comment {
            self.types_out
                .push_str(&format!("// {} is {}.\n", s.name, doc.to_lowercase()));
        }
        let rows: Vec<(String, String, String)> = self
            .check_result
            .module
            .struct_info_by_name(&s.name)
            .map(|info| {
                info.fields
                    .iter()
                    .map(|f| {
                        (
                            to_pascal_case(&f.name),
                            type_to_go(&f.ty),
                            format!("`json:\"{}\"`", f.name),
                        )
                    })
                    .collect()
            })
            .unwrap_or_default();
        self.types_out.push_str(&render_struct(&s.name, &rows));
    }

    /// Emits Go string constants for a Phoenix enum.
    fn emit_enum(&mut self, e: &EnumDecl) {
        let all_unit = e.variants.iter().all(|v| v.fields.is_empty());
        if !all_unit {
            return;
        }

        if let Some(ref doc) = e.doc_comment {
            self.types_out
                .push_str(&format!("// {} is {}.\n", e.name, doc.to_lowercase()));
        }
        self.types_out
            .push_str(&format!("type {} string\n\n", e.name));
        self.types_out.push_str("const (\n");
        // gofmt aligns the constant-name column within the block; the right-hand
        // side (`Type = "value"`) is identical-width-agnostic, so only the name
        // column needs padding to the block maximum.
        let names: Vec<String> = e
            .variants
            .iter()
            .map(|v| format!("{}{}", e.name, v.name))
            .collect();
        let max_name = names.iter().map(|n| n.len()).max().unwrap_or(0);
        for (name, v) in names.iter().zip(&e.variants) {
            self.types_out.push_str(&format!(
                "\t{:<width$} {} = \"{}\"\n",
                name,
                e.name,
                v.name,
                width = max_name
            ));
        }
        self.types_out.push_str(")\n\n");
    }

    /// Emits a derived Go struct for an endpoint body type.
    fn emit_derived_type(&mut self, ep: &EndpointInfo) {
        let Some(ref body) = ep.body else { return };
        let type_name = format!("{}Body", capitalize(&ep.name));

        if !self.emitted_derived_types.insert(type_name.clone()) {
            return;
        }

        let rows: Vec<(String, String, String)> = body
            .fields
            .iter()
            .map(|f| {
                let go_type = if f.optional {
                    format!("*{}", type_to_go(&f.ty))
                } else {
                    type_to_go(&f.ty)
                };
                let omitempty = if f.optional { ",omitempty" } else { "" };
                (
                    to_pascal_case(&f.name),
                    go_type,
                    format!("`json:\"{}{}\"`", f.name, omitempty),
                )
            })
            .collect();
        self.types_out.push_str(&render_struct(&type_name, &rows));
    }

    // ── validation emission ────────────────────────────────────────

    /// Emits a `Validate() error` method on a Go struct if any of its fields
    /// have `where` constraints.
    fn emit_validate_method(&mut self, s: &StructDecl) {
        let Some(info) = self.check_result.module.struct_info_by_name(&s.name) else {
            return;
        };
        if !info.fields.iter().any(|f| f.constraint.is_some()) {
            return;
        }

        self.types_needs_fmt = true;

        self.types_out.push_str(&format!(
            "// Validate checks all field constraints for {}.\n",
            s.name
        ));
        self.types_out
            .push_str(&format!("func (s {}) Validate() error {{\n", s.name));

        for f in &info.fields {
            if let Some(ref constraint) = f.constraint {
                if constraint_needs_strings(constraint) {
                    self.types_needs_strings = true;
                }
                let is_option = matches!(&f.ty, Type::Generic(name, _) if name == "Option");
                let go_expr = constraint_expr_to_go(constraint, &f.name, is_option);
                // `constraint_expr_to_go` already wraps binary expressions in
                // parentheses; strip the redundant outer pair so the `!(...)`
                // guard matches gofmt's canonical output (no doubled parens).
                let go_expr = strip_outer_parens(&go_expr);
                if is_option {
                    self.types_out.push_str(&format!(
                        "\tif s.{} != nil && !({}) {{\n\t\treturn fmt.Errorf(\"{}: constraint violated\")\n\t}}\n",
                        to_pascal_case(&f.name), go_expr, f.name
                    ));
                } else {
                    self.types_out.push_str(&format!(
                        "\tif !({}) {{\n\t\treturn fmt.Errorf(\"{}: constraint violated\")\n\t}}\n",
                        go_expr, f.name
                    ));
                }
            }
        }

        self.types_out.push_str("\treturn nil\n}\n\n");
    }

    // ── client.go emission ──────────────────────────────────────────

    /// Emits a Go method on `ApiClient` for an endpoint.
    fn emit_client_method(&mut self, ep: &EndpointInfo) {
        let method_name = to_pascal_case(&ep.name);
        let http_method = ep.method.as_upper_str();
        let response_type = ep.response.as_ref().map(type_to_go);

        // Build parameter list
        let mut params = Vec::new();
        for pp in &ep.path_params {
            params.push(format!("{} string", to_camel(pp)));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(format!("body {}", body_type));
        }
        for qp in &ep.query_params {
            let go_type = type_to_go(&qp.ty);
            params.push(format!("{} {}", to_camel(&qp.name), go_type));
        }
        let params_str = params.join(", ");

        // Return type
        let return_sig = match &response_type {
            Some(rt) => format!("(*{}, error)", rt),
            None => "error".to_string(),
        };

        if let Some(ref doc) = ep.doc_comment {
            self.client_out
                .push_str(&format!("\n// {} {}.\n", method_name, doc.to_lowercase()));
        }
        self.client_out.push_str(&format!(
            "func (c *ApiClient) {}({}) {} {{\n",
            method_name, params_str, return_sig
        ));

        // Build URL. Every method formats its URL with `fmt.Sprintf` and (below)
        // wraps HTTP errors with `fmt.Errorf`, so emitting any method needs `fmt`.
        self.client_needs_fmt = true;
        let url_expr = build_go_url(&ep.path, &ep.path_params);
        self.client_out.push_str(&format!(
            "\tu := fmt.Sprintf(\"%s{}\", c.BaseURL{})\n",
            url_expr.0, url_expr.1
        ));

        // Query params
        if !ep.query_params.is_empty() {
            self.client_needs_url = true;
            self.client_out.push_str("\tq := url.Values{}\n");
            for qp in &ep.query_params {
                let name = to_camel(&qp.name);
                let (optional, inner) = query_param_shape(&qp.ty);
                // For an optional query param the value is a pointer; only set it
                // when non-nil, dereferencing for the formatting expression.
                let value_expr = if optional {
                    format!("*{name}")
                } else {
                    name.clone()
                };
                let set_expr = match inner {
                    Type::Int => {
                        self.client_needs_strconv = true;
                        format!(
                            "q.Set(\"{}\", strconv.FormatInt({}, 10))",
                            qp.name, value_expr
                        )
                    }
                    Type::Float => {
                        self.client_needs_strconv = true;
                        format!(
                            "q.Set(\"{}\", strconv.FormatFloat({}, 'f', -1, 64))",
                            qp.name, value_expr
                        )
                    }
                    Type::Bool => {
                        self.client_needs_strconv = true;
                        format!("q.Set(\"{}\", strconv.FormatBool({}))", qp.name, value_expr)
                    }
                    Type::String => format!("q.Set(\"{}\", {})", qp.name, value_expr),
                    _ => format!("q.Set(\"{}\", fmt.Sprint({}))", qp.name, value_expr),
                };
                if optional {
                    self.client_out
                        .push_str(&format!("\tif {name} != nil {{\n\t\t{set_expr}\n\t}}\n"));
                } else {
                    self.client_out.push_str(&format!("\t{set_expr}\n"));
                }
            }
            self.client_out.push_str("\tu += \"?\" + q.Encode()\n");
        }

        // Build request. A request body pulls in `bytes` (for the reader) and
        // `encoding/json` (to marshal); a response pulls in `encoding/json` to
        // decode. Track both so the import block carries only what's used.
        if response_type.is_some() {
            self.client_needs_json = true;
        }
        if ep.body.is_some() {
            self.client_needs_bytes = true;
            self.client_needs_json = true;
            self.client_out
                .push_str("\tdata, err := json.Marshal(body)\n");
            self.client_out
                .push_str("\tif err != nil {\n\t\treturn nil, err\n\t}\n");
            self.client_out.push_str(&format!(
                "\treq, err := http.NewRequest(\"{}\", u, bytes.NewReader(data))\n",
                http_method
            ));
            self.client_out
                .push_str("\tif err != nil {\n\t\treturn nil, err\n\t}\n");
            self.client_out
                .push_str("\treq.Header.Set(\"Content-Type\", \"application/json\")\n");
        } else {
            self.client_out.push_str(&format!(
                "\treq, err := http.NewRequest(\"{}\", u, nil)\n",
                http_method
            ));
            let err_ret = if response_type.is_some() {
                "nil, err"
            } else {
                "err"
            };
            self.client_out.push_str(&format!(
                "\tif err != nil {{\n\t\treturn {}\n\t}}\n",
                err_ret
            ));
        }

        // Execute
        let err_ret = if response_type.is_some() { "nil, " } else { "" };
        self.client_out
            .push_str("\tresp, err := c.Client.Do(req)\n");
        self.client_out.push_str(&format!(
            "\tif err != nil {{\n\t\treturn {}err\n\t}}\n",
            err_ret
        ));
        self.client_out.push_str("\tdefer resp.Body.Close()\n");
        self.client_out.push_str(&format!(
            "\tif resp.StatusCode >= 400 {{\n\t\treturn {}fmt.Errorf(\"HTTP %d\", resp.StatusCode)\n\t}}\n",
            err_ret
        ));

        // Decode response
        if let Some(ref rt) = response_type {
            self.client_out.push_str(&format!("\tvar result {}\n", rt));
            self.client_out.push_str(&format!(
                "\tif err := json.NewDecoder(resp.Body).Decode(&result); err != nil {{\n\t\treturn {}err\n\t}}\n",
                err_ret
            ));
            self.client_out.push_str("\treturn &result, nil\n");
        } else {
            self.client_out.push_str("\treturn nil\n");
        }

        self.client_out.push_str("}\n");
    }

    // ── handlers.go emission ────────────────────────────────────────

    /// Emits a Go interface method signature for an endpoint.
    fn emit_handler_method(&mut self, ep: &EndpointInfo) {
        let method_name = to_pascal_case(&ep.name);

        let mut params = Vec::new();
        for pp in &ep.path_params {
            params.push(format!("{} string", to_camel(pp)));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(format!("body {}", body_type));
        }
        for qp in &ep.query_params {
            params.push(format!("{} {}", to_camel(&qp.name), type_to_go(&qp.ty)));
        }
        let params_str = params.join(", ");

        let return_type = match ep.response.as_ref().map(type_to_go) {
            Some(rt) => format!("(*{}, error)", rt),
            None => "error".to_string(),
        };

        if let Some(ref doc) = ep.doc_comment {
            self.handlers_out
                .push_str(&format!("\t// {} {}.\n", method_name, doc.to_lowercase()));
        }
        self.handlers_out.push_str(&format!(
            "\t{}({}) {}\n",
            method_name, params_str, return_type
        ));
    }

    // ── server.go emission ──────────────────────────────────────────

    /// Emits a `net/http` handler registration for an endpoint.
    fn emit_server_route(&mut self, ep: &EndpointInfo) {
        let method = ep.method.as_upper_str();
        // Go 1.22+ mux pattern: "METHOD /path"
        let pattern = format!("{} {}", method, ep.path);

        self.server_out.push_str(&format!(
            "\tmux.HandleFunc(\"{}\", func(w http.ResponseWriter, r *http.Request) {{\n",
            pattern
        ));

        // Parse path params
        for pp in &ep.path_params {
            self.server_out.push_str(&format!(
                "\t\t{camel} := r.PathValue(\"{name}\")\n",
                name = pp,
                camel = to_camel(pp)
            ));
        }

        // Parse body
        if ep.body.is_some() {
            self.server_needs_json = true;
            let body_type = format!("{}Body", capitalize(&ep.name));
            self.server_out.push_str(&format!(
                "\t\tvar body {}\n\t\tif err := json.NewDecoder(r.Body).Decode(&body); err != nil {{\n\t\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n\t\t\treturn\n\t\t}}\n",
                body_type
            ));
        }

        // Parse query params. Required params parse into a value type; optional
        // params (`Option<T>`) parse into a `*T` that is nil when absent, matching
        // the handler signature produced by `emit_handler_method`.
        for qp in &ep.query_params {
            self.emit_query_param_parse(qp);
        }

        // Call handler
        let mut args = Vec::new();
        for pp in &ep.path_params {
            args.push(to_camel(pp));
        }
        if ep.body.is_some() {
            args.push("body".to_string());
        }
        for qp in &ep.query_params {
            args.push(to_camel(&qp.name));
        }
        let args_str = args.join(", ");

        let handler_name = to_pascal_case(&ep.name);

        // Error mapping uses `strings.Contains`; encoding a response uses
        // `encoding/json`. Record both so the import block stays minimal.
        if !ep.errors.is_empty() {
            self.server_needs_strings = true;
        }
        if ep.response.is_some() {
            self.server_needs_json = true;
            self.server_out.push_str(&format!(
                "\t\tresult, err := h.{}({})\n",
                handler_name, args_str
            ));
            self.server_out.push_str("\t\tif err != nil {\n");
            // Error mapping
            for (name, code) in &ep.errors {
                self.server_out.push_str(&format!(
                    "\t\t\tif strings.Contains(err.Error(), \"{name}\") {{\n\t\t\t\thttp.Error(w, \"{name}\", {code})\n\t\t\t\treturn\n\t\t\t}}\n"
                ));
            }
            self.server_out
                .push_str("\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n");
            self.server_out.push_str("\t\t\treturn\n\t\t}\n");
            self.server_out
                .push_str("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n");
            self.server_out
                .push_str("\t\tjson.NewEncoder(w).Encode(result)\n");
        } else {
            self.server_out
                .push_str(&format!("\t\terr := h.{}({})\n", handler_name, args_str));
            self.server_out.push_str("\t\tif err != nil {\n");
            for (name, code) in &ep.errors {
                self.server_out.push_str(&format!(
                    "\t\t\tif strings.Contains(err.Error(), \"{name}\") {{\n\t\t\t\thttp.Error(w, \"{name}\", {code})\n\t\t\t\treturn\n\t\t\t}}\n"
                ));
            }
            self.server_out
                .push_str("\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n");
            self.server_out.push_str("\t\t\treturn\n\t\t}\n");
            self.server_out
                .push_str("\t\tw.WriteHeader(http.StatusNoContent)\n");
        }

        self.server_out.push_str("\t})\n");
    }

    /// Emits server-side parsing for a single query parameter into a local whose
    /// Go type matches the handler signature ([`Self::emit_handler_method`]).
    ///
    /// Required params parse into a value (using the declared default, else the
    /// Go zero value); optional `Option<T>` params parse into a `*T` that stays
    /// nil when the parameter is absent or malformed. Numeric/bool parsing pulls
    /// in `strconv`; enum (named) params are produced via a direct `T(v)` string
    /// conversion, since Phoenix enums lower to `type T string`. That conversion
    /// is unchecked — an out-of-range value reaches the handler as-is, matching
    /// how Gen represents enums everywhere else (no runtime validation).
    fn emit_query_param_parse(&mut self, qp: &QueryParamInfo) {
        let camel = to_camel(&qp.name);
        let name = &qp.name;
        let (optional, inner) = query_param_shape(&qp.ty);

        // Optional params deliberately ignore `qp.default_value`: `Option<T>`
        // already models "may be absent" as a nil pointer, so a default would be
        // redundant (and there is no pointer slot to pre-seed). Only the required
        // branch below consults the declared default.
        let body = if optional {
            match inner {
                Type::Int => {
                    self.server_needs_strconv = true;
                    format!(
                        "var {camel} *int64\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\tif n, err := strconv.ParseInt(v, 10, 64); err == nil {{\n\t\t\t\t{camel} = &n\n\t\t\t}}\n\t\t}}\n"
                    )
                }
                Type::Float => {
                    self.server_needs_strconv = true;
                    format!(
                        "var {camel} *float64\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\tif n, err := strconv.ParseFloat(v, 64); err == nil {{\n\t\t\t\t{camel} = &n\n\t\t\t}}\n\t\t}}\n"
                    )
                }
                Type::Bool => {
                    self.server_needs_strconv = true;
                    format!(
                        "var {camel} *bool\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\tif b, err := strconv.ParseBool(v); err == nil {{\n\t\t\t\t{camel} = &b\n\t\t\t}}\n\t\t}}\n"
                    )
                }
                Type::String => {
                    format!(
                        "var {camel} *string\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\t{camel} = &v\n\t\t}}\n"
                    )
                }
                other => {
                    // Enum / named string-backed type: convert the raw value.
                    let go_type = type_to_go(other);
                    format!(
                        "var {camel} *{go_type}\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\tcv := {go_type}(v)\n\t\t\t{camel} = &cv\n\t\t}}\n"
                    )
                }
            }
        } else {
            let default = |fallback: &str| {
                qp.default_value
                    .as_ref()
                    .map(default_value_to_go)
                    .unwrap_or_else(|| fallback.to_string())
            };
            match inner {
                Type::Int => {
                    self.server_needs_strconv = true;
                    let default = default("0");
                    format!(
                        "{camel} := int64({default})\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\t{camel}, _ = strconv.ParseInt(v, 10, 64)\n\t\t}}\n"
                    )
                }
                Type::Float => {
                    self.server_needs_strconv = true;
                    let default = default("0");
                    format!(
                        "{camel} := float64({default})\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\t{camel}, _ = strconv.ParseFloat(v, 64)\n\t\t}}\n"
                    )
                }
                Type::Bool => {
                    self.server_needs_strconv = true;
                    let default = default("false");
                    format!(
                        "{camel} := {default}\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\t{camel}, _ = strconv.ParseBool(v)\n\t\t}}\n"
                    )
                }
                Type::String => {
                    let default = default("\"\"");
                    format!(
                        "{camel} := {default}\n\t\tif v := r.URL.Query().Get(\"{name}\"); v != \"\" {{\n\t\t\t{camel} = v\n\t\t}}\n"
                    )
                }
                other => {
                    // Enum / named string-backed type: convert the raw value.
                    let go_type = type_to_go(other);
                    format!("{camel} := {go_type}(r.URL.Query().Get(\"{name}\"))\n")
                }
            }
        };

        self.server_out.push_str("\t\t");
        self.server_out.push_str(&body);
    }
}

// ── Helper functions ─────────────────────────────────────────────────

/// Converts a Phoenix `Type` to a Go type string.
fn type_to_go(ty: &Type) -> String {
    match ty {
        Type::Int => "int64".to_string(),
        Type::Float => "float64".to_string(),
        Type::String => "string".to_string(),
        Type::Bool => "bool".to_string(),
        Type::Void => "".to_string(),
        Type::Named(name) => name.clone(),
        Type::Generic(name, args) if name == "List" && args.len() == 1 => {
            format!("[]{}", type_to_go(&args[0]))
        }
        Type::Generic(name, args) if name == "Map" && args.len() == 2 => {
            format!("map[{}]{}", type_to_go(&args[0]), type_to_go(&args[1]))
        }
        Type::Generic(name, args) if name == "Option" && args.len() == 1 => {
            format!("*{}", type_to_go(&args[0]))
        }
        // Trait objects map to a Go interface named after the trait.  The
        // interface itself is not emitted by Phoenix codegen today — callers
        // supplying `dyn Trait` fields must define the matching Go interface
        // in hand-written code.  Parallel to the TS/Python behavior.
        Type::Dyn(name) => name.clone(),
        _ => "interface{}".to_string(),
    }
}

/// Renders a complete `type NAME struct { ... }` declaration (trailing blank
/// line included) with gofmt-faithful field alignment.
///
/// An empty field set collapses to `type NAME struct{}` — gofmt rewrites the
/// multi-line `struct {\n}` form to that, so emitting it directly keeps
/// `gofmt -l` empty for fieldless structs (e.g. a body type with every field
/// omitted, or a struct sema couldn't resolve).
fn render_struct(name: &str, rows: &[(String, String, String)]) -> String {
    if rows.is_empty() {
        return format!("type {name} struct{{}}\n\n");
    }
    format!("type {name} struct {{\n{}}}\n\n", align_struct_fields(rows))
}

/// Renders Go struct fields as gofmt-aligned rows.
///
/// Each row is `(name, go_type, json_tag)`. gofmt aligns columns within a
/// contiguous field block by padding the name and type columns with spaces to
/// the block maximum (plus one separating space), with a single leading tab for
/// the struct-body indent. Emitting the exact spacing here keeps `gofmt -l`
/// empty without shelling out to gofmt.
fn align_struct_fields(rows: &[(String, String, String)]) -> String {
    let max_name = rows.iter().map(|(n, _, _)| n.len()).max().unwrap_or(0);
    let max_type = rows.iter().map(|(_, t, _)| t.len()).max().unwrap_or(0);
    let mut out = String::new();
    for (name, ty, tag) in rows {
        out.push_str(&format!(
            "\t{name:<nw$} {ty:<tw$} {tag}\n",
            nw = max_name,
            tw = max_type
        ));
    }
    out
}

/// Strips a single balanced outer pair of parentheses from `expr`, if the whole
/// string is wrapped in one. Used to avoid emitting doubled parens like
/// `!((expr))` that gofmt would rewrite.
///
/// Assumes `expr` is parenthesis-balanced (it always is — the only caller feeds
/// it [`constraint_expr_to_go`] output). The leading-`(`/trailing-`)` guard plus
/// that invariant mean the depth counter never decrements below zero, so the
/// scan cannot underflow on the inputs this is ever given.
fn strip_outer_parens(expr: &str) -> String {
    let bytes = expr.as_bytes();
    if bytes.first() != Some(&b'(') || bytes.last() != Some(&b')') {
        return expr.to_string();
    }
    // Verify the opening paren matches the closing paren (balanced wrap).
    let mut depth = 0usize;
    for (i, &b) in bytes.iter().enumerate() {
        match b {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    // The first '(' closes at index i; only strip if that's the
                    // final character (i.e. the whole expression is wrapped).
                    if i == bytes.len() - 1 {
                        return expr[1..expr.len() - 1].to_string();
                    }
                    return expr.to_string();
                }
            }
            _ => {}
        }
    }
    expr.to_string()
}

/// Inspects a query-param type and returns `(optional, inner)`.
///
/// For `Option<T>` this returns `(true, &T)`; for any other type `(false, ty)`.
/// Optional query params are represented as `*T` in client/handler signatures
/// and parsed into a nil-able pointer on the server.
fn query_param_shape(ty: &Type) -> (bool, &Type) {
    match ty {
        Type::Generic(name, args) if name == "Option" && args.len() == 1 => (true, &args[0]),
        other => (false, other),
    }
}

/// Converts a camelCase identifier to PascalCase (Go exported name).
fn to_pascal_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// Returns a camelCase identifier (Go unexported / parameter name).
/// Phoenix identifiers are already camelCase, so this is mostly identity.
fn to_camel(s: &str) -> String {
    s.to_string()
}

use crate::capitalize;

/// Builds a Go `fmt.Sprintf` format string and args from a Phoenix URL pattern.
///
/// Returns `(format_pattern, sprintf_args)`.
/// `/api/users/{id}` → `("/api/users/%d", ", id")`
fn build_go_url(path: &str, params: &[String]) -> (String, String) {
    let mut format_str = String::new();
    let mut in_brace = false;

    for c in path.chars() {
        if c == '{' {
            in_brace = true;
            format_str.push_str("%s"); // path params are strings
        } else if c == '}' {
            in_brace = false;
        } else if !in_brace {
            format_str.push(c);
        }
    }

    let args = if params.is_empty() {
        String::new()
    } else {
        format!(
            ", {}",
            params
                .iter()
                .map(|p| to_camel(p))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };

    (format_str, args)
}

/// Converts a `DefaultValue` to a Go literal.
fn default_value_to_go(val: &DefaultValue) -> String {
    match val {
        DefaultValue::Int(v) => v.to_string(),
        DefaultValue::Float(v) => v.to_string(),
        DefaultValue::String(v) => format!("\"{}\"", v),
        DefaultValue::Bool(true) => "true".to_string(),
        DefaultValue::Bool(false) => "false".to_string(),
    }
}

/// Recursively converts a Phoenix constraint `Expr` to a Go expression string.
///
/// Replaces `self` with the struct field accessor (`s.FieldName`), translates
/// `self.length` to `len(s.FieldName)`, and `self.contains(arg)` to
/// `strings.Contains(s.FieldName, arg)`.
///
/// When `deref` is true (for `Option` fields), the field is a pointer and
/// accesses are dereferenced (e.g., `*s.FieldName`).
fn constraint_expr_to_go(
    expr: &phoenix_parser::ast::Expr,
    field_name: &str,
    deref: bool,
) -> String {
    use phoenix_parser::ast::{BinaryOp, Expr, LiteralKind, UnaryOp};

    match expr {
        Expr::Ident(ident) if ident.name == "self" => {
            let accessor = format!("s.{}", to_pascal_case(field_name));
            if deref {
                format!("(*{})", accessor)
            } else {
                accessor
            }
        }
        Expr::Ident(ident) => ident.name.clone(),
        Expr::Literal(lit) => match &lit.kind {
            LiteralKind::Int(v) => v.to_string(),
            LiteralKind::Float(v) => v.to_string(),
            LiteralKind::String(v) => format!("\"{}\"", v),
            LiteralKind::Bool(v) => v.to_string(),
        },
        Expr::Binary(bin) => {
            let left = constraint_expr_to_go(&bin.left, field_name, deref);
            let right = constraint_expr_to_go(&bin.right, field_name, deref);
            let op = match bin.op {
                BinaryOp::Add => "+",
                BinaryOp::Sub => "-",
                BinaryOp::Mul => "*",
                BinaryOp::Div => "/",
                BinaryOp::Mod => "%",
                BinaryOp::Eq => "==",
                BinaryOp::NotEq => "!=",
                BinaryOp::Lt => "<",
                BinaryOp::Gt => ">",
                BinaryOp::LtEq => "<=",
                BinaryOp::GtEq => ">=",
                BinaryOp::And => "&&",
                BinaryOp::Or => "||",
            };
            format!("({left} {op} {right})")
        }
        Expr::Unary(un) => {
            let operand = constraint_expr_to_go(&un.operand, field_name, deref);
            match un.op {
                UnaryOp::Neg => format!("(-{operand})"),
                UnaryOp::Not => format!("(!{operand})"),
            }
        }
        // self.length → len(s.FieldName)
        Expr::FieldAccess(fa) if fa.field == "length" && is_self_ident_go(&fa.object) => {
            let accessor = format!("s.{}", to_pascal_case(field_name));
            if deref {
                format!("len(*{})", accessor)
            } else {
                format!("len({})", accessor)
            }
        }
        Expr::FieldAccess(fa) => {
            let object = constraint_expr_to_go(&fa.object, field_name, deref);
            format!("{object}.{}", fa.field)
        }
        // self.contains(arg) → strings.Contains(s.FieldName, arg)
        Expr::MethodCall(mc) if mc.method == "contains" && is_self_ident_go(&mc.object) => {
            let accessor = format!("s.{}", to_pascal_case(field_name));
            let args: Vec<String> = mc
                .args
                .iter()
                .map(|a| constraint_expr_to_go(a, field_name, deref))
                .collect();
            if deref {
                format!("strings.Contains(*{}, {})", accessor, args.join(", "))
            } else {
                format!("strings.Contains({}, {})", accessor, args.join(", "))
            }
        }
        Expr::MethodCall(mc) => {
            let object = constraint_expr_to_go(&mc.object, field_name, deref);
            let args: Vec<String> = mc
                .args
                .iter()
                .map(|a| constraint_expr_to_go(a, field_name, deref))
                .collect();
            format!("{object}.{}({})", mc.method, args.join(", "))
        }
        _ => "true".to_string(),
    }
}

/// Returns true if the expression is the `self` identifier.
fn is_self_ident_go(expr: &phoenix_parser::ast::Expr) -> bool {
    matches!(expr, phoenix_parser::ast::Expr::Ident(i) if i.name == "self")
}

/// Returns true if any part of a constraint expression uses a method call
/// that requires the `"strings"` import (e.g., `contains`).
fn constraint_needs_strings(expr: &phoenix_parser::ast::Expr) -> bool {
    use phoenix_parser::ast::Expr;
    match expr {
        Expr::Binary(bin) => {
            constraint_needs_strings(&bin.left) || constraint_needs_strings(&bin.right)
        }
        Expr::MethodCall(mc) if mc.method == "contains" => true,
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use phoenix_common::span::SourceId;
    use phoenix_lexer::lexer::tokenize;
    use phoenix_parser::parser;
    use phoenix_sema::checker;

    fn generate_from_source(source: &str) -> GoFiles {
        let tokens = tokenize(source, SourceId(0));
        let (program, parse_errors) = parser::parse(&tokens);
        assert!(parse_errors.is_empty(), "parse errors: {parse_errors:?}");
        let result = checker::check(&program);
        assert!(
            result.diagnostics.is_empty(),
            "check errors: {:?}",
            result.diagnostics
        );
        generate_go(&program, &result)
    }

    #[test]
    fn struct_to_go() {
        let files = generate_from_source(
            r#"
/** A registered user */
struct User {
    Int id
    String name
    Option<String> bio
}
"#,
        );
        insta::assert_snapshot!("go_struct", files.types);
    }

    #[test]
    fn simple_enum() {
        let files = generate_from_source("enum Role { Admin  Editor  Viewer }");
        insta::assert_snapshot!("go_enum", files.types);
    }

    #[test]
    fn get_with_path_param() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint getUser: GET "/api/users/{id}" {
    response User
}
"#,
        );
        insta::assert_snapshot!("go_get_client", files.client);
        insta::assert_snapshot!("go_get_handler", files.handlers);
        insta::assert_snapshot!("go_get_server", files.server);
    }

    #[test]
    fn post_with_body_and_errors() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
    error { Conflict(409) }
}
"#,
        );
        insta::assert_snapshot!("go_post_client", files.client);
        insta::assert_snapshot!("go_post_server", files.server);
        insta::assert_snapshot!("go_post_types", files.types);
    }

    #[test]
    fn query_params() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint listUsers: GET "/api/users" {
    query {
        Int page = 1
        Int limit = 20
        Option<String> search
    }
    response List<User>
}
"#,
        );
        insta::assert_snapshot!("go_query_client", files.client);
        insta::assert_snapshot!("go_query_server", files.server);
    }

    #[test]
    fn void_response() {
        let files = generate_from_source(
            r#"
endpoint deleteUser: DELETE "/api/users/{id}" {
    error { NotFound(404) }
}
"#,
        );
        insta::assert_snapshot!("go_void_client", files.client);
        insta::assert_snapshot!("go_void_server", files.server);
    }

    #[test]
    fn multiple_endpoints() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint listUsers: GET "/api/users" {
    response List<User>
}
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
endpoint getUser: GET "/api/users/{id}" {
    response User
}
endpoint deleteUser: DELETE "/api/users/{id}" {
}
"#,
        );
        insta::assert_snapshot!("go_multi_types", files.types);
        insta::assert_snapshot!("go_multi_client", files.client);
        insta::assert_snapshot!("go_multi_handlers", files.handlers);
        insta::assert_snapshot!("go_multi_server", files.server);
    }

    #[test]
    fn pascal_case_conversion() {
        assert_eq!(to_pascal_case("createUser"), "CreateUser");
        assert_eq!(to_pascal_case("id"), "Id");
        assert_eq!(to_pascal_case("listUsers"), "ListUsers");
        assert_eq!(to_pascal_case("User"), "User");
    }

    #[test]
    fn multiple_path_params() {
        let files = generate_from_source(
            r#"
struct Comment { Int id  String text }
endpoint getComment: GET "/api/users/{userId}/posts/{postId}" {
    response Comment
}
"#,
        );
        insta::assert_snapshot!("go_multi_path_client", files.client);
    }

    #[test]
    fn partial_body() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  Int age }
endpoint updateUser: PATCH "/api/users/{id}" {
    body User omit { id } partial
    response User
}
"#,
        );
        insta::assert_snapshot!("go_partial_types", files.types);
    }

    // ── Gap-filling tests ───────────────────────────────────────────

    /// `pick` modifier in derived body.
    #[test]
    fn pick_body() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email  Int age }
endpoint updateEmail: PATCH "/api/users/{id}" {
    body User pick { email }
    response User
}
"#,
        );
        insta::assert_snapshot!("go_pick_types", files.types);
    }

    /// Map<K,V> and Bool fields in struct.
    #[test]
    fn map_and_bool_fields() {
        let files = generate_from_source(
            r#"
struct Config {
    Map<String, String> settings
    Bool enabled
    Float threshold
}
"#,
        );
        insta::assert_snapshot!("go_map_bool_float_types", files.types);
    }

    /// PUT method.
    #[test]
    fn put_method() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint replaceUser: PUT "/api/users/{id}" {
    body User
    response User
}
"#,
        );
        insta::assert_snapshot!("go_put_server", files.server);
    }

    /// String and Bool query param defaults.
    #[test]
    fn string_bool_query_defaults() {
        let files = generate_from_source(
            r#"
struct Item { Int id  String name }
endpoint listItems: GET "/api/items" {
    query {
        String sortBy = "name"
        Bool ascending = true
    }
    response List<Item>
}
"#,
        );
        insta::assert_snapshot!("go_string_bool_query_client", files.client);
        insta::assert_snapshot!("go_string_bool_query_server", files.server);
    }

    /// Required `Float` and enum query params, plus an optional enum. Exercises
    /// the server-parse paths whose local type must match the handler signature:
    /// `float64` via `strconv.ParseFloat`, and a `T(v)` / `*T` conversion for the
    /// string-backed enum. Also pins the conditional server import set.
    #[test]
    fn float_and_enum_query_params() {
        let files = generate_from_source(
            r#"
enum Sort { Asc  Desc }
struct Item { Int id  String name }
endpoint listItems: GET "/api/items" {
    query {
        Float minScore = 0.5
        Sort sort
        Option<Sort> fallback
    }
    response List<Item>
}
"#,
        );
        insta::assert_snapshot!("go_float_enum_query_client", files.client);
        insta::assert_snapshot!("go_float_enum_query_server", files.server);
        insta::assert_snapshot!("go_float_enum_query_handlers", files.handlers);
    }

    /// A derived body that omits every field collapses to `struct{}` — gofmt
    /// rewrites the multi-line empty form, so this guards `render_struct`.
    #[test]
    fn empty_derived_body_is_gofmt_clean() {
        let files = generate_from_source(
            r#"
struct Ping { Int id }
endpoint ping: POST "/api/ping" {
    body Ping omit { id }
    response Ping
}
"#,
        );
        assert!(
            files.types.contains("type PingBody struct{}"),
            "expected collapsed empty struct, got:\n{}",
            files.types
        );
        assert!(!files.types.contains("type PingBody struct {\n}"));
    }

    /// A schema with types but no endpoints emits a client with no methods, so
    /// `fmt` (only ever used inside a method) must not be imported — an unused
    /// import would fail `go build`. `net/http` stays (the client struct holds a
    /// `*http.Client`).
    #[test]
    fn types_only_client_omits_fmt_import() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
"#,
        );
        assert!(
            !files.client.contains("\"fmt\""),
            "types-only client must not import fmt:\n{}",
            files.client
        );
        assert!(
            files.client.contains("\"net/http\""),
            "client must still import net/http:\n{}",
            files.client
        );
    }

    /// Enum as response type.
    #[test]
    fn enum_response() {
        let files = generate_from_source(
            r#"
enum Status { Active  Inactive  Banned }
endpoint getStatus: GET "/api/status" {
    response Status
}
"#,
        );
        insta::assert_snapshot!("go_enum_response_client", files.client);
    }

    /// default_value_to_go covers all variants.
    #[test]
    fn default_value_conversions() {
        assert_eq!(default_value_to_go(&DefaultValue::Int(42)), "42");
        assert_eq!(default_value_to_go(&DefaultValue::Float(1.5)), "1.5");
        assert_eq!(
            default_value_to_go(&DefaultValue::String("hello".into())),
            "\"hello\""
        );
        assert_eq!(default_value_to_go(&DefaultValue::Bool(true)), "true");
        assert_eq!(default_value_to_go(&DefaultValue::Bool(false)), "false");
    }

    // ── Validation tests ───────────────────────────────────────────

    /// Validate method with numeric and string length constraints.
    #[test]
    fn validate_numeric_and_string() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String name where self.length > 0 && self.length <= 100
    Int age where self >= 0 && self <= 150
}
"#,
        );
        insta::assert_snapshot!("go_validate_types", files.types);
    }

    /// Validate method with `contains` constraint (requires strings import).
    #[test]
    fn validate_contains() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String email where self.contains("@") && self.length > 3
}
"#,
        );
        insta::assert_snapshot!("go_validate_contains_types", files.types);
    }

    /// No Validate method when struct has no constraints.
    #[test]
    fn no_validate_without_constraints() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
"#,
        );
        assert!(
            !files.types.contains("Validate"),
            "should not emit Validate when no constraints"
        );
        assert!(
            !files.types.contains("import"),
            "should not emit imports when no constraints"
        );
    }

    /// `dyn Trait` maps to a bare Go interface name (the interface itself
    /// is expected to be defined in hand-written Go alongside the generated
    /// struct).  Parallel to the TS/Python behavior.
    #[test]
    fn dyn_type_erases_to_trait_name() {
        assert_eq!(type_to_go(&Type::Dyn("Drawable".to_string())), "Drawable");
    }
}
