//! Python code generation for Phoenix Gen.
//!
//! Generates four files from a Phoenix program:
//! - **models.py** — Pydantic `BaseModel` classes for structs, `str` enums,
//!   and derived body types with `Field()` constraint validation.
//! - **client.py** — an async `httpx`-based typed client with methods for
//!   each endpoint.
//! - **handlers.py** — a `Handlers` `Protocol` class that server implementations
//!   must satisfy.
//! - **server.py** — a FastAPI router that wires HTTP routes to handler methods
//!   with automatic parameter parsing and error mapping.

use std::collections::BTreeSet;

use phoenix_parser::ast::{Declaration, EnumDecl, Program, StructDecl};
use phoenix_sema::Analysis;
use phoenix_sema::checker::{DefaultValue, EndpointInfo};
use phoenix_sema::types::Type;

mod format;
use format::*;

/// The output of Python code generation: four file contents.
pub struct PythonFiles {
    /// Content for `__init__.py` — marks the output dir as a package so the
    /// intra-package relative imports (`from .models import ...`) resolve.
    pub init: String,
    /// Content for `models.py` — Pydantic models, enums, derived body types.
    pub models: String,
    /// Content for `client.py` — async httpx-based client.
    pub client: String,
    /// Content for `handlers.py` — Protocol-based handler interface.
    pub handlers: String,
    /// Content for `server.py` — FastAPI router wiring.
    pub server: String,
}

/// Generates Python code from a parsed and type-checked Phoenix program.
pub fn generate_python(program: &Program, check_result: &Analysis) -> PythonFiles {
    let generator = PyGenerator::new(check_result);
    generator.generate(program)
}

/// Internal Python code generator.
struct PyGenerator<'a> {
    check_result: &'a Analysis,
    models_out: String,
    client_out: String,
    handlers_out: String,
    server_out: String,
    emitted_derived_types: BTreeSet<String>,
}

impl<'a> PyGenerator<'a> {
    /// Creates a new Python generator with the given semantic analysis results.
    fn new(check_result: &'a Analysis) -> Self {
        Self {
            check_result,
            models_out: String::new(),
            client_out: String::new(),
            handlers_out: String::new(),
            server_out: String::new(),
            emitted_derived_types: BTreeSet::new(),
        }
    }

    /// Generates `models.py`, `client.py`, `handlers.py`, and `server.py`
    /// from the program AST.
    fn generate(mut self, program: &Program) -> PythonFiles {
        // ── models.py ───────────────────────────────────────────────
        self.models_out
            .push_str("# Generated by Phoenix Gen — do not edit manually.\n\n");
        self.models_out
            .push_str("from __future__ import annotations\n\n");
        self.emit_models_imports(program);

        for decl in &program.declarations {
            match decl {
                Declaration::Struct(s) => self.emit_model(s),
                Declaration::Enum(e) => self.emit_enum(e),
                _ => {}
            }
        }

        for ep in &self.check_result.endpoints {
            self.emit_derived_model(ep);
            self.emit_result_envelope(ep);
        }

        // ── client.py ───────────────────────────────────────────────
        self.client_out
            .push_str("# Generated by Phoenix Gen — do not edit manually.\n\n");
        self.emit_client_imports();
        self.client_out.push_str("\n\nclass ApiClient:\n");
        self.client_out.push_str(
            "    def __init__(self, base_url: str) -> None:\n        self.base_url = base_url\n        self.client = httpx.AsyncClient()\n",
        );

        for ep in &self.check_result.endpoints {
            self.emit_client_method(ep);
        }

        // ── handlers.py ─────────────────────────────────────────────
        self.handlers_out
            .push_str("# Generated by Phoenix Gen — implement the handler methods below.\n\n");
        self.emit_handler_imports();
        self.handlers_out
            .push_str("\n\nclass Handlers(Protocol):\n");

        for ep in &self.check_result.endpoints {
            self.emit_handler_method(ep);
        }

        // ── server.py ───────────────────────────────────────────────
        self.server_out
            .push_str("# Generated by Phoenix Gen — do not edit manually.\n\n");
        self.emit_server_imports();
        self.server_out
            .push_str("\n\ndef create_router(handlers: Handlers) -> APIRouter:\n");
        self.server_out.push_str("    router = APIRouter()\n");

        for ep in &self.check_result.endpoints {
            self.emit_server_route(ep);
        }

        ensure_blank_lines(&mut self.server_out, 1);
        self.server_out.push_str("    return router\n");

        PythonFiles {
            init: "# Generated by Phoenix Gen — do not edit manually.\n".to_string(),
            models: self.models_out,
            client: self.client_out,
            handlers: self.handlers_out,
            server: self.server_out,
        }
    }

    // ── models.py emission ──────────────────────────────────────────

    /// Emits imports needed by models.py based on what types are used.
    fn emit_models_imports(&mut self, program: &Program) {
        let mut needs_field = false;
        let mut needs_enum = false;

        for decl in &program.declarations {
            match decl {
                Declaration::Struct(s) => {
                    if let Some(info) = self.check_result.module.struct_info_by_name(&s.name)
                        && info.fields.iter().any(|f| f.constraint.is_some())
                    {
                        needs_field = true;
                    }
                }
                Declaration::Enum(_) => needs_enum = true,
                _ => {}
            }
        }
        // Check derived types for constraints too
        for ep in &self.check_result.endpoints {
            if let Some(ref body) = ep.body
                && body.fields.iter().any(|f| f.constraint.is_some())
            {
                needs_field = true;
            }
        }

        // Import groups, in isort order: standard library, then third party.
        // (`from __future__ import annotations` is emitted separately first.)
        if needs_enum {
            self.models_out.push_str("from enum import Enum\n\n");
        }
        if needs_field {
            self.models_out
                .push_str("from pydantic import BaseModel, Field\n");
        } else {
            self.models_out.push_str("from pydantic import BaseModel\n");
        }
        self.models_out.push('\n');
    }

    /// Emits a Pydantic BaseModel class for a Phoenix struct.
    fn emit_model(&mut self, s: &StructDecl) {
        ensure_blank_lines(&mut self.models_out, 2);
        if let Some(ref doc) = s.doc_comment {
            self.models_out.push_str(&render_hash_comment("", doc));
        }
        self.models_out
            .push_str(&format!("class {}(BaseModel):\n", s.name));

        if let Some(info) = self.check_result.module.struct_info_by_name(&s.name) {
            if info.fields.is_empty() {
                self.models_out.push_str("    pass\n");
            } else {
                for f in &info.fields {
                    let py_type = type_to_python(&f.ty);
                    let is_option = matches!(&f.ty, Type::Generic(name, _) if name == "Option");
                    let field_str = constraint_to_field(&f.constraint);

                    let snake = to_snake_case(&f.name);
                    if is_option {
                        if let Some(ref field_kwargs) = field_str {
                            self.models_out.push_str(&pydantic_field_line(
                                &snake,
                                &py_type,
                                "None",
                                field_kwargs,
                            ));
                        } else {
                            self.models_out
                                .push_str(&format!("    {snake}: {py_type} = None\n"));
                        }
                    } else if let Some(ref field_kwargs) = field_str {
                        self.models_out.push_str(&pydantic_field_line(
                            &snake,
                            &py_type,
                            "...",
                            field_kwargs,
                        ));
                    } else {
                        self.models_out
                            .push_str(&format!("    {snake}: {py_type}\n"));
                    }
                }
            }
        }
    }

    /// Emits a Python `str` Enum for a Phoenix enum with simple variants.
    fn emit_enum(&mut self, e: &EnumDecl) {
        let all_unit = e.variants.iter().all(|v| v.fields.is_empty());
        if !all_unit {
            return; // Skip complex enums for now
        }

        ensure_blank_lines(&mut self.models_out, 2);
        if let Some(ref doc) = e.doc_comment {
            self.models_out.push_str(&render_hash_comment("", doc));
        }
        self.models_out
            .push_str(&format!("class {}(str, Enum):\n", e.name));
        for v in &e.variants {
            self.models_out.push_str(&format!(
                "    {} = \"{}\"\n",
                to_screaming_snake(&v.name),
                v.name
            ));
        }
    }

    /// Emits a derived Pydantic model for an endpoint body type.
    fn emit_derived_model(&mut self, ep: &EndpointInfo) {
        let Some(ref body) = ep.body else { return };
        let type_name = format!("{}Body", capitalize(&ep.name));

        if !self.emitted_derived_types.insert(type_name.clone()) {
            return;
        }

        ensure_blank_lines(&mut self.models_out, 2);
        self.models_out
            .push_str(&format!("class {}(BaseModel):\n", type_name));

        if body.fields.is_empty() {
            self.models_out.push_str("    pass\n");
        } else {
            for f in &body.fields {
                let py_type = type_to_python(&f.ty);
                let field_str = constraint_to_field(&f.constraint);
                // A field can be optional either because the source type is
                // `Option<T>` or because a `partial` modifier marked it optional.
                // Avoid emitting `T | None | None` when both apply. Test the
                // source type structurally rather than sniffing the rendered
                // string: a container like `List<Option<T>>` renders as
                // `list[T | None]`, which is *not* itself optional and still
                // needs the outer `| None` when `partial` marks the field.
                let already_optional = matches!(&f.ty, Type::Generic(name, _) if name == "Option");
                let optional_type = if f.optional && !already_optional {
                    format!("{py_type} | None")
                } else {
                    py_type.clone()
                };

                let snake = to_snake_case(&f.name);
                if f.optional {
                    if let Some(ref kwargs) = field_str {
                        self.models_out.push_str(&pydantic_field_line(
                            &snake,
                            &optional_type,
                            "None",
                            kwargs,
                        ));
                    } else {
                        self.models_out
                            .push_str(&format!("    {snake}: {optional_type} = None\n"));
                    }
                } else if let Some(ref kwargs) = field_str {
                    self.models_out
                        .push_str(&pydantic_field_line(&snake, &py_type, "...", kwargs));
                } else {
                    self.models_out
                        .push_str(&format!("    {snake}: {py_type}\n"));
                }
            }
        }
    }

    /// Emits the `<Endpoint>Result` typed envelope model for an endpoint that
    /// declares response headers: the response body plus one typed field per
    /// response header (snake_case local name). Endpoints without response
    /// headers emit nothing here — they keep returning the bare response type.
    fn emit_result_envelope(&mut self, ep: &EndpointInfo) {
        if ep.response_headers.is_empty() {
            return;
        }
        let type_name = format!("{}Result", capitalize(&ep.name));
        if !self.emitted_derived_types.insert(type_name.clone()) {
            return;
        }

        let body_type = ep
            .response
            .as_ref()
            .map(type_to_python)
            .unwrap_or_else(|| "None".to_string());

        ensure_blank_lines(&mut self.models_out, 2);
        self.models_out
            .push_str(&format!("class {type_name}(BaseModel):\n"));
        self.models_out
            .push_str(&format!("    body: {body_type}\n"));
        for hp in &ep.response_headers {
            let snake = to_snake_case(&hp.name);
            let py_type = type_to_python(&hp.ty);
            // Response-header optionality is `Option<T>` ONLY. A `= default` on a
            // response header is meaningless (sema ignores it; the handler sets
            // the value), so a default must not flip the field to `T | None`.
            let is_optional = matches!(&hp.ty, Type::Generic(name, _) if name == "Option");
            if is_optional {
                self.models_out
                    .push_str(&format!("    {snake}: {py_type} = None\n"));
            } else {
                self.models_out
                    .push_str(&format!("    {snake}: {py_type}\n"));
            }
        }
    }

    // ── client.py emission ──────────────────────────────────────────

    /// Emits imports for the client file.
    fn emit_client_imports(&mut self) {
        // `Any` is only referenced by the `params: dict[str, Any]` dict that
        // query-bearing endpoints emit; importing it otherwise trips ruff F401.
        let needs_any = self
            .check_result
            .endpoints
            .iter()
            .any(|ep| !ep.query_params.is_empty());
        if needs_any {
            self.client_out
                .push_str("from typing import Any\n\nimport httpx\n");
        } else {
            self.client_out.push_str("import httpx\n");
        }

        let mut imports = BTreeSet::new();
        for ep in &self.check_result.endpoints {
            if ep.body.is_some() {
                imports.insert(format!("{}Body", capitalize(&ep.name)));
            }
            if let Some(ref resp) = ep.response {
                collect_python_imports(resp, &mut imports);
            }
            // Endpoints with response headers return the typed envelope, which
            // lives in models.py and must be imported here.
            if !ep.response_headers.is_empty() {
                imports.insert(format!("{}Result", capitalize(&ep.name)));
            }
        }
        if !imports.is_empty() {
            let joined: Vec<_> = imports.into_iter().collect();
            self.client_out.push('\n');
            self.client_out
                .push_str(&format_from_import(".models", &joined));
        }
    }

    /// Emits a single async client method for an endpoint.
    fn emit_client_method(&mut self, ep: &EndpointInfo) {
        let method = ep.method.as_lower_str();
        let fn_name = to_snake_case(&ep.name);
        // The bare response body type; the method's return type becomes the typed
        // `<Endpoint>Result` envelope when the endpoint declares response headers.
        let body_type = ep
            .response
            .as_ref()
            .map(type_to_python)
            .unwrap_or_else(|| "None".to_string());
        let response_type = if ep.response_headers.is_empty() {
            body_type.clone()
        } else {
            format!("{}Result", capitalize(&ep.name))
        };

        // Build parameter list
        let mut params = vec!["self".to_string()];
        for pp in &ep.path_params {
            params.push(format!("{}: str", to_snake_case(pp)));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(format!("body: {body_type}"));
        }
        // Query params and request headers are keyword-only.
        if !ep.query_params.is_empty() || !ep.headers.is_empty() {
            params.push("*".to_string());
            for qp in &ep.query_params {
                let py_type = type_to_python(&qp.ty);
                let is_optional =
                    qp.has_default || matches!(&qp.ty, Type::Generic(name, _) if name == "Option");
                if is_optional {
                    let default = qp
                        .default_value
                        .as_ref()
                        .map(default_value_to_python)
                        .unwrap_or_else(|| "None".to_string());
                    params.push(format!(
                        "{}: {} = {}",
                        to_snake_case(&qp.name),
                        py_type,
                        default
                    ));
                } else {
                    params.push(format!("{}: {}", to_snake_case(&qp.name), py_type));
                }
            }
            for hp in &ep.headers {
                let py_type = type_to_python(&hp.ty);
                let is_optional =
                    hp.has_default || matches!(&hp.ty, Type::Generic(name, _) if name == "Option");
                if is_optional {
                    let default = hp
                        .default_value
                        .as_ref()
                        .map(default_value_to_python)
                        .unwrap_or_else(|| "None".to_string());
                    params.push(format!(
                        "{}: {} = {}",
                        to_snake_case(&hp.name),
                        py_type,
                        default
                    ));
                } else {
                    params.push(format!("{}: {}", to_snake_case(&hp.name), py_type));
                }
            }
        }

        ensure_blank_lines(&mut self.client_out, 1);
        if let Some(ref doc) = ep.doc_comment {
            self.client_out.push_str(&render_hash_comment("    ", doc));
        }

        let sig = format_def_signature(
            "    ",
            "async def",
            &fn_name,
            &params,
            &format!(" -> {response_type}:"),
        );
        self.client_out.push_str(&sig);

        // Build URL
        let url = build_python_url(&ep.path);
        let has_query = !ep.query_params.is_empty();
        let has_headers = !ep.headers.is_empty();

        // Query params dict
        if has_query {
            self.client_out
                .push_str("        params: dict[str, Any] = {}\n");
            for qp in &ep.query_params {
                let snake = to_snake_case(&qp.name);
                self.client_out.push_str(&format!(
                    "        if {snake} is not None:\n            params[\"{}\"] = {snake}\n",
                    qp.name
                ));
            }
        }

        // Request headers dict. httpx wants `str` header values, so non-string
        // types are stringified; optional headers are only set when present. The
        // wire name is the exact HTTP header string (never recomputed here).
        if has_headers {
            self.client_out
                .push_str("        headers: dict[str, str] = {}\n");
            for hp in &ep.headers {
                let snake = to_snake_case(&hp.name);
                // Only an `Option<T>` header can actually be `None` at runtime, so
                // only those are guarded. A header with a literal default is a
                // non-None value (it defaults to that literal) and is sent
                // unconditionally — guarding it would be an always-true check.
                let is_nullable = matches!(&hp.ty, Type::Generic(name, _) if name == "Option");
                let value = match &unwrap_option(&hp.ty) {
                    // `str` headers pass through untouched.
                    Type::String => snake.clone(),
                    // `bool` must serialize as lowercase `true`/`false` to match
                    // every other path (Go `strconv.FormatBool`, TS `String(bool)`,
                    // and this generator's own response-header set/read which use
                    // lowercase). Python's `str(True)` would emit `"True"`, which
                    // the TS server's `=== "true"` coercion rejects.
                    Type::Bool => format!("(\"true\" if {snake} else \"false\")"),
                    _ => format!("str({snake})"),
                };
                if is_nullable {
                    // Only send the header when the caller provided a value.
                    self.client_out.push_str(&format!(
                        "        if {snake} is not None:\n            headers[\"{}\"] = {value}\n",
                        hp.wire_name
                    ));
                } else {
                    self.client_out.push_str(&format!(
                        "        headers[\"{}\"] = {value}\n",
                        hp.wire_name
                    ));
                }
            }
        }

        // HTTP call
        let mut call_args = vec![format!("f\"{{self.base_url}}{url}\"")];
        if ep.body.is_some() {
            call_args.push("json=body.model_dump()".to_string());
        }
        if has_query {
            call_args.push("params=params".to_string());
        }
        if has_headers {
            call_args.push("headers=headers".to_string());
        }
        let call = format_call(
            "        ",
            &format!("response = await self.client.{method}"),
            &call_args,
            "",
        );
        self.client_out.push_str(&call);
        self.client_out
            .push_str("        response.raise_for_status()\n");

        // Return
        if response_type == "None" {
            return;
        }

        // Parse the body into the bare response type (list or single model).
        let is_list = matches!(&ep.response, Some(Type::Generic(name, _)) if name == "List");
        let body_expr = if is_list {
            let inner = match &ep.response {
                Some(Type::Generic(_, args)) if !args.is_empty() => type_to_python(&args[0]),
                _ => "dict".to_string(),
            };
            format!("[{inner}(**item) for item in response.json()]")
        } else {
            format!("{body_type}(**response.json())")
        };

        if ep.response_headers.is_empty() {
            self.client_out
                .push_str(&format!("        return {body_expr}\n"));
            return;
        }

        // Typed envelope: read each response header off the httpx response and
        // coerce to the declared type. Absent optional headers stay `None`;
        // required headers are coerced directly (the raw `.get` is `str | None`,
        // so the `<wire>` local carries that union and the coercion narrows it).
        let mut result_args = vec![format!("body={body_expr}")];
        for hp in &ep.response_headers {
            let snake = to_snake_case(&hp.name);
            // Response-header optionality is `Option<T>` ONLY (a `= default` is
            // meaningless for a response header), matching the envelope field.
            let is_optional = matches!(&hp.ty, Type::Generic(name, _) if name == "Option");
            let inner_ty = unwrap_option(&hp.ty);
            self.client_out.push_str(&format!(
                "        {snake}_raw = response.headers.get(\"{}\")\n",
                hp.wire_name
            ));
            // `str` headers pass through untouched; other scalar types are parsed
            // from the wire string. `int`/`float`/`bool` get a converter.
            self.client_out
                .push_str(&header_read_coercion(&inner_ty, &snake, is_optional));
            result_args.push(format!("{snake}={snake}"));
        }
        let ret = format_call(
            "        ",
            &format!("return {response_type}"),
            &result_args,
            "",
        );
        self.client_out.push_str(&ret);
    }

    // ── handlers.py emission ────────────────────────────────────────

    /// Emits imports for the handlers file.
    fn emit_handler_imports(&mut self) {
        self.handlers_out.push_str("from typing import Protocol\n");

        let mut imports = BTreeSet::new();
        for ep in &self.check_result.endpoints {
            if ep.body.is_some() {
                imports.insert(format!("{}Body", capitalize(&ep.name)));
            }
            if let Some(ref resp) = ep.response {
                collect_python_imports(resp, &mut imports);
            }
            // Endpoints with response headers return the typed envelope.
            if !ep.response_headers.is_empty() {
                imports.insert(format!("{}Result", capitalize(&ep.name)));
            }
        }
        if !imports.is_empty() {
            let joined: Vec<_> = imports.into_iter().collect();
            self.handlers_out.push('\n');
            self.handlers_out
                .push_str(&format_from_import(".models", &joined));
        }
    }

    /// Emits a single handler method signature.
    fn emit_handler_method(&mut self, ep: &EndpointInfo) {
        let fn_name = to_snake_case(&ep.name);
        let response_type = if ep.response_headers.is_empty() {
            ep.response
                .as_ref()
                .map(type_to_python)
                .unwrap_or_else(|| "None".to_string())
        } else {
            format!("{}Result", capitalize(&ep.name))
        };

        let mut params = vec!["self".to_string()];
        for pp in &ep.path_params {
            params.push(format!("{}: str", to_snake_case(pp)));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(format!("body: {body_type}"));
        }
        if !ep.query_params.is_empty() || !ep.headers.is_empty() {
            params.push("*".to_string());
            for qp in &ep.query_params {
                let py_type = type_to_python(&qp.ty);
                let is_option = matches!(&qp.ty, Type::Generic(name, _) if name == "Option");
                if is_option {
                    params.push(format!("{}: {} = None", to_snake_case(&qp.name), py_type));
                } else {
                    params.push(format!("{}: {}", to_snake_case(&qp.name), py_type));
                }
            }
            for hp in &ep.headers {
                let py_type = type_to_python(&hp.ty);
                // Mirrors query params: the handler only sees `= None` for an
                // `Option<T>` header. A header with a literal default is resolved
                // by the server (`Header(<default>, ...)`) before the handler is
                // called, so it arrives as a plain required value here.
                let is_option = matches!(&hp.ty, Type::Generic(name, _) if name == "Option");
                if is_option {
                    params.push(format!("{}: {} = None", to_snake_case(&hp.name), py_type));
                } else {
                    params.push(format!("{}: {}", to_snake_case(&hp.name), py_type));
                }
            }
        }

        ensure_blank_lines(&mut self.handlers_out, 1);
        if let Some(ref doc) = ep.doc_comment {
            self.handlers_out
                .push_str(&render_hash_comment("    ", doc));
        }
        let sig = format_def_signature(
            "    ",
            "async def",
            &fn_name,
            &params,
            &format!(" -> {response_type}: ..."),
        );
        self.handlers_out.push_str(&sig);
    }

    // ── server.py emission ──────────────────────────────────────────

    /// Emits imports for the server file.
    fn emit_server_imports(&mut self) {
        // Build the `fastapi` import list from what the routes actually use, so
        // ruff F401 never fires on an unused name. `APIRouter` is always needed;
        // `HTTPException` only when some endpoint maps errors; `Query` only when
        // some query param needs an `alias=` (its wire name differs from the
        // snake_case Python parameter — see `emit_server_route`).
        let needs_http_exception = self
            .check_result
            .endpoints
            .iter()
            .any(|ep| !ep.errors.is_empty());
        let needs_query = self.check_result.endpoints.iter().any(|ep| {
            ep.query_params
                .iter()
                .any(|qp| to_snake_case(&qp.name) != qp.name)
        });
        // Request headers always bind via `Header(alias="<wire_name>")` — the
        // exact HTTP header name (e.g. `Idempotency-Key`) is never a valid Python
        // identifier — so any request header pulls in `Header`. Response headers
        // are set on a `Response` param, so any of those pulls in `Response`.
        let needs_header = self
            .check_result
            .endpoints
            .iter()
            .any(|ep| !ep.headers.is_empty());
        let needs_response = self
            .check_result
            .endpoints
            .iter()
            .any(|ep| !ep.response_headers.is_empty());
        let mut names = vec!["APIRouter"];
        if needs_header {
            names.push("Header");
        }
        if needs_http_exception {
            names.push("HTTPException");
        }
        if needs_query {
            names.push("Query");
        }
        if needs_response {
            names.push("Response");
        }
        self.server_out
            .push_str(&format!("from fastapi import {}\n\n", names.join(", ")));

        let mut model_imports = BTreeSet::new();
        for ep in &self.check_result.endpoints {
            if ep.body.is_some() {
                model_imports.insert(format!("{}Body", capitalize(&ep.name)));
            }
            if let Some(ref resp) = ep.response {
                collect_python_imports(resp, &mut model_imports);
            }
            // The route returns `result.body`, so the envelope type itself is not
            // imported; only the body's component types (above) are referenced.
        }
        self.server_out.push_str("from .handlers import Handlers\n");
        if !model_imports.is_empty() {
            let joined: Vec<_> = model_imports.into_iter().collect();
            self.server_out
                .push_str(&format_from_import(".models", &joined));
        }
    }

    /// Emits a single FastAPI route for an endpoint.
    fn emit_server_route(&mut self, ep: &EndpointInfo) {
        let method = ep.method.as_lower_str();
        let fn_name = to_snake_case(&ep.name);
        let response_type = ep
            .response
            .as_ref()
            .map(type_to_python)
            .unwrap_or_else(|| "None".to_string());

        // FastAPI path: {id} stays as {id} (FastAPI uses same syntax)
        let status = if ep.response.is_none() {
            ", status_code=204"
        } else {
            ""
        };

        ensure_blank_lines(&mut self.server_out, 1);
        self.server_out.push_str(&format!(
            "    @router.{}(\"{}\"{})\n",
            method, ep.path, status
        ));

        // Build function params. Python requires every parameter WITHOUT a
        // default to precede those WITH one, so we collect into two ordered
        // groups and concatenate. Path params and the body never carry a
        // default; query params land in `defaulted` when they render a `= ...`
        // (optional params, and required-but-aliased params — see below).
        let mut required = Vec::new();
        let mut defaulted = Vec::new();
        for pp in &ep.path_params {
            required.push(format!("{}: str", to_snake_case(pp)));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            required.push(format!("body: {body_type}"));
        }
        for qp in &ep.query_params {
            let py_type = type_to_python(&qp.ty);
            let snake = to_snake_case(&qp.name);
            let is_optional =
                qp.has_default || matches!(&qp.ty, Type::Generic(name, _) if name == "Option");
            // FastAPI matches query keys to the Python parameter name. The
            // generated client sends the schema's original (camelCase) name, so
            // when snake_case differs we must pin the wire key with an explicit
            // `Query(default, alias="<wireName>")` — otherwise FastAPI never sees
            // the value and silently falls back to the default. Single-word
            // params (snake == wire) need no alias and stay plain.
            let needs_alias = snake != qp.name;
            if is_optional {
                let default = qp
                    .default_value
                    .as_ref()
                    .map(default_value_to_python)
                    .unwrap_or_else(|| "None".to_string());
                if needs_alias {
                    defaulted.push(format!(
                        "{snake}: {py_type} = Query({default}, alias=\"{}\")",
                        qp.name
                    ));
                } else {
                    defaulted.push(format!("{snake}: {py_type} = {default}"));
                }
            } else if needs_alias {
                // A required aliased param renders `= Query(alias=...)`, which is
                // a syntactic default, so it must sort after the non-defaulted
                // params even though FastAPI still treats it as required (a
                // `Query(...)` with no value sentinel is required regardless of
                // position).
                defaulted.push(format!("{snake}: {py_type} = Query(alias=\"{}\")", qp.name));
            } else {
                required.push(format!("{snake}: {py_type}"));
            }
        }
        // Request headers bind via FastAPI `Header(default, alias="<wire_name>")`.
        // The wire name (e.g. `Idempotency-Key`) is never a valid Python
        // identifier, so headers ALWAYS need the alias — there is no plain form.
        // `Header(...)` is a syntactic default, so every header lands in
        // `defaulted` (after the non-defaulted path/body/response params).
        for hp in &ep.headers {
            let py_type = type_to_python(&hp.ty);
            let snake = to_snake_case(&hp.name);
            let is_optional =
                hp.has_default || matches!(&hp.ty, Type::Generic(name, _) if name == "Option");
            if is_optional {
                let default = hp
                    .default_value
                    .as_ref()
                    .map(default_value_to_python)
                    .unwrap_or_else(|| "None".to_string());
                defaulted.push(format!(
                    "{snake}: {py_type} = Header({default}, alias=\"{}\")",
                    hp.wire_name
                ));
            } else {
                // Required-but-aliased: `Header(alias=...)` (no value sentinel) is
                // required regardless of position, mirroring the required `Query`
                // alias form above.
                defaulted.push(format!(
                    "{snake}: {py_type} = Header(alias=\"{}\")",
                    hp.wire_name
                ));
            }
        }
        // A `response: Response` param lets the route set response headers; it
        // has no default, so it sorts with the other required params.
        let has_response_headers = !ep.response_headers.is_empty();
        if has_response_headers {
            required.push("response: Response".to_string());
        }
        let params: Vec<String> = required.into_iter().chain(defaulted).collect();

        let sig = format_def_signature(
            "    ",
            "async def",
            &fn_name,
            &params,
            &format!(" -> {response_type}:"),
        );
        self.server_out.push_str(&sig);

        // Error handling wrapper
        let has_errors = !ep.errors.is_empty();
        let indent = if has_errors {
            "            "
        } else {
            "        "
        };

        if has_errors {
            self.server_out.push_str("        try:\n");
        }

        // Call handler
        let mut handler_args = Vec::new();
        for pp in &ep.path_params {
            let snake = to_snake_case(pp);
            handler_args.push(format!("{snake}={snake}"));
        }
        if ep.body.is_some() {
            handler_args.push("body=body".to_string());
        }
        for qp in &ep.query_params {
            let snake = to_snake_case(&qp.name);
            handler_args.push(format!("{snake}={snake}"));
        }
        for hp in &ep.headers {
            let snake = to_snake_case(&hp.name);
            handler_args.push(format!("{snake}={snake}"));
        }

        if has_response_headers {
            // The handler returns the typed envelope; capture it, copy each
            // response header onto the FastAPI `Response` (string-coerced, guarded
            // for optional), then return the bare body for serialization.
            let call = format_call(
                indent,
                &format!("result = await handlers.{fn_name}"),
                &handler_args,
                "",
            );
            self.server_out.push_str(&call);
            for hp in &ep.response_headers {
                let snake = to_snake_case(&hp.name);
                // Response-header optionality is `Option<T>` ONLY (a `= default`
                // is meaningless for a response header), matching the envelope.
                let is_optional = matches!(&hp.ty, Type::Generic(name, _) if name == "Option");
                let inner = unwrap_option(&hp.ty);
                // Stringify for the wire. `str` passes through; `bool` is emitted
                // as lowercase `true`/`false` so it round-trips with the client's
                // `== "true"` read (Python's `str(True)` would yield "True").
                let value = match &inner {
                    Type::String => format!("result.{snake}"),
                    Type::Bool => format!("\"true\" if result.{snake} else \"false\""),
                    _ => format!("str(result.{snake})"),
                };
                if is_optional {
                    self.server_out.push_str(&format!(
                        "{indent}if result.{snake} is not None:\n{indent}    response.headers[\"{}\"] = {value}\n",
                        hp.wire_name
                    ));
                } else {
                    self.server_out.push_str(&format!(
                        "{indent}response.headers[\"{}\"] = {value}\n",
                        hp.wire_name
                    ));
                }
            }
            self.server_out
                .push_str(&format!("{indent}return result.body\n"));
        } else {
            let prefix = if ep.response.is_some() {
                format!("return await handlers.{fn_name}")
            } else {
                format!("await handlers.{fn_name}")
            };
            let call = format_call(indent, &prefix, &handler_args, "");
            self.server_out.push_str(&call);
        }

        // Error mapping
        if has_errors {
            self.server_out.push_str("        except Exception as e:\n");
            for (name, code) in &ep.errors {
                self.server_out
                    .push_str(&format!("            if str(e) == \"{name}\":\n"));
                // `raise HTTPException(...) from e` wraps like black once a long
                // error name pushes it past 88 columns.
                let raise = format_call(
                    "                ",
                    "raise HTTPException",
                    &[format!("status_code={code}"), format!("detail=\"{name}\"")],
                    " from e",
                );
                self.server_out.push_str(&raise);
            }
            self.server_out.push_str("            raise\n");
        }
    }
}

// ── Helper functions ─────────────────────────────────────────────────

/// Strips a single `Option<T>` wrapper, returning the inner type; non-option
/// types are returned unchanged. Used to find the scalar type carried by a
/// response header so the client can coerce the wire string to it.
fn unwrap_option(ty: &Type) -> Type {
    match ty {
        Type::Generic(name, args) if name == "Option" && args.len() == 1 => args[0].clone(),
        other => other.clone(),
    }
}

/// Emits the client-side coercion of a single response header from its raw
/// `str | None` wire read (`<snake>_raw`) into the typed local `<snake>` the
/// envelope expects.
///
/// `inner_ty` is the header type with any `Option<…>` stripped. Optional headers
/// stay `None` when absent; required headers coerce directly, fabricating the
/// type's zero value only to satisfy the type checker (a required response header
/// is contractually always present on the wire).
fn header_read_coercion(inner_ty: &Type, snake: &str, is_optional: bool) -> String {
    let raw = format!("{snake}_raw");
    let rhs = if is_optional {
        // None/empty reads as `None`; a present value is parsed to the inner
        // scalar via a truthiness ternary (`is not None` would be longer).
        match inner_ty {
            Type::Int => format!("int({raw}) if {raw} else None"),
            Type::Float => format!("float({raw}) if {raw} else None"),
            Type::Bool => format!("({raw} == \"true\") if {raw} else None"),
            // `str` (and any unmodeled scalar) passes through untouched.
            _ => raw.clone(),
        }
    } else {
        // A required response header is contractually present; the `or <zero>`
        // fallback only narrows the `str | None` read to a non-None value for the
        // type checker.
        match inner_ty {
            Type::Int => format!("int({raw} or 0)"),
            Type::Float => format!("float({raw} or 0)"),
            Type::Bool => format!("{raw} == \"true\""),
            _ => format!("{raw} or \"\""),
        }
    };
    emit_py_assignment("        ", snake, &rhs)
}

/// Renders a single `lhs = rhs` assignment, wrapping the RHS in parentheses one
/// indent level deeper when the one-line form would exceed [`LINE_LENGTH`] — the
/// layout black produces for an over-long assignment. Keeps generated coercions
/// (whose `lhs`/`rhs` both embed the header's snake_case name, so a long name can
/// push past 88 columns) formatter-clean. Returns the line(s) with a trailing
/// newline.
fn emit_py_assignment(indent: &str, lhs: &str, rhs: &str) -> String {
    let one_line = format!("{indent}{lhs} = {rhs}");
    if one_line.len() <= LINE_LENGTH {
        return format!("{one_line}\n");
    }
    format!("{indent}{lhs} = (\n{indent}    {rhs}\n{indent})\n")
}

/// Renders `text` as one or more Python `#` comments, each prefixed with
/// `indent`. A multi-line doc comment (the lexer joins its lines with `\n`) gets
/// EVERY line prefixed, so continuation lines stay commented instead of leaking
/// into the file as code. Trailing whitespace is trimmed per line, so an empty
/// line renders as a bare `#` (no trailing space) — keeping `# ` block-comment
/// linters (ruff E265/W291) happy — matching the Go `render_line_comment` helper.
fn render_hash_comment(indent: &str, text: &str) -> String {
    let mut out = String::new();
    for line in text.split('\n') {
        out.push_str(format!("{indent}# {line}").trim_end());
        out.push('\n');
    }
    out
}

/// Converts a Phoenix `Type` to a Python type annotation string.
fn type_to_python(ty: &Type) -> String {
    match ty {
        Type::Int => "int".to_string(),
        Type::Float => "float".to_string(),
        Type::String => "str".to_string(),
        Type::Bool => "bool".to_string(),
        Type::Void => "None".to_string(),
        Type::Named(name) => name.clone(),
        Type::Generic(name, args) if name == "List" && args.len() == 1 => {
            format!("list[{}]", type_to_python(&args[0]))
        }
        Type::Generic(name, args) if name == "Map" && args.len() == 2 => {
            format!(
                "dict[{}, {}]",
                type_to_python(&args[0]),
                type_to_python(&args[1])
            )
        }
        Type::Generic(name, args) if name == "Option" && args.len() == 1 => {
            format!("{} | None", type_to_python(&args[0]))
        }
        Type::Generic(name, args) => {
            let py_args: Vec<String> = args.iter().map(type_to_python).collect();
            format!("{}[{}]", name, py_args.join(", "))
        }
        // Trait objects erase to the trait name (dispatched at runtime via
        // duck typing in Python); sharper Protocol-based mappings can replace
        // this once specific traits need per-trait shims.
        Type::Dyn(name) => name.clone(),
        _ => "object".to_string(),
    }
}

/// Converts a camelCase identifier to snake_case.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_lowercase().next().unwrap_or(c));
    }
    result
}

/// Converts a PascalCase name to SCREAMING_SNAKE_CASE for Python enum values.
fn to_screaming_snake(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_uppercase().next().unwrap_or(c));
    }
    result
}

use crate::capitalize;

/// Builds a Python f-string URL expression from a Phoenix path pattern.
///
/// `/api/users/{id}` → `/api/users/{id}` (Python f-strings use same `{}`).
/// Path param names are converted to snake_case.
fn build_python_url(path: &str) -> String {
    let mut result = String::new();
    let mut in_brace = false;
    let mut param_name = String::new();

    for c in path.chars() {
        if c == '{' {
            in_brace = true;
            param_name.clear();
            result.push('{');
        } else if c == '}' {
            in_brace = false;
            result.push_str(&to_snake_case(&param_name));
            result.push('}');
        } else if in_brace {
            param_name.push(c);
        } else {
            result.push(c);
        }
    }
    result
}

/// Formats an `f64` as a Python float literal, guaranteeing a decimal point so
/// the value reads as a `float` (e.g. `0` → `0.0`) rather than an `int`. Rust's
/// `f64` `Display` never uses exponent notation, so only a missing `.` needs
/// fixing up.
fn format_python_float(v: f64) -> String {
    let s = v.to_string();
    if s.contains('.') { s } else { format!("{s}.0") }
}

/// Converts a `DefaultValue` to a Python literal.
fn default_value_to_python(val: &DefaultValue) -> String {
    match val {
        DefaultValue::Int(v) => v.to_string(),
        DefaultValue::Float(v) => format_python_float(*v),
        DefaultValue::String(v) => format!("\"{}\"", v),
        DefaultValue::Bool(true) => "True".to_string(),
        DefaultValue::Bool(false) => "False".to_string(),
    }
}

/// Recursively collects user-defined type names that need to be imported.
fn collect_python_imports(ty: &Type, imports: &mut BTreeSet<String>) {
    match ty {
        Type::Named(name) => {
            imports.insert(name.clone());
        }
        Type::Generic(name, args) => {
            if !matches!(name.as_str(), "List" | "Option" | "Map" | "Result") {
                imports.insert(name.clone());
            }
            for arg in args {
                collect_python_imports(arg, imports);
            }
        }
        Type::Dyn(name) => {
            imports.insert(name.clone());
        }
        _ => {}
    }
}

/// Extracts Pydantic `Field()` kwargs from a constraint expression.
///
/// Returns `Some("ge=0, le=150")` for numeric bounds, `Some("min_length=1")`
/// for string length, or `None` if no extractable constraints.
fn constraint_to_field(constraint: &Option<phoenix_parser::ast::Expr>) -> Option<Vec<String>> {
    let constraint = constraint.as_ref()?;
    let mut kwargs = Vec::new();
    extract_pydantic_kwargs(constraint, &mut kwargs);
    if kwargs.is_empty() {
        None
    } else {
        Some(kwargs)
    }
}

/// Recursively extracts Pydantic Field kwargs from constraint expressions.
fn extract_pydantic_kwargs(expr: &phoenix_parser::ast::Expr, kwargs: &mut Vec<String>) {
    use phoenix_parser::ast::{BinaryOp, Expr, LiteralKind};

    match expr {
        // expr1 and expr2 → extract from both
        Expr::Binary(bin) if bin.op == BinaryOp::And => {
            extract_pydantic_kwargs(&bin.left, kwargs);
            extract_pydantic_kwargs(&bin.right, kwargs);
        }
        // self >= N, self <= N, etc.
        Expr::Binary(bin) if is_self_ident(&bin.left) => {
            if let Expr::Literal(lit) = &bin.right {
                let val = match &lit.kind {
                    LiteralKind::Int(v) => v.to_string(),
                    LiteralKind::Float(v) => format_python_float(*v),
                    _ => return,
                };
                match bin.op {
                    BinaryOp::GtEq => kwargs.push(format!("ge={val}")),
                    BinaryOp::LtEq => kwargs.push(format!("le={val}")),
                    BinaryOp::Gt => kwargs.push(format!("gt={val}")),
                    BinaryOp::Lt => kwargs.push(format!("lt={val}")),
                    _ => {}
                }
            }
        }
        // self.length >= N, etc.
        Expr::Binary(bin) if is_self_length(&bin.left) => {
            if let Expr::Literal(lit) = &bin.right
                && let LiteralKind::Int(n) = &lit.kind
            {
                match bin.op {
                    BinaryOp::GtEq => kwargs.push(format!("min_length={n}")),
                    BinaryOp::LtEq => kwargs.push(format!("max_length={n}")),
                    BinaryOp::Gt => kwargs.push(format!("min_length={}", n + 1)),
                    BinaryOp::Lt => kwargs.push(format!("max_length={}", n - 1)),
                    _ => {}
                }
            }
        }
        _ => {}
    }
}

/// Returns true if the expression is the `self` identifier.
fn is_self_ident(expr: &phoenix_parser::ast::Expr) -> bool {
    matches!(expr, phoenix_parser::ast::Expr::Ident(i) if i.name == "self")
}

/// Returns true if the expression is `self.length`.
fn is_self_length(expr: &phoenix_parser::ast::Expr) -> bool {
    matches!(
        expr,
        phoenix_parser::ast::Expr::FieldAccess(fa) if fa.field == "length" && is_self_ident(&fa.object)
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use phoenix_common::span::SourceId;
    use phoenix_lexer::lexer::tokenize;
    use phoenix_parser::parser;
    use phoenix_sema::checker;

    /// An interior empty doc line renders as a bare `#` (no trailing space) so
    /// ruff E265 stays happy. Guards the empty-line branch of
    /// `render_hash_comment`, which the doc-comment integration tests don't hit.
    #[test]
    fn render_hash_comment_blanks_out_empty_lines() {
        assert_eq!(
            render_hash_comment("    ", "first\n\nthird"),
            "    # first\n    #\n    # third\n"
        );
    }

    fn generate_from_source(source: &str) -> PythonFiles {
        let tokens = tokenize(source, SourceId(0));
        let (program, parse_errors) = parser::parse(&tokens);
        assert!(parse_errors.is_empty(), "parse errors: {parse_errors:?}");
        let result = checker::check(&program);
        assert!(
            result.diagnostics.is_empty(),
            "check errors: {:?}",
            result.diagnostics
        );
        generate_python(&program, &result)
    }

    #[test]
    fn struct_to_model() {
        let files = generate_from_source(
            r#"
/** A registered user */
struct User {
    Int id
    String name
    Option<String> bio
}
"#,
        );
        insta::assert_snapshot!("py_struct_to_model", files.models);
    }

    #[test]
    fn simple_enum() {
        let files = generate_from_source("enum Role { Admin  Editor  Viewer }");
        insta::assert_snapshot!("py_simple_enum", files.models);
    }

    #[test]
    fn model_with_constraints() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String name where self.length > 0 && self.length <= 100
    Int age where self >= 0 && self <= 150
}
"#,
        );
        insta::assert_snapshot!("py_model_constraints", files.models);
    }

    #[test]
    fn get_with_path_param() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint getUser: GET "/api/users/{id}" {
    response User
}
"#,
        );
        insta::assert_snapshot!("py_get_client", files.client);
        insta::assert_snapshot!("py_get_handler", files.handlers);
        insta::assert_snapshot!("py_get_server", files.server);
    }

    #[test]
    fn post_with_body() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
    error { Conflict(409) }
}
"#,
        );
        insta::assert_snapshot!("py_post_client", files.client);
        insta::assert_snapshot!("py_post_server", files.server);
        insta::assert_snapshot!("py_post_models", files.models);
    }

    #[test]
    fn query_params_with_defaults() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint listUsers: GET "/api/users" {
    query {
        Int page = 1
        Int limit = 20
        Option<String> search
    }
    response List<User>
}
"#,
        );
        insta::assert_snapshot!("py_query_client", files.client);
        insta::assert_snapshot!("py_query_handler", files.handlers);
        insta::assert_snapshot!("py_query_server", files.server);
    }

    /// A required, camelCase query param renders `= Query(alias=...)` — a
    /// syntactic default — so it must sort AFTER a required plain param, or the
    /// generated server is invalid Python ("non-default argument follows default
    /// argument"). Guards the parameter partitioning in `emit_server_route`.
    #[test]
    fn required_aliased_query_param_sorts_after_plain() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint searchUsers: GET "/api/users" {
    query {
        Int maxResults
        Int page
    }
    response List<User>
}
"#,
        );
        let plain = files.server.find("page: int").expect("plain param present");
        let aliased = files
            .server
            .find("max_results: int = Query(alias=\"maxResults\")")
            .expect("aliased param present");
        assert!(
            plain < aliased,
            "required plain param must precede the aliased (defaulted) one:\n{}",
            files.server
        );
    }

    #[test]
    fn void_response() {
        let files = generate_from_source(
            r#"
endpoint deleteUser: DELETE "/api/users/{id}" {
    error { NotFound(404) }
}
"#,
        );
        insta::assert_snapshot!("py_void_client", files.client);
        insta::assert_snapshot!("py_void_server", files.server);
    }

    /// A request header with an auto-derived wire name (`idempotencyKey →
    /// Idempotency-Key`) must: appear as a snake_case keyword-only client arg,
    /// be sent on a `headers` dict keyed by the EXACT wire name, bind on the
    /// server via `Header(alias="<wire_name>")`, and thread into the handler.
    #[test]
    fn request_header_auto_wire_name() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint createUser: POST "/api/users" {
    headers { String idempotencyKey }
    response User
}
"#,
        );
        insta::assert_snapshot!("py_req_header_client", files.client);
        insta::assert_snapshot!("py_req_header_handler", files.handlers);
        insta::assert_snapshot!("py_req_header_server", files.server);
        // Client sends the exact wire name; server aliases to it.
        assert!(
            files
                .client
                .contains("headers[\"Idempotency-Key\"] = idempotency_key"),
            "client must key the header dict on the wire name:\n{}",
            files.client
        );
        assert!(
            files.server.contains("Header(alias=\"Idempotency-Key\")"),
            "server must alias the Header param to the wire name:\n{}",
            files.server
        );
    }

    /// An explicit `as "Exact-Wire-Name"` override pins the wire name verbatim,
    /// overriding the auto Title-Kebab transform on both client and server.
    #[test]
    fn request_header_as_override() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint createUser: POST "/api/users" {
    headers { String token as "X-Auth" }
    response User
}
"#,
        );
        assert!(
            files.client.contains("headers[\"X-Auth\"] = token"),
            "client must use the override wire name:\n{}",
            files.client
        );
        assert!(
            files
                .server
                .contains("token: str = Header(alias=\"X-Auth\")"),
            "server must alias to the override wire name:\n{}",
            files.server
        );
    }

    /// An optional request header renders `T | None = Header(None, alias=...)`
    /// on the server, a defaulted keyword arg on the client, and is only added
    /// to the wire dict when present.
    #[test]
    fn optional_request_header() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint createUser: POST "/api/users" {
    headers { Option<String> traceId }
    response User
}
"#,
        );
        assert!(
            files
                .server
                .contains("trace_id: str | None = Header(None, alias=\"Trace-Id\")"),
            "optional header must render Header(None, alias=...):\n{}",
            files.server
        );
        assert!(
            files.client.contains("trace_id: str | None = None"),
            "optional header must be a defaulted client kwarg:\n{}",
            files.client
        );
        assert!(
            files
                .client
                .contains("if trace_id is not None:\n            headers[\"Trace-Id\"] = trace_id"),
            "optional header must be guarded on the wire:\n{}",
            files.client
        );
    }

    /// A `Bool` request header must be serialized as lowercase `true`/`false` on
    /// the wire — NOT Python's `str(True)` → `"True"`. This matches every other
    /// path (Go `strconv.FormatBool`, TS `String(bool)`, and this generator's own
    /// response-header set/read which use lowercase + `== "true"`), so a bool
    /// header round-trips across languages. Regression guard for the capitalized
    /// `str(...)` bug.
    #[test]
    fn bool_request_header_serializes_lowercase() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint createUser: POST "/api/users" {
    headers { Bool debug }
    response User
}
"#,
        );
        assert!(
            files
                .client
                .contains("headers[\"Debug\"] = (\"true\" if debug else \"false\")"),
            "bool header must serialize lowercase, not str(bool):\n{}",
            files.client
        );
        assert!(
            !files.client.contains("str(debug)"),
            "bool header must not use str() (yields capitalized True/False):\n{}",
            files.client
        );
    }

    /// A request header with a literal default binds the default into both the
    /// server `Header(<default>, alias=...)` and the client kwarg
    /// (`max_stale: int = 60`). Per the documented "defaulted request headers"
    /// gap, the client sends it unconditionally (no `Option<T>` guard).
    #[test]
    fn defaulted_request_header_binds_default() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint createUser: POST "/api/users" {
    headers { Int maxStale = 60 }
    response User
}
"#,
        );
        assert!(
            files
                .server
                .contains("max_stale: int = Header(60, alias=\"Max-Stale\")"),
            "server must bind the default into Header(...):\n{}",
            files.server
        );
        assert!(
            files.client.contains("max_stale: int = 60"),
            "client must default the kwarg:\n{}",
            files.client
        );
        assert!(
            files
                .client
                .contains("headers[\"Max-Stale\"] = str(max_stale)"),
            "client must send the defaulted header unconditionally:\n{}",
            files.client
        );
    }

    /// An endpoint with response headers returns a typed `<Endpoint>Result`
    /// envelope: a pydantic model bundling `body` + each header (snake_case),
    /// the handler returns it, the server sets headers on the `Response` and
    /// returns `result.body`, and the client reads headers off the response.
    #[test]
    fn response_header_envelope() {
        let files = generate_from_source(
            r#"
struct Post { Int id  String title }
endpoint getPost: GET "/api/posts/{id}" {
    response Post headers { Int ratelimitRemaining as "X-RateLimit-Remaining" }
}
"#,
        );
        insta::assert_snapshot!("py_resp_header_models", files.models);
        insta::assert_snapshot!("py_resp_header_client", files.client);
        insta::assert_snapshot!("py_resp_header_handler", files.handlers);
        insta::assert_snapshot!("py_resp_header_server", files.server);
        // Envelope shape.
        assert!(
            files.models.contains(
                "class GetPostResult(BaseModel):\n    body: Post\n    ratelimit_remaining: int\n"
            ),
            "envelope model must bundle body + typed header:\n{}",
            files.models
        );
        // Handler returns the envelope.
        assert!(
            files.handlers.contains("-> GetPostResult: ..."),
            "handler must return the envelope:\n{}",
            files.handlers
        );
        // Server sets the header off the result and returns the body.
        assert!(
            files.server.contains(
                "response.headers[\"X-RateLimit-Remaining\"] = str(result.ratelimit_remaining)"
            ),
            "server must set the response header from the result:\n{}",
            files.server
        );
        assert!(
            files.server.contains("return result.body\n"),
            "server must return the bare body:\n{}",
            files.server
        );
        // Client reads the header into the envelope it returns.
        assert!(
            files.client.contains(
                "ratelimit_remaining_raw = response.headers.get(\"X-RateLimit-Remaining\")"
            ),
            "client must read the response header off the wire:\n{}",
            files.client
        );
        assert!(
            files.client.contains("return GetPostResult("),
            "client must return the typed envelope:\n{}",
            files.client
        );
    }

    /// A multi-line doc comment must have EVERY line prefixed with `#`, not just
    /// the first — otherwise continuation lines leak into the file as code.
    /// Regression guard for `render_hash_comment`.
    #[test]
    fn multiline_doc_comment_is_fully_commented() {
        let files = generate_from_source(
            r#"
struct Widget { Int id }
/**
 * Fetch a widget by id
 * with extra detail on the second line
 */
endpoint getWidget: GET "/api/widgets/{id}" {
    response Widget
}
"#,
        );
        assert!(
            files.client.contains(
                "    # Fetch a widget by id\n    # with extra detail on the second line\n"
            ),
            "every doc line must be commented:\n{}",
            files.client
        );
        // The continuation line must never appear UNcommented (leaked as code).
        assert!(
            !files.client.contains("\n    with extra detail"),
            "continuation doc line leaked as code:\n{}",
            files.client
        );
    }

    #[test]
    fn snake_case_conversion() {
        assert_eq!(to_snake_case("createUser"), "create_user");
        assert_eq!(to_snake_case("getHTTPResponse"), "get_h_t_t_p_response");
        assert_eq!(to_snake_case("id"), "id");
        assert_eq!(to_snake_case("userId"), "user_id");
        assert_eq!(to_snake_case("listUsers"), "list_users");
    }

    #[test]
    fn screaming_snake_conversion() {
        assert_eq!(to_screaming_snake("Admin"), "ADMIN");
        assert_eq!(to_screaming_snake("NotFound"), "NOT_FOUND");
        assert_eq!(to_screaming_snake("ValidationError"), "VALIDATION_ERROR");
    }

    #[test]
    fn multiple_endpoints() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint listUsers: GET "/api/users" {
    response List<User>
}
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
endpoint getUser: GET "/api/users/{id}" {
    response User
}
endpoint deleteUser: DELETE "/api/users/{id}" {
}
"#,
        );
        insta::assert_snapshot!("py_multi_models", files.models);
        insta::assert_snapshot!("py_multi_client", files.client);
        insta::assert_snapshot!("py_multi_handlers", files.handlers);
        insta::assert_snapshot!("py_multi_server", files.server);
    }

    // ── Gap-filling tests ───────────────────────────────────────────

    /// `pick` modifier in derived body.
    #[test]
    fn body_pick_only() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email  Int age }
endpoint updateEmail: PATCH "/api/users/{id}" {
    body User pick { email }
    response User
}
"#,
        );
        insta::assert_snapshot!("py_pick_models", files.models);
        insta::assert_snapshot!("py_pick_client", files.client);
    }

    /// `partial` modifier makes all fields optional.
    #[test]
    fn body_partial() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name where self.length > 0  Int age where self >= 0 }
endpoint updateUser: PATCH "/api/users/{id}" {
    body User omit { id } partial
    response User
}
"#,
        );
        insta::assert_snapshot!("py_partial_models", files.models);
    }

    /// A `partial` body field whose type already contains an inner `| None`
    /// (here `List<Option<String>>` → `list[str | None]`) must still gain the
    /// *outer* `| None` from `partial` — the container is not itself optional.
    /// Guards against the `already_optional` heuristic matching the inner union.
    #[test]
    fn body_partial_inner_optional_container() {
        let files = generate_from_source(
            r#"
struct Post { Int id  List<Option<String>> tags }
endpoint updatePost: PATCH "/api/posts/{id}" {
    body Post omit { id } partial
    response Post
}
"#,
        );
        assert!(
            files
                .models
                .contains("tags: list[str | None] | None = None"),
            "expected outer `| None` on a partial List<Option<String>> field, got:\n{}",
            files.models
        );
    }

    /// Multiple path params.
    #[test]
    fn multiple_path_params() {
        let files = generate_from_source(
            r#"
struct Comment { Int id  String text }
endpoint getComment: GET "/api/users/{userId}/posts/{postId}" {
    response Comment
}
"#,
        );
        insta::assert_snapshot!("py_multi_path_client", files.client);
        insta::assert_snapshot!("py_multi_path_handler", files.handlers);
    }

    /// Float constraints in Pydantic Field.
    #[test]
    fn float_constraints() {
        let files = generate_from_source(
            r#"
struct Measurement { Float value where self >= 0.0 && self <= 100.5 }
"#,
        );
        insta::assert_snapshot!("py_float_constraints", files.models);
    }

    /// Bool and String query param defaults.
    #[test]
    fn bool_string_defaults() {
        let files = generate_from_source(
            r#"
struct Item { Int id  String name }
endpoint listItems: GET "/api/items" {
    query {
        String sortBy = "name"
        Bool ascending = true
        Int limit = 50
    }
    response List<Item>
}
"#,
        );
        insta::assert_snapshot!("py_bool_string_defaults_client", files.client);
        insta::assert_snapshot!("py_bool_string_defaults_server", files.server);
    }

    /// Map<K,V> type in struct.
    #[test]
    fn map_type() {
        let files = generate_from_source(
            r#"
struct Config { Map<String, String> settings  Int version }
"#,
        );
        insta::assert_snapshot!("py_map_type", files.models);
    }

    /// Enum as response type.
    #[test]
    fn enum_response() {
        let files = generate_from_source(
            r#"
enum Status { Active  Inactive  Banned }
endpoint getStatus: GET "/api/status" {
    response Status
}
"#,
        );
        insta::assert_snapshot!("py_enum_response_client", files.client);
    }

    /// PUT method.
    #[test]
    fn put_method() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint replaceUser: PUT "/api/users/{id}" {
    body User
    response User
}
"#,
        );
        insta::assert_snapshot!("py_put_server", files.server);
    }

    /// default_value_to_python covers all variants.
    #[test]
    fn default_value_conversions() {
        assert_eq!(default_value_to_python(&DefaultValue::Int(42)), "42");
        assert_eq!(default_value_to_python(&DefaultValue::Float(1.5)), "1.5");
        assert_eq!(
            default_value_to_python(&DefaultValue::String("hello".into())),
            "\"hello\""
        );
        assert_eq!(default_value_to_python(&DefaultValue::Bool(true)), "True");
        assert_eq!(default_value_to_python(&DefaultValue::Bool(false)), "False");
    }

    /// `dyn Trait` erases to the trait name — callers are expected to have
    /// a matching Protocol / ABC defined in hand-written Python.
    #[test]
    fn dyn_type_erases_to_trait_name() {
        assert_eq!(
            type_to_python(&Type::Dyn("Drawable".to_string())),
            "Drawable"
        );
    }

    /// `dyn Trait` gets recorded as an import so the generator wires up the
    /// user-defined trait symbol the same way it does named structs/enums.
    #[test]
    fn dyn_type_records_import() {
        let mut imports = BTreeSet::new();
        collect_python_imports(&Type::Dyn("Drawable".to_string()), &mut imports);
        assert!(imports.contains("Drawable"));
    }
}
