//! TypeScript code generation for Phoenix Gen.
//!
//! Generates four files from a Phoenix program:
//! - **types.ts** — TypeScript interfaces for structs, string unions for enums,
//!   derived type aliases for endpoint body types, and error type definitions.
//! - **client.ts** — a fetch-based client SDK with typed async functions for
//!   each endpoint, including query parameter handling and typed error responses.
//! - **handlers.ts** — a `Handlers` interface that server implementations must
//!   satisfy, with typed method signatures for each endpoint.
//! - **server.ts** — an Express-compatible router that wires HTTP routes to
//!   handler methods with automatic parameter parsing and error mapping.

use std::collections::BTreeSet;

use phoenix_parser::ast::{Declaration, EnumDecl, Program, StructDecl, TypeExpr};
use phoenix_sema::checker::{CheckResult, DefaultValue, EndpointInfo, ResolvedDerivedType};
use phoenix_sema::types::Type;

/// The output of TypeScript code generation: four file contents.
pub struct GeneratedFiles {
    /// Content for `types.ts` — interfaces, enums, derived types, error types.
    pub types: String,
    /// Content for `client.ts` — fetch-based client SDK.
    pub client: String,
    /// Content for `handlers.ts` — server handler interface.
    pub handlers: String,
    /// Content for `server.ts` — Express-compatible router wiring.
    pub server: String,
}

/// Generates TypeScript code from a parsed and type-checked Phoenix program.
///
/// Iterates over declarations in source order to produce deterministic,
/// diff-friendly output.
pub fn generate_typescript(program: &Program, check_result: &CheckResult) -> GeneratedFiles {
    let generator = TsGenerator::new(check_result);
    generator.generate(program)
}

/// Internal TypeScript code generator.
///
/// Accumulates generated code for `types.ts`, `client.ts`, `handlers.ts`,
/// and `server.ts` in separate string buffers, using the semantic analysis
/// results to resolve types and build correct signatures.
struct TsGenerator<'a> {
    /// Semantic analysis results providing resolved types, struct info, and
    /// endpoint definitions.
    check_result: &'a CheckResult,
    /// Accumulated output for `types.ts`.
    types_out: String,
    /// Accumulated output for `client.ts`.
    client_out: String,
    /// Accumulated output for `handlers.ts`.
    handlers_out: String,
    /// Accumulated output for `server.ts`.
    server_out: String,
    /// Tracks which derived type names have been emitted to avoid duplicates.
    emitted_derived_types: BTreeSet<String>,
    /// Whether the `ValidationError` class has been emitted.
    emitted_validation_error: bool,
}

impl<'a> TsGenerator<'a> {
    /// Creates a new TypeScript generator with the given semantic analysis results.
    fn new(check_result: &'a CheckResult) -> Self {
        Self {
            check_result,
            types_out: String::new(),
            client_out: String::new(),
            handlers_out: String::new(),
            server_out: String::new(),
            emitted_derived_types: BTreeSet::new(),
            emitted_validation_error: false,
        }
    }

    /// Generates TypeScript `types.ts`, `client.ts`, and `handlers.ts` from the
    /// program AST.
    fn generate(mut self, program: &Program) -> GeneratedFiles {
        // Generate types.ts
        self.types_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");

        for decl in &program.declarations {
            match decl {
                Declaration::Struct(s) => self.emit_struct(s),
                Declaration::Enum(e) => self.emit_enum(e),
                _ => {}
            }
        }

        // Emit struct-level validation functions
        for decl in &program.declarations {
            if let Declaration::Struct(s) = decl {
                self.emit_struct_validation(s);
            }
        }

        // Emit derived types and error types for endpoints
        for ep in &self.check_result.endpoints {
            self.emit_endpoint_derived_type(ep);
        }
        for ep in &self.check_result.endpoints {
            self.emit_endpoint_error_types(ep);
        }

        // Emit validation functions for endpoints with constrained body fields
        for ep in &self.check_result.endpoints {
            self.emit_validation_function(ep);
        }

        // Generate client.ts
        self.client_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");
        self.emit_client_imports();
        self.emit_client_preamble();

        for ep in &self.check_result.endpoints {
            self.emit_client_function(ep);
        }

        self.client_out.push_str("}\n");

        // Generate handlers.ts
        self.handlers_out
            .push_str("// Generated by Phoenix Gen — implement the handler methods below.\n\n");
        self.emit_handler_imports();
        self.handlers_out.push_str("export interface Handlers {\n");

        for ep in &self.check_result.endpoints {
            self.emit_handler_method(ep);
        }

        self.handlers_out.push_str("}\n");

        // Generate server.ts (Express-compatible router)
        self.server_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");
        self.emit_server_imports();
        self.emit_server_router();

        GeneratedFiles {
            types: self.types_out,
            client: self.client_out,
            handlers: self.handlers_out,
            server: self.server_out,
        }
    }

    // ── Type emission ────────────────────────────────────────────────

    /// Emits a TypeScript `export interface` for a Phoenix struct.
    fn emit_struct(&mut self, s: &StructDecl) {
        if let Some(ref doc) = s.doc_comment {
            self.types_out.push_str(&format!("/** {} */\n", doc));
        }
        self.types_out
            .push_str(&format!("export interface {} {{\n", s.name));

        if let Some(info) = self.check_result.structs.get(&s.name) {
            for f in &info.fields {
                let ts_type = type_to_ts(&f.ty);
                let optional = matches!(&f.ty, Type::Generic(name, _) if name == "Option");
                if optional {
                    self.types_out
                        .push_str(&format!("  {}?: {};\n", f.name, ts_type));
                } else {
                    self.types_out
                        .push_str(&format!("  {}: {};\n", f.name, ts_type));
                }
            }
        }

        self.types_out.push_str("}\n\n");
    }

    /// Emits a `validate{StructName}` function for a struct with constrained fields.
    fn emit_struct_validation(&mut self, s: &StructDecl) {
        let Some(info) = self.check_result.structs.get(&s.name) else {
            return;
        };
        if !info.fields.iter().any(|f| f.constraint.is_some()) {
            return;
        }

        // Emit ValidationError class once
        if !self.emitted_validation_error {
            self.types_out
                .push_str("export class ValidationError extends Error {\n");
            self.types_out
                .push_str("  constructor(message: string) {\n");
            self.types_out.push_str("    super(message);\n");
            self.types_out
                .push_str("    this.name = \"ValidationError\";\n");
            self.types_out.push_str("  }\n");
            self.types_out.push_str("}\n\n");
            self.emitted_validation_error = true;
        }

        self.types_out.push_str(&format!(
            "export function validate{}(input: unknown): {} {{\n",
            s.name, s.name
        ));
        self.types_out.push_str(
            "  if (typeof input !== 'object' || input === null) throw new ValidationError('expected object');\n",
        );
        self.types_out
            .push_str("  const obj = input as Record<string, unknown>;\n");

        for f in &info.fields {
            let is_option = matches!(&f.ty, Type::Generic(name, _) if name == "Option");
            let inner_ty = if is_option {
                if let Type::Generic(_, args) = &f.ty {
                    &args[0]
                } else {
                    &f.ty
                }
            } else {
                &f.ty
            };

            let ts_typeof = match inner_ty {
                Type::Int | Type::Float => Some("number"),
                Type::String => Some("string"),
                Type::Bool => Some("boolean"),
                _ => None,
            };

            // Type check for primitive fields
            if let Some(typeof_str) = ts_typeof {
                if is_option {
                    self.types_out.push_str(&format!(
                        "  if (obj.{name} !== undefined && typeof obj.{name} !== '{ty}') throw new ValidationError('{name}: expected {ty}');\n",
                        name = f.name, ty = typeof_str
                    ));
                } else {
                    self.types_out.push_str(&format!(
                        "  if (typeof obj.{name} !== '{ty}') throw new ValidationError('{name}: expected {ty}');\n",
                        name = f.name, ty = typeof_str
                    ));
                }
            }

            // Constraint check
            if let Some(ref constraint) = f.constraint {
                let ts_expr = constraint_expr_to_ts(constraint, &f.name);
                if is_option {
                    self.types_out.push_str(&format!(
                        "  if (obj.{name} !== undefined && !({expr})) throw new ValidationError('{name}: constraint violated');\n",
                        name = f.name, expr = ts_expr,
                    ));
                } else {
                    self.types_out.push_str(&format!(
                        "  if (!({expr})) throw new ValidationError('{name}: constraint violated');\n",
                        name = f.name, expr = ts_expr,
                    ));
                }
            }
        }

        self.types_out
            .push_str(&format!("  return obj as unknown as {};\n", s.name));
        self.types_out.push_str("}\n\n");
    }

    /// Emits a TypeScript string union type for a Phoenix enum (simple variants only).
    fn emit_enum(&mut self, e: &EnumDecl) {
        if let Some(ref doc) = e.doc_comment {
            self.types_out.push_str(&format!("/** {} */\n", doc));
        }

        let all_unit = e.variants.iter().all(|v| v.fields.is_empty());
        if all_unit {
            // Simple enum → string union
            let variants: Vec<String> = e
                .variants
                .iter()
                .map(|v| format!("\"{}\"", v.name))
                .collect();
            self.types_out.push_str(&format!(
                "export type {} = {};\n\n",
                e.name,
                variants.join(" | ")
            ));
        } else {
            // Tagged union
            self.types_out
                .push_str(&format!("export type {} =\n", e.name));
            for v in &e.variants {
                if v.fields.is_empty() {
                    self.types_out
                        .push_str(&format!("  | {{ tag: \"{}\" }}\n", v.name));
                } else if v.fields.len() == 1 {
                    let ts = type_expr_to_ts(&v.fields[0]);
                    self.types_out
                        .push_str(&format!("  | {{ tag: \"{}\"; value: {} }}\n", v.name, ts));
                } else {
                    let ts: Vec<String> = v.fields.iter().map(type_expr_to_ts).collect();
                    self.types_out.push_str(&format!(
                        "  | {{ tag: \"{}\"; value: [{}] }}\n",
                        v.name,
                        ts.join(", ")
                    ));
                }
            }
            self.types_out.push('\n');
        }
    }

    /// Emits a derived type alias for an endpoint body (e.g., `Omit<User, "id">`).
    fn emit_endpoint_derived_type(&mut self, ep: &EndpointInfo) {
        let Some(ref body) = ep.body else { return };
        let type_name = format!("{}Body", capitalize(&ep.name));

        if !self.emitted_derived_types.insert(type_name.clone()) {
            return;
        }

        let ts_type = derived_type_to_ts(body);
        self.types_out
            .push_str(&format!("export type {} = {};\n\n", type_name, ts_type));
    }

    /// Emits error type definitions for an endpoint's error variants.
    ///
    /// For an endpoint with `error { NotFound(404), Conflict(409) }`, produces:
    /// ```typescript
    /// export type CreateUserError = "NotFound" | "Conflict";
    /// export const CreateUserErrors = { NotFound: 404, Conflict: 409 } as const;
    /// ```
    fn emit_endpoint_error_types(&mut self, ep: &EndpointInfo) {
        if ep.errors.is_empty() {
            return;
        }

        let type_name = format!("{}Error", capitalize(&ep.name));

        // String union of error variant names
        let variants: Vec<String> = ep
            .errors
            .iter()
            .map(|(name, _)| format!("\"{name}\""))
            .collect();
        self.types_out.push_str(&format!(
            "export type {} = {};\n\n",
            type_name,
            variants.join(" | ")
        ));

        // Const object mapping variant names to status codes
        let entries: Vec<String> = ep
            .errors
            .iter()
            .map(|(name, code)| format!("  {name}: {code}"))
            .collect();
        self.types_out.push_str(&format!(
            "export const {}Errors = {{\n{},\n}} as const;\n\n",
            capitalize(&ep.name),
            entries.join(",\n")
        ));
    }

    /// Emits a `ValidationError` class and a typed `validate*Body` function for
    /// an endpoint whose body has at least one constrained field.
    fn emit_validation_function(&mut self, ep: &EndpointInfo) {
        let Some(ref body) = ep.body else { return };
        let has_constraints = body.fields.iter().any(|f| f.constraint.is_some());
        if !has_constraints {
            return;
        }

        // Emit ValidationError class once
        if !self.emitted_validation_error {
            self.types_out
                .push_str("export class ValidationError extends Error {\n");
            self.types_out
                .push_str("  constructor(message: string) {\n");
            self.types_out.push_str("    super(message);\n");
            self.types_out
                .push_str("    this.name = \"ValidationError\";\n");
            self.types_out.push_str("  }\n");
            self.types_out.push_str("}\n\n");
            self.emitted_validation_error = true;
        }

        let type_name = format!("{}Body", capitalize(&ep.name));
        self.types_out.push_str(&format!(
            "export function validate{}(input: unknown): {} {{\n",
            type_name, type_name
        ));
        self.types_out.push_str(
            "  if (typeof input !== 'object' || input === null) throw new ValidationError('expected object');\n",
        );
        self.types_out
            .push_str("  const obj = input as Record<string, unknown>;\n");

        for f in &body.fields {
            let ts_typeof = match &f.ty {
                Type::Int | Type::Float => Some("number"),
                Type::String => Some("string"),
                Type::Bool => Some("boolean"),
                _ => None,
            };

            // Type check for primitive fields
            if let Some(typeof_str) = ts_typeof {
                if f.optional {
                    self.types_out.push_str(&format!(
                        "  if (obj.{name} !== undefined && typeof obj.{name} !== '{ty}') throw new ValidationError('{name}: expected {ty}');\n",
                        name = f.name, ty = typeof_str
                    ));
                } else {
                    self.types_out.push_str(&format!(
                        "  if (typeof obj.{name} !== '{ty}') throw new ValidationError('{name}: expected {ty}');\n",
                        name = f.name, ty = typeof_str
                    ));
                }
            }

            // Constraint check
            if let Some(ref constraint) = f.constraint {
                let ts_expr = constraint_expr_to_ts(constraint, &f.name);
                if f.optional {
                    self.types_out.push_str(&format!(
                        "  if (obj.{name} !== undefined && !({expr})) throw new ValidationError('{name}: constraint violated');\n",
                        name = f.name, expr = ts_expr,
                    ));
                } else {
                    self.types_out.push_str(&format!(
                        "  if (!({expr})) throw new ValidationError('{name}: constraint violated');\n",
                        name = f.name, expr = ts_expr,
                    ));
                }
            }
        }

        self.types_out
            .push_str(&format!("  return obj as unknown as {};\n", type_name));
        self.types_out.push_str("}\n\n");
    }

    // ── Client emission ──────────────────────────────────────────────

    /// Emits import statements for the client file, collecting all user-defined
    /// type names referenced by endpoint signatures.
    fn emit_client_imports(&mut self) {
        let mut type_imports = BTreeSet::new();

        for ep in &self.check_result.endpoints {
            if ep.body.is_some() {
                type_imports.insert(format!("{}Body", capitalize(&ep.name)));
            }
            if let Some(ref resp) = ep.response {
                collect_import_names(resp, &mut type_imports);
            }
        }

        if !type_imports.is_empty() {
            let joined: Vec<_> = type_imports.into_iter().collect();
            self.client_out.push_str(&format!(
                "import type {{ {} }} from \"./types\";\n\n",
                joined.join(", ")
            ));
        }
    }

    /// Emits the client preamble: `ApiError` class (if needed), base URL
    /// configuration, and the opening of the `api` object.
    fn emit_client_preamble(&mut self) {
        // Emit ApiError class if any endpoint has error variants
        let has_errors = self
            .check_result
            .endpoints
            .iter()
            .any(|ep| !ep.errors.is_empty());
        if has_errors {
            self.client_out
                .push_str("export class ApiError extends Error {\n");
            self.client_out.push_str("  constructor(\n");
            self.client_out
                .push_str("    public readonly code: string,\n");
            self.client_out
                .push_str("    public readonly status: number,\n");
            self.client_out
                .push_str("    public readonly body: string,\n");
            self.client_out.push_str("  ) {\n");
            self.client_out
                .push_str("    super(`${code} (${status}): ${body}`);\n");
            self.client_out.push_str("    this.name = \"ApiError\";\n");
            self.client_out.push_str("  }\n");
            self.client_out.push_str("}\n\n");
        }

        self.client_out.push_str("export let baseUrl = \"\";\n\n");
        self.client_out
            .push_str("export function setBaseUrl(url: string): void {\n");
        self.client_out.push_str("  baseUrl = url;\n");
        self.client_out.push_str("}\n\n");
        self.client_out.push_str("export const api = {\n");
    }

    /// Emits a single async client function for an endpoint, including query
    /// parameter construction, body serialization, and typed error handling.
    fn emit_client_function(&mut self, ep: &EndpointInfo) {
        let method = ep.method.as_upper_str();
        let response_type = ep
            .response
            .as_ref()
            .map(type_to_ts)
            .unwrap_or_else(|| "void".to_string());
        let has_query = !ep.query_params.is_empty();

        // Build function parameters
        let mut params = Vec::new();
        for pp in &ep.path_params {
            params.push(format!("{pp}: string"));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(format!("body: {body_type}"));
        }
        if has_query {
            let fields: Vec<String> = ep
                .query_params
                .iter()
                .map(|qp| {
                    let ts_ty = type_to_ts(&qp.ty);
                    if is_query_param_optional(qp) {
                        format!("{}?: {}", qp.name, ts_ty)
                    } else {
                        format!("{}: {}", qp.name, ts_ty)
                    }
                })
                .collect();
            let all_optional = ep.query_params.iter().all(is_query_param_optional);
            if all_optional {
                params.push(format!("opts?: {{ {} }}", fields.join("; ")));
            } else {
                params.push(format!("opts: {{ {} }}", fields.join("; ")));
            }
        }

        let params_str = params.join(", ");

        // Doc comment
        if let Some(ref doc) = ep.doc_comment {
            self.client_out.push_str(&format!("  /** {} */\n", doc));
        }

        // Function signature
        self.client_out.push_str(&format!(
            "  async {}({}): Promise<{}> {{\n",
            ep.name, params_str, response_type
        ));

        // Query string construction (only if endpoint has query params)
        if has_query {
            self.client_out
                .push_str("    const params = new URLSearchParams();\n");
            for qp in &ep.query_params {
                self.client_out.push_str(&format!(
                    "    if (opts?.{name} !== undefined) params.set(\"{name}\", String(opts.{name}));\n",
                    name = qp.name
                ));
            }
            self.client_out
                .push_str("    const query = params.toString();\n");
        }

        // Build URL with path param substitution
        let url_expr = build_url_expr(&ep.path, &ep.path_params);
        if has_query {
            self.client_out.push_str(&format!(
                "    const response = await fetch(`${{baseUrl}}{url_expr}${{query ? `?${{query}}` : \"\"}}`, {{\n"
            ));
        } else {
            self.client_out.push_str(&format!(
                "    const response = await fetch(`${{baseUrl}}{url_expr}`, {{\n"
            ));
        }
        self.client_out
            .push_str(&format!("      method: \"{method}\",\n"));

        if ep.body.is_some() {
            self.client_out
                .push_str("      headers: { \"Content-Type\": \"application/json\" },\n");
            self.client_out
                .push_str("      body: JSON.stringify(body),\n");
        }

        self.client_out.push_str("    });\n");

        // Error handling
        if ep.errors.is_empty() {
            self.client_out.push_str("    if (!response.ok) {\n");
            self.client_out
                .push_str("      throw new Error(`${response.status}: ${response.statusText}`);\n");
            self.client_out.push_str("    }\n");
        } else {
            self.client_out.push_str("    if (!response.ok) {\n");
            self.client_out
                .push_str("      const errorBody = await response.text();\n");
            for (name, code) in &ep.errors {
                self.client_out.push_str(&format!(
                    "      if (response.status === {code}) throw new ApiError(\"{name}\", {code}, errorBody);\n"
                ));
            }
            self.client_out
                .push_str("      throw new ApiError(\"Unknown\", response.status, errorBody);\n");
            self.client_out.push_str("    }\n");
        }

        // Return
        if response_type != "void" {
            self.client_out
                .push_str("    return await response.json();\n");
        }

        self.client_out.push_str("  },\n\n");
    }

    // ── Handler emission ────────────────────────────────────────────

    /// Emits import statements for the handlers file, collecting all
    /// user-defined type names referenced by handler signatures.
    fn emit_handler_imports(&mut self) {
        let mut imports = BTreeSet::new();

        for ep in &self.check_result.endpoints {
            if ep.body.is_some() {
                imports.insert(format!("{}Body", capitalize(&ep.name)));
            }
            if let Some(ref resp) = ep.response {
                collect_import_names(resp, &mut imports);
            }
        }

        if !imports.is_empty() {
            let joined: Vec<_> = imports.into_iter().collect();
            self.handlers_out.push_str(&format!(
                "import type {{ {} }} from \"./types\";\n\n",
                joined.join(", ")
            ));
        }
    }

    /// Emits a single method signature in the `Handlers` interface for an
    /// endpoint.
    ///
    /// Handler methods receive path params as individual arguments, body as a
    /// typed parameter, and query params as a required object (the server
    /// framework applies defaults before calling the handler).
    fn emit_handler_method(&mut self, ep: &EndpointInfo) {
        let response_type = ep
            .response
            .as_ref()
            .map(type_to_ts)
            .unwrap_or_else(|| "void".to_string());

        let mut params = Vec::new();
        for pp in &ep.path_params {
            params.push(format!("{pp}: string"));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(format!("body: {body_type}"));
        }
        if !ep.query_params.is_empty() {
            let fields: Vec<String> = ep
                .query_params
                .iter()
                .map(|qp| {
                    let ts_ty = type_to_ts(&qp.ty);
                    // In handlers, Option<T> fields are optional; others are required
                    // (defaults have been applied by the framework before the handler).
                    let optional = matches!(&qp.ty, Type::Generic(name, _) if name == "Option");
                    if optional {
                        format!("{}?: {}", qp.name, ts_ty)
                    } else {
                        format!("{}: {}", qp.name, ts_ty)
                    }
                })
                .collect();
            params.push(format!("query: {{ {} }}", fields.join("; ")));
        }

        let params_str = params.join(", ");

        if let Some(ref doc) = ep.doc_comment {
            self.handlers_out.push_str(&format!("  /** {} */\n", doc));
        }
        self.handlers_out.push_str(&format!(
            "  {}({}): Promise<{}>;\n",
            ep.name, params_str, response_type
        ));
    }
    // ── Server router emission ─────────────────────────────────────

    /// Emits import statements for the server router file, including validation
    /// function imports for endpoints with constrained body types.
    fn emit_server_imports(&mut self) {
        self.server_out
            .push_str("import { Router } from \"express\";\n");
        self.server_out
            .push_str("import type { Request, Response } from \"express\";\n");
        self.server_out
            .push_str("import type { Handlers } from \"./handlers\";\n");

        // Import validation functions for endpoints with constrained bodies
        let mut validate_imports: Vec<String> = Vec::new();
        for ep in &self.check_result.endpoints {
            if let Some(ref body) = ep.body
                && body.fields.iter().any(|f| f.constraint.is_some())
            {
                let type_name = format!("{}Body", capitalize(&ep.name));
                validate_imports.push(format!("validate{type_name}"));
            }
        }
        if !validate_imports.is_empty() {
            validate_imports.insert(0, "ValidationError".to_string());
            self.server_out.push_str(&format!(
                "import {{ {} }} from \"./types\";\n",
                validate_imports.join(", ")
            ));
        }

        self.server_out.push('\n');
    }

    /// Emits an Express-compatible `createRouter` function that wires each
    /// endpoint to its handler, parsing path/query/body parameters and
    /// mapping errors to HTTP status codes.
    fn emit_server_router(&mut self) {
        self.server_out
            .push_str("export function createRouter(handlers: Handlers): Router {\n");
        self.server_out.push_str("  const router = Router();\n\n");

        for ep in &self.check_result.endpoints {
            self.emit_server_route(ep);
        }

        self.server_out.push_str("  return router;\n");
        self.server_out.push_str("}\n");
    }

    /// Emits a single Express route handler for an endpoint.
    fn emit_server_route(&mut self, ep: &EndpointInfo) {
        let method = ep.method.as_lower_str();

        // Convert Phoenix path params to Express-style: {id} → :id
        let express_path = ep.path.replace('{', ":").replace('}', "");

        self.server_out.push_str(&format!(
            "  router.{}(\"{}\", async (req: Request, res: Response) => {{\n",
            method, express_path
        ));
        self.server_out.push_str("    try {\n");

        // Build handler call arguments
        let mut args = Vec::new();

        // Path params: extract from req.params
        for pp in &ep.path_params {
            self.server_out
                .push_str(&format!("      const {pp} = req.params.{pp};\n"));
            args.push(pp.clone());
        }

        // Body: parse from req.body, with validation if constraints exist
        if let Some(ref body) = ep.body {
            let has_constraints = body.fields.iter().any(|f| f.constraint.is_some());
            if has_constraints {
                let type_name = format!("{}Body", capitalize(&ep.name));
                self.server_out.push_str(&format!(
                    "      const body = validate{}(req.body);\n",
                    type_name
                ));
            } else {
                self.server_out.push_str("      const body = req.body;\n");
            }
            args.push("body".to_string());
        }

        // Query params: extract, coerce, and apply defaults
        if !ep.query_params.is_empty() {
            self.server_out.push_str("      const query = {\n");
            for qp in &ep.query_params {
                let coerce = query_param_coercion(qp);
                self.server_out
                    .push_str(&format!("        {}: {},\n", qp.name, coerce));
            }
            self.server_out.push_str("      };\n");
            args.push("query".to_string());
        }

        // Call the handler
        let args_str = args.join(", ");
        if ep.response.is_some() {
            self.server_out.push_str(&format!(
                "      const result = await handlers.{}({});\n",
                ep.name, args_str
            ));
            self.server_out.push_str("      res.json(result);\n");
        } else {
            self.server_out.push_str(&format!(
                "      await handlers.{}({});\n",
                ep.name, args_str
            ));
            self.server_out.push_str("      res.status(204).end();\n");
        }

        // Error handling with status code mapping
        self.server_out.push_str("    } catch (error: unknown) {\n");

        // Catch validation errors from constrained bodies
        let has_body_constraints = ep
            .body
            .as_ref()
            .is_some_and(|b| b.fields.iter().any(|f| f.constraint.is_some()));
        if has_body_constraints {
            self.server_out.push_str(
                "      if (error instanceof ValidationError) { res.status(400).json({ error: error.message }); return; }\n",
            );
        }

        if ep.errors.is_empty() {
            self.server_out
                .push_str("      res.status(500).json({ error: \"Internal Server Error\" });\n");
        } else {
            self.server_out
                .push_str("      if (error instanceof Error) {\n");
            for (name, code) in &ep.errors {
                self.server_out.push_str(&format!(
                    "        if (error.message === \"{name}\") {{ res.status({code}).json({{ error: \"{name}\" }}); return; }}\n"
                ));
            }
            self.server_out.push_str("      }\n");
            self.server_out
                .push_str("      res.status(500).json({ error: \"Internal Server Error\" });\n");
        }
        self.server_out.push_str("    }\n");
        self.server_out.push_str("  });\n\n");
    }
}

// ── Helper functions ─────────────────────────────────────────────────

/// Generates a TypeScript expression that extracts and coerces a query
/// parameter from `req.query`, applying the default value if the parameter
/// is absent.
fn query_param_coercion(qp: &phoenix_sema::checker::QueryParamInfo) -> String {
    let raw = format!("req.query.{}", qp.name);
    let is_option = matches!(&qp.ty, Type::Generic(name, _) if name == "Option");

    // Determine the coercion expression based on the resolved type
    let coerced = match &qp.ty {
        Type::Int | Type::Float => format!("Number({raw})"),
        Type::Bool => format!("{raw} === \"true\""),
        Type::String => format!("{raw} as string"),
        Type::Generic(name, args) if name == "Option" && !args.is_empty() => {
            // For Option<T>, coerce the inner type if present
            match &args[0] {
                Type::Int | Type::Float => {
                    format!("{raw} !== undefined ? Number({raw}) : undefined")
                }
                Type::Bool => format!("{raw} !== undefined ? {raw} === \"true\" : undefined"),
                _ => format!("{raw} as string | undefined"),
            }
        }
        _ => format!("{raw} as string"),
    };

    // Apply default value if present
    if is_option {
        return coerced;
    }
    if let Some(ref default) = qp.default_value {
        let default_ts = default_value_to_ts(default);
        format!("{raw} !== undefined ? {coerced} : {default_ts}")
    } else {
        coerced
    }
}

/// Converts a [`DefaultValue`] to a TypeScript literal.
fn default_value_to_ts(val: &DefaultValue) -> String {
    match val {
        DefaultValue::Int(v) => v.to_string(),
        DefaultValue::Float(v) => v.to_string(),
        DefaultValue::String(v) => format!("\"{}\"", v),
        DefaultValue::Bool(v) => v.to_string(),
    }
}

/// Recursively converts a Phoenix constraint `Expr` to a TypeScript expression
/// string, replacing `self` with `obj.{field_name}` for use in validation
/// functions.
fn constraint_expr_to_ts(expr: &phoenix_parser::ast::Expr, field_name: &str) -> String {
    use phoenix_parser::ast::{BinaryOp, Expr, LiteralKind, UnaryOp};
    match expr {
        Expr::Ident(ident) if ident.name == "self" => format!("obj.{field_name}"),
        Expr::Ident(ident) => ident.name.clone(),
        Expr::Literal(lit) => match &lit.kind {
            LiteralKind::Int(v) => v.to_string(),
            LiteralKind::Float(v) => v.to_string(),
            LiteralKind::String(v) => format!("\"{}\"", v),
            LiteralKind::Bool(v) => v.to_string(),
        },
        Expr::Binary(bin) => {
            let left = constraint_expr_to_ts(&bin.left, field_name);
            let right = constraint_expr_to_ts(&bin.right, field_name);
            let op = match bin.op {
                BinaryOp::Add => "+",
                BinaryOp::Sub => "-",
                BinaryOp::Mul => "*",
                BinaryOp::Div => "/",
                BinaryOp::Mod => "%",
                BinaryOp::Eq => "===",
                BinaryOp::NotEq => "!==",
                BinaryOp::Lt => "<",
                BinaryOp::Gt => ">",
                BinaryOp::LtEq => "<=",
                BinaryOp::GtEq => ">=",
                BinaryOp::And => "&&",
                BinaryOp::Or => "||",
            };
            format!("({left} {op} {right})")
        }
        Expr::Unary(un) => {
            let operand = constraint_expr_to_ts(&un.operand, field_name);
            match un.op {
                UnaryOp::Neg => format!("(-{operand})"),
                UnaryOp::Not => format!("(!{operand})"),
            }
        }
        Expr::FieldAccess(fa) => {
            let object = constraint_expr_to_ts(&fa.object, field_name);
            format!("{object}.{}", fa.field)
        }
        Expr::MethodCall(mc) => {
            let object = constraint_expr_to_ts(&mc.object, field_name);
            let args: Vec<String> = mc
                .args
                .iter()
                .map(|a| constraint_expr_to_ts(a, field_name))
                .collect();
            // Map Phoenix method names to JS equivalents
            let method = match mc.method.as_str() {
                "contains" => "includes",
                other => other,
            };
            format!("{object}.{method}({})", args.join(", "))
        }
        _ => "true".to_string(),
    }
}

/// Converts a resolved Phoenix `Type` to a TypeScript type string.
fn type_to_ts(ty: &Type) -> String {
    match ty {
        Type::Int | Type::Float => "number".to_string(),
        Type::String => "string".to_string(),
        Type::Bool => "boolean".to_string(),
        Type::Void => "void".to_string(),
        Type::Named(name) => name.clone(),
        Type::Generic(name, args) if name == "List" && args.len() == 1 => {
            format!("{}[]", type_to_ts(&args[0]))
        }
        Type::Generic(name, args) if name == "Map" && args.len() == 2 => {
            format!("Record<{}, {}>", type_to_ts(&args[0]), type_to_ts(&args[1]))
        }
        Type::Generic(name, args) if name == "Option" && args.len() == 1 => {
            format!("{} | undefined", type_to_ts(&args[0]))
        }
        Type::Generic(name, args) => {
            let ts_args: Vec<String> = args.iter().map(type_to_ts).collect();
            format!("{}<{}>", name, ts_args.join(", "))
        }
        Type::Function(params, ret) => {
            let ps: Vec<String> = params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, type_to_ts(p)))
                .collect();
            format!("({}) => {}", ps.join(", "), type_to_ts(ret))
        }
        Type::TypeVar(name) => name.clone(),
        // Trait objects erase to the trait name on the TS side (structural
        // interface dispatch handles the runtime variance); sharper mappings
        // can replace this when specific traits get per-trait TS shims.
        Type::Dyn(name) => name.clone(),
        Type::Error => "unknown".to_string(),
    }
}

/// Converts a Phoenix `TypeExpr` (AST node) to a TypeScript type string.
/// Used for enum variant fields which only have AST-level type info.
fn type_expr_to_ts(te: &TypeExpr) -> String {
    match te {
        TypeExpr::Named(n) => match n.name.as_str() {
            "Int" | "Float" => "number".to_string(),
            "String" => "string".to_string(),
            "Bool" => "boolean".to_string(),
            "Void" => "void".to_string(),
            other => other.to_string(),
        },
        TypeExpr::Generic(g) => {
            let args: Vec<String> = g.type_args.iter().map(type_expr_to_ts).collect();
            match g.name.as_str() {
                "List" if args.len() == 1 => format!("{}[]", args[0]),
                "Option" if args.len() == 1 => format!("{} | undefined", args[0]),
                "Map" if args.len() == 2 => format!("Record<{}, {}>", args[0], args[1]),
                _ => format!("{}<{}>", g.name, args.join(", ")),
            }
        }
        TypeExpr::Function(f) => {
            let ps: Vec<String> = f
                .param_types
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, type_expr_to_ts(p)))
                .collect();
            format!("({}) => {}", ps.join(", "), type_expr_to_ts(&f.return_type))
        }
        TypeExpr::Dyn(d) => d.trait_name.clone(),
    }
}

/// Converts a resolved derived type to a TypeScript type expression.
///
/// Emits an inline object type to faithfully represent the derived fields
/// with their optionality. This covers all modifier combinations (omit,
/// pick, partial, selective partial).
fn derived_type_to_ts(body: &ResolvedDerivedType) -> String {
    let all_optional = !body.fields.is_empty() && body.fields.iter().all(|f| f.optional);

    if all_optional {
        // All optional — emit Partial with inline type for the fields
        let mut parts = Vec::new();
        for f in &body.fields {
            let ts = type_to_ts(&f.ty);
            parts.push(format!("  {}?: {};", f.name, ts));
        }
        return format!("{{\n{}\n}}", parts.join("\n"));
    }

    // Emit inline object type with the actual derived fields
    let mut parts = Vec::new();
    for f in &body.fields {
        let ts = type_to_ts(&f.ty);
        if f.optional {
            parts.push(format!("  {}?: {};", f.name, ts));
        } else {
            parts.push(format!("  {}: {};", f.name, ts));
        }
    }
    format!("{{\n{}\n}}", parts.join("\n"))
}

/// Recursively collects user-defined type names that need to be imported.
///
/// Skips built-in generic wrappers (`List`, `Option`, `Map`, `Result`) since
/// they map to native TypeScript constructs, but descends into their type
/// arguments to find the actual user-defined types (e.g., `List<User>` imports
/// `User`, not `List`).
fn collect_import_names(ty: &Type, imports: &mut BTreeSet<String>) {
    match ty {
        Type::Named(name) => {
            imports.insert(name.clone());
        }
        Type::Generic(name, args) => {
            if !matches!(name.as_str(), "List" | "Option" | "Map" | "Result") {
                imports.insert(name.clone());
            }
            for arg in args {
                collect_import_names(arg, imports);
            }
        }
        _ => {}
    }
}

/// Returns whether a query parameter should be optional in the client function
/// signature (either it has a default value or its type is `Option<T>`).
fn is_query_param_optional(qp: &phoenix_sema::checker::QueryParamInfo) -> bool {
    qp.has_default || matches!(&qp.ty, Type::Generic(name, _) if name == "Option")
}

/// Builds a URL template expression with path parameter substitution.
///
/// `/api/users/{id}` → `/api/users/${id}`
fn build_url_expr(path: &str, _params: &[String]) -> String {
    path.replace('{', "${")
}

use crate::capitalize;

#[cfg(test)]
mod tests {
    use super::*;
    use phoenix_common::span::SourceId;
    use phoenix_lexer::lexer::tokenize;
    use phoenix_parser::parser;
    use phoenix_sema::checker;

    /// Parses, type-checks, and generates TypeScript from a Phoenix source string.
    fn generate_from_source(source: &str) -> GeneratedFiles {
        let tokens = tokenize(source, SourceId(0));
        let (program, parse_errors) = parser::parse(&tokens);
        assert!(
            parse_errors.is_empty(),
            "unexpected parse errors: {parse_errors:?}"
        );
        let result = checker::check(&program);
        assert!(
            result.diagnostics.is_empty(),
            "unexpected check errors: {:?}",
            result.diagnostics
        );
        generate_typescript(&program, &result)
    }

    // ── types.ts tests ──────────────────────────────────────────────

    #[test]
    fn struct_to_interface() {
        let files = generate_from_source(
            r#"
/** A registered user */
struct User {
    Int id
    String name
    String email
    Option<String> bio
}
"#,
        );
        insta::assert_snapshot!("struct_to_interface_types", files.types);
    }

    #[test]
    fn simple_enum_to_union() {
        let files = generate_from_source(
            r#"
/** User roles */
enum Role { Admin  Editor  Viewer }
"#,
        );
        insta::assert_snapshot!("simple_enum_to_union_types", files.types);
    }

    #[test]
    fn tagged_enum_to_union() {
        let files = generate_from_source(
            r#"
enum Shape {
    Circle(Float)
    Rect(Float, Float)
    Point
}
"#,
        );
        insta::assert_snapshot!("tagged_enum_to_union_types", files.types);
    }

    // ── client.ts tests ─────────────────────────────────────────────

    #[test]
    fn get_with_path_param() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint getUser: GET "/api/users/{id}" {
    response User
}
"#,
        );
        insta::assert_snapshot!("get_with_path_param_types", files.types);
        insta::assert_snapshot!("get_with_path_param_client", files.client);
        insta::assert_snapshot!("get_with_path_param_handlers", files.handlers);
    }

    #[test]
    fn post_with_body_omit() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
"#,
        );
        insta::assert_snapshot!("post_with_body_omit_types", files.types);
        insta::assert_snapshot!("post_with_body_omit_client", files.client);
        insta::assert_snapshot!("post_with_body_omit_handlers", files.handlers);
    }

    #[test]
    fn patch_with_partial() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email  Int age }
endpoint updateUser: PATCH "/api/users/{id}" {
    body User omit { id } partial
    response User
}
"#,
        );
        insta::assert_snapshot!("patch_with_partial_types", files.types);
        insta::assert_snapshot!("patch_with_partial_client", files.client);
    }

    #[test]
    fn get_with_query_params_all_optional() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint listUsers: GET "/api/users" {
    query {
        Int page = 1
        Int limit = 20
        Option<String> search
    }
    response List<User>
}
"#,
        );
        insta::assert_snapshot!("get_with_query_all_optional_types", files.types);
        insta::assert_snapshot!("get_with_query_all_optional_client", files.client);
        insta::assert_snapshot!("get_with_query_all_optional_handlers", files.handlers);
    }

    #[test]
    fn get_with_query_params_some_required() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint searchUsers: GET "/api/users/search" {
    query {
        String term
        Int page = 1
    }
    response List<User>
}
"#,
        );
        insta::assert_snapshot!("get_with_query_some_required_client", files.client);
    }

    #[test]
    fn endpoint_with_errors() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
    error {
        ValidationError(400)
        Conflict(409)
    }
}
"#,
        );
        insta::assert_snapshot!("endpoint_with_errors_types", files.types);
        insta::assert_snapshot!("endpoint_with_errors_client", files.client);
    }

    #[test]
    fn void_response() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint deleteUser: DELETE "/api/users/{id}" {
}
"#,
        );
        insta::assert_snapshot!("void_response_client", files.client);
        insta::assert_snapshot!("void_response_handlers", files.handlers);
    }

    #[test]
    fn list_response_type() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint listUsers: GET "/api/users" {
    response List<User>
}
"#,
        );
        // Should import User (not List) from types
        insta::assert_snapshot!("list_response_client", files.client);
    }

    #[test]
    fn multiple_endpoints() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint listUsers: GET "/api/users" {
    response List<User>
}
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
endpoint getUser: GET "/api/users/{id}" {
    response User
}
endpoint deleteUser: DELETE "/api/users/{id}" {
}
"#,
        );
        insta::assert_snapshot!("multiple_endpoints_types", files.types);
        insta::assert_snapshot!("multiple_endpoints_client", files.client);
        insta::assert_snapshot!("multiple_endpoints_handlers", files.handlers);
    }

    #[test]
    fn doc_comments_passthrough() {
        let files = generate_from_source(
            r#"
/** A registered user */
struct User { Int id  String name }
/** Create a new user */
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
"#,
        );
        insta::assert_snapshot!("doc_comments_types", files.types);
        insta::assert_snapshot!("doc_comments_client", files.client);
        insta::assert_snapshot!("doc_comments_handlers", files.handlers);
    }

    #[test]
    fn selective_partial() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email  Int age }
endpoint patchUser: PATCH "/api/users/{id}" {
    body User omit { id } partial { email, age }
    response User
}
"#,
        );
        insta::assert_snapshot!("selective_partial_types", files.types);
    }

    // ── Edge case tests ─────────────────────────────────────────────

    /// Minimal endpoint: no body, no response, no query, no errors.
    #[test]
    fn minimal_endpoint() {
        let files = generate_from_source(
            r#"
endpoint healthCheck: GET "/api/health" {
}
"#,
        );
        insta::assert_snapshot!("minimal_endpoint_client", files.client);
        insta::assert_snapshot!("minimal_endpoint_handlers", files.handlers);
    }

    /// Enum used as response type.
    #[test]
    fn enum_response_type() {
        let files = generate_from_source(
            r#"
enum Status { Active  Inactive  Banned }
endpoint getStatus: GET "/api/status" {
    response Status
}
"#,
        );
        insta::assert_snapshot!("enum_response_client", files.client);
        insta::assert_snapshot!("enum_response_handlers", files.handlers);
    }

    /// `pick` modifier without `omit`.
    #[test]
    fn body_pick_only() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email  Int age }
endpoint updateEmail: PATCH "/api/users/{id}/email" {
    body User pick { email }
    response User
}
"#,
        );
        insta::assert_snapshot!("body_pick_only_types", files.types);
        insta::assert_snapshot!("body_pick_only_client", files.client);
    }

    /// Endpoint with multiple path parameters.
    #[test]
    fn multiple_path_params() {
        let files = generate_from_source(
            r#"
struct Comment { Int id  String text }
endpoint getComment: GET "/api/users/{userId}/posts/{postId}" {
    response Comment
}
"#,
        );
        insta::assert_snapshot!("multiple_path_params_client", files.client);
        insta::assert_snapshot!("multiple_path_params_handlers", files.handlers);
    }

    /// `Option<User>` response type.
    #[test]
    fn option_response_type() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint findUser: GET "/api/users/{id}" {
    response Option<User>
}
"#,
        );
        insta::assert_snapshot!("option_response_client", files.client);
    }

    /// `Map<String, User>` response type.
    #[test]
    fn map_response_type() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint getUserMap: GET "/api/users/map" {
    response Map<String, User>
}
"#,
        );
        insta::assert_snapshot!("map_response_client", files.client);
    }

    /// Query params with a required (no default, non-optional) param.
    #[test]
    fn query_required_param() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint searchUsers: GET "/api/users/search" {
    query {
        String term
        Int page = 1
    }
    response List<User>
}
"#,
        );
        insta::assert_snapshot!("query_required_param_client", files.client);
        insta::assert_snapshot!("query_required_param_handlers", files.handlers);
    }

    /// Single error variant (not multiple).
    #[test]
    fn single_error_variant() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint getUser: GET "/api/users/{id}" {
    response User
    error { NotFound(404) }
}
"#,
        );
        insta::assert_snapshot!("single_error_types", files.types);
        insta::assert_snapshot!("single_error_client", files.client);
    }

    /// Endpoint with body but no response.
    #[test]
    fn body_no_response() {
        let files = generate_from_source(
            r#"
struct Feedback { String message  Int rating }
endpoint submitFeedback: POST "/api/feedback" {
    body Feedback
}
"#,
        );
        insta::assert_snapshot!("body_no_response_client", files.client);
        insta::assert_snapshot!("body_no_response_handlers", files.handlers);
    }

    /// Struct with `Option<T>` fields generates optional properties in the interface.
    #[test]
    fn struct_with_optional_fields() {
        let files = generate_from_source(
            r#"
struct Profile {
    Int id
    String name
    Option<String> bio
    Option<Int> age
}
"#,
        );
        insta::assert_snapshot!("struct_optional_fields_types", files.types);
    }

    // ── server.ts tests ─────────────────────────────────────────────

    /// Server router for a GET endpoint with path params.
    #[test]
    fn server_get_with_path_param() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint getUser: GET "/api/users/{id}" {
    response User
}
"#,
        );
        insta::assert_snapshot!("server_get_path_param", files.server);
    }

    /// Server router for a POST endpoint with body and errors.
    #[test]
    fn server_post_with_body_and_errors() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
    error {
        ValidationError(400)
        Conflict(409)
    }
}
"#,
        );
        insta::assert_snapshot!("server_post_body_errors", files.server);
    }

    /// Server router for a GET endpoint with query params and defaults.
    #[test]
    fn server_get_with_query_params() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint listUsers: GET "/api/users" {
    query {
        Int page = 1
        Int limit = 20
        Option<String> search
    }
    response List<User>
}
"#,
        );
        insta::assert_snapshot!("server_get_query_params", files.server);
    }

    /// Server router for a DELETE endpoint (void response).
    #[test]
    fn server_delete_void() {
        let files = generate_from_source(
            r#"
endpoint deleteUser: DELETE "/api/users/{id}" {
    error { NotFound(404) }
}
"#,
        );
        insta::assert_snapshot!("server_delete_void", files.server);
    }

    /// Server router with multiple endpoints.
    #[test]
    fn server_multiple_endpoints() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint listUsers: GET "/api/users" {
    response List<User>
}
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
endpoint getUser: GET "/api/users/{id}" {
    response User
}
endpoint deleteUser: DELETE "/api/users/{id}" {
}
"#,
        );
        insta::assert_snapshot!("server_multiple_endpoints", files.server);
    }

    /// Server router for PATCH endpoint with body + path param.
    #[test]
    fn server_patch_with_body() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email  Int age }
endpoint updateUser: PATCH "/api/users/{id}" {
    body User omit { id } partial
    response User
    error { NotFound(404) }
}
"#,
        );
        insta::assert_snapshot!("server_patch_body", files.server);
    }

    /// Server router for endpoint with both query params and body.
    #[test]
    fn server_query_and_body() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name  String email }
endpoint createUser: POST "/api/users" {
    query { Bool notify = false }
    body User omit { id }
    response User
}
"#,
        );
        insta::assert_snapshot!("server_query_and_body", files.server);
    }

    /// Server router for endpoint with multiple path params.
    #[test]
    fn server_multiple_path_params() {
        let files = generate_from_source(
            r#"
struct Comment { Int id  String text }
endpoint getComment: GET "/api/users/{userId}/posts/{postId}" {
    response Comment
}
"#,
        );
        insta::assert_snapshot!("server_multiple_path_params", files.server);
    }

    /// Server router for endpoint with string and bool query defaults.
    #[test]
    fn server_string_and_bool_defaults() {
        let files = generate_from_source(
            r#"
struct Item { Int id  String name }
endpoint listItems: GET "/api/items" {
    query {
        String sort = "name"
        Bool ascending = true
        Int limit = 50
    }
    response List<Item>
}
"#,
        );
        insta::assert_snapshot!("server_string_bool_defaults", files.server);
    }

    /// Server for minimal endpoint (no body/query/response/errors).
    #[test]
    fn server_minimal_endpoint() {
        let files = generate_from_source(
            r#"
endpoint healthCheck: GET "/api/health" {
}
"#,
        );
        insta::assert_snapshot!("server_minimal_endpoint", files.server);
    }

    // ── Where constraint codegen tests ──────────────────────────────

    /// Validation function generated for endpoint with constrained body fields.
    #[test]
    fn validation_function_numeric_and_string() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String name where self.length > 0 && self.length <= 100
    Int age where self >= 0 && self <= 150
}
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
"#,
        );
        insta::assert_snapshot!("validation_numeric_string_types", files.types);
    }

    /// Validation function with `self.contains()` constraint.
    #[test]
    fn validation_function_contains() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String email where self.contains("@") && self.length > 3
}
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
"#,
        );
        insta::assert_snapshot!("validation_contains_types", files.types);
    }

    /// Server.ts calls validation function when body has constraints.
    #[test]
    fn server_calls_validation() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String name where self.length > 0
    Int age where self >= 0
}
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
"#,
        );
        insta::assert_snapshot!("server_with_validation", files.server);
    }

    /// No validation function when body has no constraints.
    #[test]
    fn no_validation_without_constraints() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
"#,
        );
        assert!(
            !files.types.contains("validate"),
            "should not emit validation function when no constraints"
        );
    }

    /// Validation function with `or` constraint.
    #[test]
    fn validation_or_constraint() {
        let files = generate_from_source(
            r#"
struct Range { Int id  Int x where self < 0 || self > 100 }
endpoint create: POST "/api/ranges" {
    body Range omit { id }
    response Range
}
"#,
        );
        insta::assert_snapshot!("validation_or_types", files.types);
    }

    /// Validation with optional field (partial) that has constraint.
    #[test]
    fn validation_optional_constrained_field() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String name where self.length > 0
    Int age where self >= 0
}
endpoint updateUser: PATCH "/api/users/{id}" {
    body User omit { id } partial
    response User
}
"#,
        );
        insta::assert_snapshot!("validation_optional_types", files.types);
    }

    /// Multiple endpoints with constraints — only one ValidationError class.
    #[test]
    fn validation_single_error_class() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name where self.length > 0 }
struct Item { Int id  Int price where self > 0 }
endpoint createUser: POST "/api/users" {
    body User omit { id }
    response User
}
endpoint createItem: POST "/api/items" {
    body Item omit { id }
    response Item
}
"#,
        );
        let count = files.types.matches("class ValidationError").count();
        assert_eq!(
            count, 1,
            "ValidationError class should be emitted exactly once"
        );
        assert!(files.types.contains("validateCreateUserBody"));
        assert!(files.types.contains("validateCreateItemBody"));
    }

    // ── Struct-level validation tests ──────────────────────────────

    /// Struct-level validate function for constrained fields.
    #[test]
    fn struct_validation_numeric_and_string() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String name where self.length > 0 && self.length <= 100
    Int age where self >= 0 && self <= 150
}
"#,
        );
        insta::assert_snapshot!("struct_validation_types", files.types);
    }

    /// Struct-level validate function with `contains` constraint.
    #[test]
    fn struct_validation_contains() {
        let files = generate_from_source(
            r#"
struct User {
    Int id
    String email where self.contains("@") && self.length > 3
}
"#,
        );
        insta::assert_snapshot!("struct_validation_contains_types", files.types);
    }

    /// No struct-level validation when no fields have constraints.
    #[test]
    fn no_struct_validation_without_constraints() {
        let files = generate_from_source(
            r#"
struct User { Int id  String name }
"#,
        );
        assert!(
            !files.types.contains("validateUser"),
            "should not emit struct validation function when no constraints"
        );
    }

    // ── dyn Trait handling ───────────────────────────────────────────

    /// `dyn Trait` erases to the trait name on the TypeScript side —
    /// structural interface dispatch handles the runtime variance.
    #[test]
    fn dyn_type_erases_to_trait_name() {
        use phoenix_sema::types::Type;
        assert_eq!(type_to_ts(&Type::Dyn("Drawable".to_string())), "Drawable");
    }

    /// End-to-end: a parser-level `TypeExpr::Dyn` erases to the trait
    /// name at the parser-expr codegen site too (exercises
    /// `type_expr_to_ts`, not just `type_to_ts`).
    #[test]
    fn dyn_type_expr_erases_to_trait_name() {
        use phoenix_common::span::Span;
        use phoenix_parser::ast::{DynType, TypeExpr};
        let te = TypeExpr::Dyn(DynType {
            trait_name: "Drawable".to_string(),
            span: Span::BUILTIN,
        });
        assert_eq!(type_expr_to_ts(&te), "Drawable");
    }
}
