//! TypeScript code generation for Phoenix Gen.
//!
//! Generates four files from a Phoenix program:
//! - **types.ts** — TypeScript interfaces for structs, string unions for enums,
//!   derived type aliases for endpoint body types, and error type definitions.
//! - **client.ts** — a fetch-based client SDK with typed async functions for
//!   each endpoint, including query parameter handling and typed error responses.
//! - **handlers.ts** — a `Handlers` interface that server implementations must
//!   satisfy, with typed method signatures for each endpoint.
//! - **server.ts** — an Express-compatible router that wires HTTP routes to
//!   handler methods with automatic parameter parsing and error mapping.

use std::collections::BTreeSet;

use phoenix_parser::ast::{Declaration, EnumDecl, PaginationMode, Program, StructDecl, TypeExpr};
use phoenix_sema::Analysis;
use phoenix_sema::checker::{DefaultValue, EndpointInfo, ResolvedDerivedType};
use phoenix_sema::types::Type;

mod format;
use format::*;

/// The output of TypeScript code generation: four file contents.
pub struct GeneratedFiles {
    /// Content for `types.ts` — interfaces, enums, derived types, error types.
    pub types: String,
    /// Content for `client.ts` — fetch-based client SDK.
    pub client: String,
    /// Content for `handlers.ts` — server handler interface.
    pub handlers: String,
    /// Content for `server.ts` — Express-compatible router wiring.
    pub server: String,
}

/// Generates TypeScript code from a parsed and type-checked Phoenix program.
///
/// Iterates over declarations in source order to produce deterministic,
/// diff-friendly output.
pub fn generate_typescript(program: &Program, check_result: &Analysis) -> GeneratedFiles {
    let generator = TsGenerator::new(check_result);
    generator.generate(program)
}

/// Internal TypeScript code generator.
///
/// Accumulates generated code for `types.ts`, `client.ts`, `handlers.ts`,
/// and `server.ts` in separate string buffers, using the semantic analysis
/// results to resolve types and build correct signatures.
struct TsGenerator<'a> {
    /// Semantic analysis results providing resolved types, struct info, and
    /// endpoint definitions.
    check_result: &'a Analysis,
    /// Accumulated output for `types.ts`.
    types_out: String,
    /// Accumulated output for `client.ts`.
    client_out: String,
    /// Accumulated output for `handlers.ts`.
    handlers_out: String,
    /// Accumulated output for `server.ts`.
    server_out: String,
    /// Tracks which derived type names have been emitted to avoid duplicates.
    emitted_derived_types: BTreeSet<String>,
    /// Whether the `ValidationError` class has been emitted.
    emitted_validation_error: bool,
}

impl<'a> TsGenerator<'a> {
    /// Creates a new TypeScript generator with the given semantic analysis results.
    fn new(check_result: &'a Analysis) -> Self {
        Self {
            check_result,
            types_out: String::new(),
            client_out: String::new(),
            handlers_out: String::new(),
            server_out: String::new(),
            emitted_derived_types: BTreeSet::new(),
            emitted_validation_error: false,
        }
    }

    /// Generates TypeScript `types.ts`, `client.ts`, and `handlers.ts` from the
    /// program AST.
    fn generate(mut self, program: &Program) -> GeneratedFiles {
        // Generate types.ts
        self.types_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");

        for decl in &program.declarations {
            match decl {
                // A file-bearing (body-only) struct never appears as a normal TS
                // value: as a multipart request body it is exploded into the
                // derived `<Endpoint>Body` (its `File` fields read off a
                // `Record<string, Blob>`), and as a binary response it is streamed
                // as a `Buffer`/`Blob`. Emitting a bare `interface` for it would be
                // dead, exported surface, so skip it — matching the Go/Python
                // generators, which likewise skip the file-bearing base struct.
                Declaration::Struct(s) if self.struct_is_file_bearing(&s.name) => {}
                Declaration::Struct(s) => self.emit_struct(s),
                Declaration::Enum(e) => self.emit_enum(e),
                _ => {}
            }
        }

        // Emit struct-level validation functions (skip file-bearing structs: no
        // interface is emitted for them, and their constraints are validated on
        // the derived body path, not here).
        for decl in &program.declarations {
            if let Declaration::Struct(s) = decl
                && !self.struct_is_file_bearing(&s.name)
            {
                self.emit_struct_validation(s);
            }
        }

        // Emit derived types and error types for endpoints
        for ep in &self.check_result.endpoints {
            self.emit_endpoint_derived_type(ep);
        }
        for ep in &self.check_result.endpoints {
            self.emit_endpoint_result_type(ep);
        }
        for ep in &self.check_result.endpoints {
            self.emit_endpoint_page_type(ep);
        }
        for ep in &self.check_result.endpoints {
            self.emit_endpoint_response_type(ep);
        }
        for ep in &self.check_result.endpoints {
            self.emit_endpoint_error_types(ep);
        }

        // Emit validation functions for endpoints with constrained body fields
        for ep in &self.check_result.endpoints {
            self.emit_validation_function(ep);
        }

        // Generate client.ts
        self.client_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");
        self.emit_client_imports();
        self.emit_client_preamble();

        for (i, ep) in self.check_result.endpoints.iter().enumerate() {
            // One blank line between methods (none before the first).
            if i > 0 {
                self.client_out.push('\n');
            }
            self.emit_client_function(ep);
        }

        // Close the `api` object literal (assigned to a const → needs `;`).
        self.client_out.push_str("};\n");

        // Generate handlers.ts
        self.handlers_out
            .push_str("// Generated by Phoenix Gen — implement the handler methods below.\n\n");
        self.emit_handler_imports();
        self.handlers_out.push_str("export interface Handlers {\n");

        for ep in &self.check_result.endpoints {
            self.emit_handler_method(ep);
        }

        self.handlers_out.push_str("}\n");

        // Generate server.ts (Express-compatible router)
        self.server_out
            .push_str("// Generated by Phoenix Gen — do not edit manually.\n\n");
        self.emit_server_imports();
        self.emit_server_router();

        GeneratedFiles {
            types: finalize(self.types_out),
            client: finalize(self.client_out),
            handlers: finalize(self.handlers_out),
            server: finalize(self.server_out),
        }
    }

    // ── Type emission ────────────────────────────────────────────────

    /// Whether the named struct is file-bearing (body-only): it has a direct
    /// `File`/`Option<File>` field and so is legal only in endpoint
    /// `body`/`response` position. Such a struct emits no standalone interface or
    /// validator (see the type-emission loop in `generate`).
    fn struct_is_file_bearing(&self, name: &str) -> bool {
        self.check_result
            .module
            .struct_info_by_name(name)
            .is_some_and(|si| si.is_file_bearing)
    }

    /// Emits a TypeScript `export interface` for a Phoenix struct.
    fn emit_struct(&mut self, s: &StructDecl) {
        if let Some(ref doc) = s.doc_comment {
            self.types_out.push_str(&render_jsdoc("", doc));
        }
        self.types_out
            .push_str(&format!("export interface {} {{\n", s.name));

        if let Some(info) = self.check_result.module.struct_info_by_name(&s.name) {
            for f in &info.fields {
                let ts_type = type_to_ts(&f.ty);
                let optional = matches!(&f.ty, Type::Generic(name, _) if name == "Option");
                if optional {
                    self.types_out
                        .push_str(&format!("  {}?: {};\n", f.name, ts_type));
                } else {
                    self.types_out
                        .push_str(&format!("  {}: {};\n", f.name, ts_type));
                }
            }
        }

        self.types_out.push_str("}\n\n");
    }

    /// Emits a `validate{StructName}` function for a struct with constrained fields.
    fn emit_struct_validation(&mut self, s: &StructDecl) {
        let Some(info) = self.check_result.module.struct_info_by_name(&s.name) else {
            return;
        };
        if !info.fields.iter().any(|f| f.constraint.is_some()) {
            return;
        }

        // Emit ValidationError class once
        if !self.emitted_validation_error {
            self.types_out
                .push_str("export class ValidationError extends Error {\n");
            self.types_out
                .push_str("  constructor(message: string) {\n");
            self.types_out.push_str("    super(message);\n");
            self.types_out
                .push_str("    this.name = \"ValidationError\";\n");
            self.types_out.push_str("  }\n");
            self.types_out.push_str("}\n\n");
            self.emitted_validation_error = true;
        }

        emit_validate_signature(&mut self.types_out, &s.name);
        let vfields: Vec<ValidationField> = info
            .fields
            .iter()
            .map(|f| validation_field(&f.name, &f.ty, f.constraint.as_ref(), false))
            .collect();
        emit_validation_body(&mut self.types_out, &vfields);

        self.types_out
            .push_str(&format!("  return obj as unknown as {};\n", s.name));
        self.types_out.push_str("}\n\n");
    }

    /// Emits a TypeScript string union type for a Phoenix enum (simple variants only).
    fn emit_enum(&mut self, e: &EnumDecl) {
        if let Some(ref doc) = e.doc_comment {
            self.types_out.push_str(&render_jsdoc("", doc));
        }

        let all_unit = e.variants.iter().all(|v| v.fields.is_empty());
        if all_unit {
            // Simple enum → string union
            let variants: Vec<String> = e
                .variants
                .iter()
                .map(|v| format!("\"{}\"", v.name))
                .collect();
            emit_union_type_alias(&mut self.types_out, &e.name, &variants);
        } else {
            // Tagged union → discriminated union of `{ tag; value }` objects.
            // Routed through `emit_union_type_alias` so the members get the same
            // Prettier-correct layout as string unions (one line if it fits, else
            // a leading-`|` member per line) and a `;` terminator.
            let members: Vec<String> = e
                .variants
                .iter()
                .map(|v| {
                    if v.fields.is_empty() {
                        format!("{{ tag: \"{}\" }}", v.name)
                    } else if v.fields.len() == 1 {
                        let ts = type_expr_to_ts(&v.fields[0]);
                        format!("{{ tag: \"{}\"; value: {} }}", v.name, ts)
                    } else {
                        let ts: Vec<String> = v.fields.iter().map(type_expr_to_ts).collect();
                        format!("{{ tag: \"{}\"; value: [{}] }}", v.name, ts.join(", "))
                    }
                })
                .collect();
            emit_union_type_alias(&mut self.types_out, &e.name, &members);
        }
    }

    /// Emits a derived type alias for an endpoint body (e.g., `Omit<User, "id">`).
    fn emit_endpoint_derived_type(&mut self, ep: &EndpointInfo) {
        let Some(ref body) = ep.body else { return };
        let type_name = format!("{}Body", capitalize(&ep.name));

        if !self.emitted_derived_types.insert(type_name.clone()) {
            return;
        }

        let ts_type = derived_type_to_ts(body);
        self.types_out
            .push_str(&format!("export type {} = {};\n\n", type_name, ts_type));
    }

    /// Emits the response-header envelope type for an endpoint that declares
    /// response headers (e.g. `interface GetPostResult { body: Post;
    /// ratelimitRemaining: number; }`). Endpoints without response headers emit
    /// nothing here and keep returning their bare response type.
    fn emit_endpoint_result_type(&mut self, ep: &EndpointInfo) {
        if ep.response_headers.is_empty() {
            return;
        }
        let name = result_type_name(ep);
        let body_type = ep
            .response
            .as_ref()
            .map(type_to_ts)
            .unwrap_or_else(|| "void".to_string());

        self.types_out
            .push_str(&format!("export interface {name} {{\n"));
        self.types_out.push_str(&format!("  body: {body_type};\n"));
        for h in &ep.response_headers {
            let ts_ty = type_to_ts(&h.ty);
            if is_header_option(h) {
                self.types_out
                    .push_str(&format!("  {}?: {};\n", h.name, ts_ty));
            } else {
                self.types_out
                    .push_str(&format!("  {}: {};\n", h.name, ts_ty));
            }
        }
        self.types_out.push_str("}\n\n");
    }

    /// Emits the pagination envelope type for an endpoint that declares a
    /// `pagination { }` block. The envelope wraps the bare `List<T>` response in
    /// a typed page object with mode-specific metadata:
    /// - **offset** → `interface ListPostsPage { items: Post[]; totalCount: number; }`
    /// - **cursor** → `interface ListPostsPage { items: Post[]; nextCursor?: string; }`
    ///
    /// Endpoints without pagination emit nothing here and keep returning their
    /// bare response type. Pagination and response headers are mutually exclusive
    /// (sema rejects the combination), so this never collides with the
    /// `<Endpoint>Result` envelope.
    fn emit_endpoint_page_type(&mut self, ep: &EndpointInfo) {
        let Some(ref pag) = ep.pagination else {
            return;
        };
        let name = page_type_name(ep);
        let item_type = type_to_ts(&pag.item_type);

        self.types_out
            .push_str(&format!("export interface {name} {{\n"));
        self.types_out
            .push_str(&format!("  items: {item_type}[];\n"));
        match pag.mode {
            PaginationMode::Offset => {
                self.types_out.push_str("  totalCount: number;\n");
            }
            // `nextCursor` is null/absent on the last page — render it optional,
            // matching how the response-header envelope renders an optional field.
            PaginationMode::Cursor => {
                self.types_out.push_str("  nextCursor?: string;\n");
            }
        }
        self.types_out.push_str("}\n\n");
    }

    /// Emits the multi-status envelope type for an endpoint that declares a
    /// `response { }` block (`response_statuses` non-empty). The handler returns,
    /// and the client observes, this envelope instead of the bare body:
    /// ```typescript
    /// export interface UpsertUserResponse {
    ///   status: number;
    ///   body?: User;
    /// }
    /// ```
    /// - `status` is the actual HTTP status (handler sets it, server writes it,
    ///   client reads it).
    /// - `body?: T` is the shared body type as an optional field, present only when
    ///   the block declares at least one typed status (`ep.response` is `Some`). An
    ///   all-typeless block (e.g. `response { 202  204 }`) has no `T`, so the
    ///   envelope is just `{ status: number }` with no `body` field.
    ///
    /// Endpoints without a `response { }` block emit nothing here and keep
    /// returning their bare response type unchanged.
    fn emit_endpoint_response_type(&mut self, ep: &EndpointInfo) {
        if ep.response_statuses.is_empty() {
            return;
        }
        let name = multi_status_type_name(ep);
        self.types_out
            .push_str(&format!("export interface {name} {{\n"));
        self.types_out.push_str("  status: number;\n");
        if let Some(ref resp) = ep.response {
            let body_type = type_to_ts(resp);
            self.types_out.push_str(&format!("  body?: {body_type};\n"));
        }
        self.types_out.push_str("}\n\n");
    }

    /// Emits error type definitions for an endpoint's error variants.
    ///
    /// For an endpoint with `error { NotFound(404), Conflict(409) }`, produces:
    /// ```typescript
    /// export type CreateUserError = "NotFound" | "Conflict";
    /// export const CreateUserErrors = { NotFound: 404, Conflict: 409 } as const;
    /// ```
    fn emit_endpoint_error_types(&mut self, ep: &EndpointInfo) {
        if ep.errors.is_empty() {
            return;
        }

        let type_name = format!("{}Error", capitalize(&ep.name));

        // String union of error variant names
        let variants: Vec<String> = ep
            .errors
            .iter()
            .map(|(name, _)| format!("\"{name}\""))
            .collect();
        emit_union_type_alias(&mut self.types_out, &type_name, &variants);

        // Const object mapping variant names to status codes
        let entries: Vec<String> = ep
            .errors
            .iter()
            .map(|(name, code)| format!("  {name}: {code}"))
            .collect();
        self.types_out.push_str(&format!(
            "export const {}Errors = {{\n{},\n}} as const;\n\n",
            capitalize(&ep.name),
            entries.join(",\n")
        ));
    }

    /// Emits a `ValidationError` class and a typed `validate*Body` function for
    /// an endpoint whose body has at least one constrained field.
    fn emit_validation_function(&mut self, ep: &EndpointInfo) {
        let Some(ref body) = ep.body else { return };
        let has_constraints = body.fields.iter().any(|f| f.constraint.is_some());
        if !has_constraints {
            return;
        }

        // Emit ValidationError class once
        if !self.emitted_validation_error {
            self.types_out
                .push_str("export class ValidationError extends Error {\n");
            self.types_out
                .push_str("  constructor(message: string) {\n");
            self.types_out.push_str("    super(message);\n");
            self.types_out
                .push_str("    this.name = \"ValidationError\";\n");
            self.types_out.push_str("  }\n");
            self.types_out.push_str("}\n\n");
            self.emitted_validation_error = true;
        }

        let type_name = format!("{}Body", capitalize(&ep.name));
        emit_validate_signature(&mut self.types_out, &type_name);
        let vfields: Vec<ValidationField> = body
            .fields
            .iter()
            .map(|f| validation_field(&f.name, &f.ty, f.constraint.as_ref(), f.optional))
            .collect();
        emit_validation_body(&mut self.types_out, &vfields);

        self.types_out
            .push_str(&format!("  return obj as unknown as {};\n", type_name));
        self.types_out.push_str("}\n\n");
    }

    // ── Client emission ──────────────────────────────────────────────

    /// Emits import statements for the client file, collecting all user-defined
    /// type names referenced by endpoint signatures.
    fn emit_client_imports(&mut self) {
        let mut type_imports = BTreeSet::new();

        for ep in &self.check_result.endpoints {
            if ep.body.is_some() {
                type_imports.insert(format!("{}Body", capitalize(&ep.name)));
            }
            if !ep.response_headers.is_empty() {
                // The method returns the envelope type, so import it — AND fall
                // through to import the bare body type too: the client still
                // casts the decoded JSON to it (`(await response.json()) as
                // <Body>`) before wrapping it in the envelope, so both names are
                // referenced in this file.
                type_imports.insert(result_type_name(ep));
            }
            if ep.pagination.is_some() {
                // The method returns (and casts the decoded JSON to) the page
                // envelope. The bare item type is NOT referenced in the client
                // (the response below is read as the whole page object), so the
                // `collect_import_names` on the `List<T>` response is skipped for
                // paginated endpoints — import only the page type here.
                type_imports.insert(page_type_name(ep));
            }
            if !ep.response_statuses.is_empty() {
                // The method returns the `<Endpoint>Response` envelope, so import
                // it — AND fall through to import the bare body type below: the
                // client still casts the parsed JSON to it
                // (`JSON.parse(responseText) as <T>`) before wrapping it in the
                // envelope's `body`, so both names are referenced here.
                type_imports.insert(multi_status_type_name(ep));
            }
            // A binary-download response is returned as a `Blob`, so the response
            // struct's name is never referenced in the client — don't import it.
            // A paginated response is read as the page envelope (imported above);
            // the bare `List<T>` element type is not referenced — skip it too.
            if !ep.response_is_binary
                && ep.pagination.is_none()
                && let Some(ref resp) = ep.response
            {
                collect_import_names(resp, &mut type_imports);
            }
        }

        if !type_imports.is_empty() {
            let joined: Vec<_> = type_imports.into_iter().collect();
            emit_import(&mut self.client_out, "import type", &joined, "./types");
            self.client_out.push('\n');
        }
    }

    /// Emits the client preamble: `ApiError` class (if needed), base URL
    /// configuration, and the opening of the `api` object.
    fn emit_client_preamble(&mut self) {
        // Emit ApiError class if any endpoint has error variants
        let has_errors = self
            .check_result
            .endpoints
            .iter()
            .any(|ep| !ep.errors.is_empty());
        if has_errors {
            self.client_out
                .push_str("export class ApiError extends Error {\n");
            self.client_out.push_str("  constructor(\n");
            self.client_out
                .push_str("    public readonly code: string,\n");
            self.client_out
                .push_str("    public readonly status: number,\n");
            self.client_out
                .push_str("    public readonly body: string,\n");
            self.client_out.push_str("  ) {\n");
            self.client_out
                .push_str("    super(`${code} (${String(status)}): ${body}`);\n");
            self.client_out.push_str("    this.name = \"ApiError\";\n");
            self.client_out.push_str("  }\n");
            self.client_out.push_str("}\n\n");
        }

        self.client_out.push_str("export let baseUrl = \"\";\n\n");
        self.client_out
            .push_str("export function setBaseUrl(url: string): void {\n");
        self.client_out.push_str("  baseUrl = url;\n");
        self.client_out.push_str("}\n\n");
        self.client_out.push_str("export const api = {\n");
    }

    /// Emits a single async client function for an endpoint, including query
    /// parameter construction, body serialization, and typed error handling.
    fn emit_client_function(&mut self, ep: &EndpointInfo) {
        let method = ep.method.as_upper_str();
        let has_resp_headers = !ep.response_headers.is_empty();
        let body_type = ep
            .response
            .as_ref()
            .map(type_to_ts)
            .unwrap_or_else(|| "void".to_string());
        // The method's declared return type: the bare body when there are no
        // response headers (the common case, unchanged), otherwise the typed
        // envelope bundling the body + each response header. A binary-download
        // response (a single-`File` response struct) is read as a `Blob`.
        let is_multi_status = !ep.response_statuses.is_empty();
        let response_type = if ep.response_is_binary {
            "Blob".to_string()
        } else if has_resp_headers {
            result_type_name(ep)
        } else if ep.pagination.is_some() {
            // The bare `List<T>` response is wrapped in the typed page envelope;
            // the client reads the whole page object from the JSON body.
            page_type_name(ep)
        } else if is_multi_status {
            // The bare body is wrapped in the `<Endpoint>Response` envelope
            // carrying the observed status + optional parsed body.
            multi_status_type_name(ep)
        } else {
            body_type.clone()
        };
        let has_query = !ep.query_params.is_empty();
        let has_req_headers = !ep.headers.is_empty();
        // The request-header object param is nullable (`headers?:`) only when
        // EVERY request header is client-optional (default or `Option<T>`); a
        // single required header makes it `headers:`. Mirrors `opts_nullable`.
        let req_headers_nullable = ep.headers.iter().all(is_header_client_optional);
        // `opts` is nullable (`opts?:`) only when EVERY query param is optional; a
        // single required param makes it `opts:`. Computed once here so the
        // signature prefix and the per-param `params.set` access logic below can
        // never disagree about whether `opts` may be undefined.
        let opts_nullable = ep.query_params.iter().all(is_query_param_optional);

        // Build function parameters
        let mut params: Vec<Param> = Vec::new();
        for pp in &ep.path_params {
            params.push(Param::Simple(format!("{pp}: string")));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(Param::Simple(format!("body: {body_type}")));
        }
        if has_query {
            let fields: Vec<String> = ep
                .query_params
                .iter()
                .map(|qp| {
                    let ts_ty = type_to_ts(&qp.ty);
                    if is_query_param_optional(qp) {
                        format!("{}?: {}", qp.name, ts_ty)
                    } else {
                        format!("{}: {}", qp.name, ts_ty)
                    }
                })
                .collect();
            // A fully-optional query bag renders as `opts: {...} = {}` (a default),
            // not `opts?: {...}`. Both are omittable, but a defaulted param — unlike
            // a `?:` one — may legally precede a required parameter, so `opts` keeps
            // its slot ahead of a required `headers` without tripping TS1016.
            params.push(Param::Object {
                prefix: "opts: ".to_string(),
                fields,
                default_empty: opts_nullable,
            });
        }
        if has_req_headers {
            let fields: Vec<String> = ep
                .headers
                .iter()
                .map(|h| {
                    let ts_ty = type_to_ts(&h.ty);
                    if is_header_client_optional(h) {
                        format!("{}?: {}", h.name, ts_ty)
                    } else {
                        format!("{}: {}", h.name, ts_ty)
                    }
                })
                .collect();
            // Same as `opts`: a fully-optional header bag renders as
            // `headers: {...} = {}` (defaulted, omittable) rather than `headers?:`,
            // so it can sit in a stable slot without violating TS1016.
            params.push(Param::Object {
                prefix: "headers: ".to_string(),
                fields,
                default_empty: req_headers_nullable,
            });
        }

        // Doc comment
        if let Some(ref doc) = ep.doc_comment {
            self.client_out.push_str(&render_jsdoc("  ", doc));
        }

        // Function signature
        let head = format!("  async {}", ep.name);
        let tail = format!(": Promise<{response_type}> {{");
        self.client_out
            .push_str(&format_signature(&head, &params, &tail, "  "));

        // Query string construction (only if endpoint has query params)
        if has_query {
            self.client_out
                .push_str("    const params = new URLSearchParams();\n");
            // `opts` is always non-nullable in the emitted client (a fully-optional
            // bag is a `= {}` default, not `opts?:`), so `emit_param_set` only needs
            // each param's own optionality to decide whether to guard with
            // `!== undefined` — it never emits an eslint-flagged redundant chain.
            for qp in &ep.query_params {
                emit_param_set(
                    &mut self.client_out,
                    "    ",
                    &qp.name,
                    is_query_param_optional(qp),
                );
            }
            self.client_out
                .push_str("    const query = params.toString();\n");
        }

        // Build URL with path param substitution
        let url_expr = build_url_expr(&ep.path, &ep.path_params);
        let url_arg = if has_query {
            format!("`${{baseUrl}}{url_expr}${{query ? `?${{query}}` : \"\"}}`")
        } else {
            format!("`${{baseUrl}}{url_expr}`")
        };

        // For a multipart body (a body field is a `File`/`Option<File>`), build a
        // `FormData` BEFORE the fetch call: append each file field (the Blob/File
        // value) and each scalar field (`String(...)`). The runtime sets the
        // multipart boundary on `Content-Type` automatically, so we MUST NOT set
        // Content-Type ourselves (doing so breaks the boundary).
        let body_is_multipart = ep.body_is_multipart;
        if body_is_multipart && let Some(ref ep_body) = ep.body {
            self.client_out
                .push_str("    const formData = new FormData();\n");
            for f in &ep_body.fields {
                emit_form_data_append(&mut self.client_out, "    ", &f.name, &f.ty, f.optional);
            }
        }

        // Build the fetch init object body. When the endpoint declares request
        // headers we build a `Headers` instance (so Content-Type and the typed
        // request headers coexist) and reference it from the init; otherwise the
        // common cases stay byte-for-byte unchanged.
        let mut init_lines: Vec<String> = vec![format!("method: \"{method}\"")];
        if has_req_headers {
            self.client_out
                .push_str("    const requestHeaders = new Headers();\n");
            // Only JSON bodies get an explicit Content-Type; multipart bodies let
            // the runtime set the boundary.
            if ep.body.is_some() && !body_is_multipart {
                self.client_out
                    .push_str("    requestHeaders.set(\"Content-Type\", \"application/json\");\n");
            }
            for h in &ep.headers {
                emit_header_set(
                    &mut self.client_out,
                    "    ",
                    "requestHeaders",
                    &h.name,
                    &h.wire_name,
                    is_header_client_optional(h),
                );
            }
            init_lines.push("headers: requestHeaders".to_string());
            if ep.body.is_some() {
                if body_is_multipart {
                    init_lines.push("body: formData".to_string());
                } else {
                    init_lines.push("body: JSON.stringify(body)".to_string());
                }
            }
        } else if ep.body.is_some() {
            if body_is_multipart {
                init_lines.push("body: formData".to_string());
            } else {
                init_lines.push("headers: { \"Content-Type\": \"application/json\" }".to_string());
                init_lines.push("body: JSON.stringify(body)".to_string());
            }
        }
        emit_fetch_call(&mut self.client_out, "    ", &url_arg, &init_lines);

        // Error handling
        if ep.errors.is_empty() {
            // This thrown path never reads the body, so cancel it before
            // throwing — an unconsumed fetch body holds the underlying
            // connection until GC. The `error { }` branch below needs no
            // cancel: `response.text()` consumes the body. Swallow the cancel
            // result: per the Streams spec, `cancel()` on an already-errored
            // stream returns a REJECTED promise, which would replace the
            // intended status error below with a raw stream error.
            self.client_out.push_str("    if (!response.ok) {\n");
            self.client_out
                .push_str("      await response.body?.cancel().catch(() => undefined);\n");
            self.client_out.push_str(
                "      throw new Error(`${String(response.status)}: ${response.statusText}`);\n",
            );
            self.client_out.push_str("    }\n");
        } else {
            self.client_out.push_str("    if (!response.ok) {\n");
            self.client_out
                .push_str("      const errorBody = await response.text();\n");
            for (name, code) in &ep.errors {
                emit_if_stmt(
                    &mut self.client_out,
                    "      ",
                    &format!("response.status === {code}"),
                    &format!("throw new ApiError(\"{name}\", {code}, errorBody);"),
                );
            }
            self.client_out
                .push_str("      throw new ApiError(\"Unknown\", response.status, errorBody);\n");
            self.client_out.push_str("    }\n");
        }

        // Return. `response.json()` is typed `any`; assert the declared response
        // type so callers get a typed result and strict lint rules (no-unsafe-*)
        // are satisfied.
        if ep.response_is_binary {
            // Binary download: read the raw bytes as a Blob rather than JSON.
            self.client_out
                .push_str("    return await response.blob();\n");
        } else if has_resp_headers {
            // Typed envelope: body read as today, each response header read from
            // the fetch `Response.headers` and coerced into its typed field.
            self.client_out.push_str("    return {\n");
            self.client_out.push_str(&format!(
                "      body: (await response.json()) as {body_type},\n"
            ));
            for h in &ep.response_headers {
                emit_object_property(
                    &mut self.client_out,
                    "      ",
                    &h.name,
                    &response_header_coercion(h),
                );
            }
            self.client_out.push_str("    };\n");
        } else if is_multi_status {
            // Multi-status envelope: record the observed status; parse the body
            // only when the response actually carries one. The guard is on
            // CONTENT, not status code: ANY typeless status (202, 204, ...)
            // sends an empty body, and `response.json()` throws on empty input
            // — so read the text and parse only when non-empty (mirrors the Go
            // client's ContentLength/EOF guard and the Python client's
            // `response.content` check). An all-typeless block has no `T` and
            // emits just the status. The local is named `responseBody` (not
            // `body`) so it never collides with a `body` request-body parameter
            // on the same method.
            if let Some(ref resp) = ep.response {
                let body_type = type_to_ts(resp);
                self.client_out.push_str("    let responseBody: ");
                self.client_out
                    .push_str(&format!("{body_type} | undefined;\n"));
                self.client_out
                    .push_str("    const responseText = await response.text();\n");
                self.client_out.push_str("    if (responseText) {\n");
                self.client_out.push_str(&format!(
                    "      responseBody = JSON.parse(responseText) as {body_type};\n"
                ));
                self.client_out.push_str("    }\n");
                self.client_out
                    .push_str("    return { status: response.status, body: responseBody };\n");
            } else {
                // All-typeless block: status only. Cancel the unread body so the
                // underlying connection is released for reuse immediately (an
                // unconsumed fetch body holds it until GC). Swallow the cancel
                // result: `cancel()` on an already-errored stream rejects, and a
                // post-headers connection drop must not turn a success into a
                // rejection.
                self.client_out
                    .push_str("    await response.body?.cancel().catch(() => undefined);\n");
                self.client_out
                    .push_str("    return { status: response.status };\n");
            }
        } else if response_type != "void" {
            self.client_out.push_str(&format!(
                "    return (await response.json()) as {response_type};\n"
            ));
        } else {
            // No response declared: cancel the unread body so the underlying
            // connection is released for reuse immediately (an unconsumed fetch
            // body holds it until GC). Swallow the cancel result: `cancel()` on
            // an already-errored stream rejects, and a post-headers connection
            // drop must not turn a success into a rejection.
            self.client_out
                .push_str("    await response.body?.cancel().catch(() => undefined);\n");
        }

        self.client_out.push_str("  },\n");
    }

    // ── Handler emission ────────────────────────────────────────────

    /// Emits import statements for the handlers file, collecting all
    /// user-defined type names referenced by handler signatures.
    fn emit_handler_imports(&mut self) {
        let mut imports = BTreeSet::new();

        for ep in &self.check_result.endpoints {
            if ep.body.is_some() {
                imports.insert(format!("{}Body", capitalize(&ep.name)));
            }
            // A binary download handler returns a `Buffer` (a Node global), so
            // the response struct's name is never referenced — skip its import.
            if !ep.response_is_binary {
                if !ep.response_headers.is_empty() {
                    // Handler returns the envelope, which already bundles the body.
                    imports.insert(result_type_name(ep));
                } else if ep.pagination.is_some() {
                    // Handler returns the page envelope (which already bundles the
                    // item type via its `items` field); import only the page type.
                    imports.insert(page_type_name(ep));
                } else if !ep.response_statuses.is_empty() {
                    // Handler returns the `<Endpoint>Response` envelope (which
                    // already bundles the optional body via its `body` field);
                    // import only the envelope type.
                    imports.insert(multi_status_type_name(ep));
                } else if let Some(ref resp) = ep.response {
                    collect_import_names(resp, &mut imports);
                }
            }
        }

        if !imports.is_empty() {
            let joined: Vec<_> = imports.into_iter().collect();
            emit_import(&mut self.handlers_out, "import type", &joined, "./types");
            self.handlers_out.push('\n');
        }
    }

    /// Emits a single method signature in the `Handlers` interface for an
    /// endpoint.
    ///
    /// Handler methods receive path params as individual arguments, body as a
    /// typed parameter, and query params as a required object (the server
    /// framework applies defaults before calling the handler).
    fn emit_handler_method(&mut self, ep: &EndpointInfo) {
        // With response headers the handler resolves the typed envelope; without
        // them it resolves the bare response type (unchanged common case). A
        // binary-download response is produced by the handler as a `Buffer`
        // (Node's idiomatic byte container; the server writes it to the wire).
        let response_type = if ep.response_is_binary {
            "Buffer".to_string()
        } else if !ep.response_headers.is_empty() {
            result_type_name(ep)
        } else if ep.pagination.is_some() {
            // Handler resolves the typed page envelope instead of the bare list;
            // it supplies the metadata (totalCount / nextCursor) Phoenix can't
            // compute.
            page_type_name(ep)
        } else if !ep.response_statuses.is_empty() {
            // Handler resolves the `<Endpoint>Response` envelope, choosing the
            // status code and supplying the optional body.
            multi_status_type_name(ep)
        } else {
            ep.response
                .as_ref()
                .map(type_to_ts)
                .unwrap_or_else(|| "void".to_string())
        };

        let mut params: Vec<Param> = Vec::new();
        for pp in &ep.path_params {
            params.push(Param::Simple(format!("{pp}: string")));
        }
        if ep.body.is_some() {
            let body_type = format!("{}Body", capitalize(&ep.name));
            params.push(Param::Simple(format!("body: {body_type}")));
        }
        if !ep.query_params.is_empty() {
            let fields: Vec<String> = ep
                .query_params
                .iter()
                .map(|qp| {
                    let ts_ty = type_to_ts(&qp.ty);
                    // In handlers, Option<T> fields are optional; others are required
                    // (defaults have been applied by the framework before the handler).
                    let optional = matches!(&qp.ty, Type::Generic(name, _) if name == "Option");
                    if optional {
                        format!("{}?: {}", qp.name, ts_ty)
                    } else {
                        format!("{}: {}", qp.name, ts_ty)
                    }
                })
                .collect();
            params.push(Param::Object {
                prefix: "query: ".to_string(),
                fields,
                default_empty: false,
            });
        }
        if !ep.headers.is_empty() {
            let fields: Vec<String> = ep
                .headers
                .iter()
                .map(|h| {
                    let ts_ty = type_to_ts(&h.ty);
                    // As with query: Option<T> headers are optional; others are
                    // required (the server applies defaults before the handler).
                    if is_header_option(h) {
                        format!("{}?: {}", h.name, ts_ty)
                    } else {
                        format!("{}: {}", h.name, ts_ty)
                    }
                })
                .collect();
            params.push(Param::Object {
                prefix: "headers: ".to_string(),
                fields,
                default_empty: false,
            });
        }

        if let Some(ref doc) = ep.doc_comment {
            self.handlers_out.push_str(&render_jsdoc("  ", doc));
        }
        let head = format!("  {}", ep.name);
        let tail = format!(": Promise<{response_type}>;");
        self.handlers_out
            .push_str(&format_signature(&head, &params, &tail, "  "));
    }
    // ── Server router emission ─────────────────────────────────────

    /// Emits import statements for the server router file, including validation
    /// function imports for endpoints with constrained body types.
    fn emit_server_imports(&mut self) {
        self.server_out
            .push_str("import { Router } from \"express\";\n");
        self.server_out
            .push_str("import type { Request, Response } from \"express\";\n");
        self.server_out
            .push_str("import type { Handlers } from \"./handlers\";\n");

        // Import validation functions for endpoints with constrained bodies. A
        // multipart body skips validate (it is assembled field-by-field from the
        // request), so it never imports the validate function — only its type.
        let mut validate_imports: Vec<String> = Vec::new();
        for ep in &self.check_result.endpoints {
            if let Some(ref body) = ep.body
                && !ep.body_is_multipart
                && body.fields.iter().any(|f| f.constraint.is_some())
            {
                let type_name = format!("{}Body", capitalize(&ep.name));
                validate_imports.push(format!("validate{type_name}"));
            }
        }
        if !validate_imports.is_empty() {
            validate_imports.insert(0, "ValidationError".to_string());
            emit_import(&mut self.server_out, "import", &validate_imports, "./types");
        }

        // Import the body *type* for endpoints whose body is cast/assembled
        // directly (no validate fn supplies it): JSON bodies without constraints
        // (`req.body as XBody`) and every multipart body (`const body: XBody`).
        let mut body_type_imports: Vec<String> = Vec::new();
        for ep in &self.check_result.endpoints {
            if let Some(ref body) = ep.body
                && (ep.body_is_multipart || !body.fields.iter().any(|f| f.constraint.is_some()))
            {
                body_type_imports.push(format!("{}Body", capitalize(&ep.name)));
            }
        }
        if !body_type_imports.is_empty() {
            emit_import(
                &mut self.server_out,
                "import type",
                &body_type_imports,
                "./types",
            );
        }

        self.server_out.push('\n');

        // When any endpoint has a multipart body, emit a minimal interface
        // describing the shape an upstream multipart middleware (multer, busboy,
        // …) adds to the request: parsed scalar fields on `body`, uploaded files
        // as `Blob` values on `files` (keyed by field name). This adds NO runtime
        // dependency — the user mounts the middleware; we only type the contract.
        if self
            .check_result
            .endpoints
            .iter()
            .any(|ep| ep.body_is_multipart)
        {
            self.server_out.push_str(
                "// A multipart middleware (multer, busboy, …) must be mounted upstream; it\n\
                 // populates these fields on the request. Scalar form fields arrive on\n\
                 // `body`; each uploaded file is expected as a `Blob` on `files`, keyed by\n\
                 // field name. NOTE: standard parsers do not produce `Blob`s directly —\n\
                 // multer's memory storage, for example, yields `{ buffer, originalname }`\n\
                 // per field — so mount a tiny adapter that maps each parsed file to a\n\
                 // `Blob`, e.g.:\n\
                 //   const blobFiles: Record<string, Blob> = {};\n\
                 //   for (const [field, parts] of Object.entries(req.files ?? {}))\n\
                 //     blobFiles[field] = new Blob([parts[0].buffer]);\n\
                 //   (req as unknown as MultipartRequest).files = blobFiles;\n\
                 // (The original filename is not carried on a `Blob`; see the project docs.)\n\
                 interface MultipartRequest {\n\
                 \x20 body: Record<string, string>;\n\
                 \x20 files: Record<string, Blob>;\n\
                 }\n\n",
            );
        }
    }

    /// Emits an Express-compatible `createRouter` function that wires each
    /// endpoint to its handler, parsing path/query/body parameters and
    /// mapping errors to HTTP status codes.
    fn emit_server_router(&mut self) {
        self.server_out
            .push_str("export function createRouter(handlers: Handlers): Router {\n");
        self.server_out.push_str("  const router = Router();\n\n");

        // Express matches routes first-registered-wins, so a parametric route
        // (`/api/posts/:id`) registered before a static sibling
        // (`/api/posts/paged`) would shadow it — the static path gets captured as
        // `id = "paged"`. Register more-specific (more-static) routes first so
        // literal segments win, matching the most-specific-wins semantics Go's
        // ServeMux and FastAPI already provide. The sort is stable, so endpoints
        // of equal specificity keep their source order (snapshot-stable).
        let mut ordered: Vec<&EndpointInfo> = self.check_result.endpoints.iter().collect();
        ordered.sort_by_key(|ep| crate::route_specificity_key(&ep.path));

        for ep in ordered {
            self.emit_server_route(ep);
        }

        self.server_out.push_str("  return router;\n");
        self.server_out.push_str("}\n");
    }

    /// Emits a single Express route handler for an endpoint.
    fn emit_server_route(&mut self, ep: &EndpointInfo) {
        let method = ep.method.as_lower_str();

        // Convert Phoenix path params to Express-style: {id} → :id
        let express_path = ep.path.replace('{', ":").replace('}', "");

        // Type the request's path params so `req.params.id` resolves to `string`
        // rather than Express's default `string | string[]`.
        let req_type = if ep.path_params.is_empty() {
            "Request".to_string()
        } else {
            let params = ep
                .path_params
                .iter()
                .map(|pp| format!("{pp}: string"))
                .collect::<Vec<_>>()
                .join("; ");
            format!("Request<{{ {params} }}>")
        };

        // Decide up front whether the `router.X(...)` call stays inline or breaks
        // across lines: a wide `Request<{…}>` (several path params) pushes the
        // opener past the print width. This fixes the arrow body's indentation,
        // so the body is built at its final depth and the width-sensitive
        // emitters (handler call, query coercion) make correct decisions.
        let inline_opener = format!(
            "  router.{method}(\"{express_path}\", async (req: {req_type}, res: Response) => {{"
        );
        let wraps = inline_opener.len() > PRINT_WIDTH;
        // `try`/`catch` indent, statement indent, and nested-block indent. When
        // the call wraps, the whole arrow body sits one level (2 spaces) deeper.
        let ti = if wraps { "      " } else { "    " };
        let si = if wraps { "        " } else { "      " };
        let ni = if wraps { "          " } else { "        " };

        let mut body = String::new();
        body.push_str(&format!("{ti}try {{\n"));

        // Build handler call arguments
        let mut args = Vec::new();

        // Path params: extract from req.params
        for pp in &ep.path_params {
            body.push_str(&format!("{si}const {pp} = req.params.{pp};\n"));
            args.push(pp.clone());
        }

        // Body: parse from req.body, with validation if constraints exist
        if let Some(ref ep_body) = ep.body {
            let type_name = format!("{}Body", capitalize(&ep.name));
            if ep.body_is_multipart {
                // multipart/form-data body. A multipart middleware (multer,
                // busboy, …) must be mounted upstream: it exposes parsed scalar
                // fields on `req.body` and the uploaded files as `Blob` values on
                // `req.files` (keyed by field name). We read against the minimal
                // `MultipartRequest` interface (emitted once below) — no runtime
                // dependency is added; the user wires the middleware.
                body.push_str(&format!(
                    "{si}const multipart = req as unknown as MultipartRequest;\n"
                ));
                body.push_str(&format!("{si}const body: {type_name} = {{\n"));
                for f in &ep_body.fields {
                    emit_object_property(
                        &mut body,
                        &format!("{si}  "),
                        &f.name,
                        &multipart_field_extraction(&f.name, &f.ty, f.optional),
                    );
                }
                body.push_str(&format!("{si}}};\n"));
            } else if ep_body.fields.iter().any(|f| f.constraint.is_some()) {
                body.push_str(&format!(
                    "{si}const body = validate{type_name}(req.body);\n"
                ));
            } else {
                // No constraints to validate, but `req.body` is `any`; cast to
                // the body type so the handler call is type-safe (and strict
                // `no-unsafe-*` lint rules are satisfied).
                body.push_str(&format!("{si}const body = req.body as {type_name};\n"));
            }
            args.push("body".to_string());
        }

        // Query params: extract, coerce, and apply defaults
        if !ep.query_params.is_empty() {
            body.push_str(&format!("{si}const query = {{\n"));
            for qp in &ep.query_params {
                emit_object_property(
                    &mut body,
                    &format!("{si}  "),
                    &qp.name,
                    &query_param_coercion(qp),
                );
            }
            body.push_str(&format!("{si}}};\n"));
            args.push("query".to_string());
        }

        // Request headers: read each from req.header("<wire>"), coerce, apply
        // defaults. express's `req.header()` is case-insensitive, so the exact
        // wire name is safe to pass verbatim.
        if !ep.headers.is_empty() {
            body.push_str(&format!("{si}const headers = {{\n"));
            for h in &ep.headers {
                emit_object_property(
                    &mut body,
                    &format!("{si}  "),
                    &h.name,
                    &request_header_coercion(h),
                );
            }
            body.push_str(&format!("{si}}};\n"));
            args.push("headers".to_string());
        }

        let has_resp_headers = !ep.response_headers.is_empty();

        // Call the handler (breaking the argument list when it overflows).
        if ep.response_is_binary {
            // Binary download: the handler returns a `Buffer`; stream it to the
            // wire with a generic binary content type (the handler may override
            // via response headers in a future slice).
            emit_call_stmt(
                &mut body,
                si,
                &format!("const result = await handlers.{}", ep.name),
                &args,
                ";",
            );
            body.push_str(&format!(
                "{si}res.setHeader(\"Content-Type\", \"application/octet-stream\");\n"
            ));
            body.push_str(&format!("{si}res.send(result);\n"));
        } else if !ep.response_statuses.is_empty() {
            // Multi-status: the handler returns the `<Endpoint>Response` envelope
            // carrying the chosen status + optional body. Write that status (not a
            // hardcoded 200/204), then JSON-encode the body only when present (a
            // typeless status — or an all-typeless block — leaves `result.body`
            // undefined and sends a bodyless response).
            //
            // The handler-chosen envelope is validated against the DECLARED
            // contract first — all three mismatches are handler bugs, reported as
            // a 500 instead of written to the wire (mirrors the Go/Python
            // servers):
            // - an undeclared status (a zero-value envelope would make Express's
            //   `res.status(0)` throw; a 4xx smuggled through the success
            //   envelope would bypass `error { }`);
            // - a body paired with a typeless status (only 204/304 get body
            //   suppression from Express — on e.g. a typeless 202 the body WOULD
            //   hit the wire, and the content-guarded client would parse it,
            //   silently violating the contract);
            // - an undefined body paired with a typed status (the contract — and
            //   the OpenAPI spec — promise a body there).
            // An all-typeless block has no `body` field, so only the membership
            // check applies.
            emit_call_stmt(
                &mut body,
                si,
                &format!("const result = await handlers.{}", ep.name),
                &args,
                ";",
            );
            let declared = ep
                .response_statuses
                .iter()
                .map(|rs| rs.status.to_string())
                .collect::<Vec<_>>()
                .join(", ");
            body.push_str(&format!(
                "{si}if (![{declared}].includes(result.status)) {{\n"
            ));
            emit_500_json(&mut body, ni, "handler returned undeclared status");
            body.push_str(&format!("{ni}return;\n"));
            body.push_str(&format!("{si}}}\n"));
            if ep.response.is_some() {
                let typed = ep
                    .response_statuses
                    .iter()
                    .filter(|rs| rs.ty.is_some())
                    .map(|rs| rs.status.to_string())
                    .collect::<Vec<_>>()
                    .join(", ");
                let typeless = ep
                    .response_statuses
                    .iter()
                    .filter(|rs| rs.ty.is_none())
                    .map(|rs| rs.status.to_string())
                    .collect::<Vec<_>>()
                    .join(", ");
                body.push_str(&format!(
                    "{si}if ([{typed}].includes(result.status) && result.body === undefined) {{\n"
                ));
                emit_500_json(&mut body, ni, "handler returned no body for a typed status");
                body.push_str(&format!("{ni}return;\n"));
                body.push_str(&format!("{si}}}\n"));
                if !typeless.is_empty() {
                    body.push_str(&format!(
                        "{si}if ([{typeless}].includes(result.status) && result.body !== undefined) {{\n"
                    ));
                    emit_500_json(
                        &mut body,
                        ni,
                        "handler returned a body for a bodyless status",
                    );
                    body.push_str(&format!("{ni}return;\n"));
                    body.push_str(&format!("{si}}}\n"));
                    body.push_str(&format!("{si}if (result.body !== undefined) {{\n"));
                    body.push_str(&format!(
                        "{ni}res.status(result.status).json(result.body);\n"
                    ));
                    body.push_str(&format!("{si}}} else {{\n"));
                    body.push_str(&format!("{ni}res.status(result.status).end();\n"));
                    body.push_str(&format!("{si}}}\n"));
                } else {
                    // Every declared status is typed, and the guard above already
                    // rejected an undefined body — so the body is always present
                    // here; a bodyless `.end()` arm would be unreachable.
                    body.push_str(&format!(
                        "{si}res.status(result.status).json(result.body);\n"
                    ));
                }
            } else {
                // All-typeless block: the envelope has no `body` field.
                body.push_str(&format!("{si}res.status(result.status).end();\n"));
            }
        } else if has_resp_headers {
            // Handler returns the envelope: set each response header from the
            // typed field (guard optional), then send the body.
            emit_call_stmt(
                &mut body,
                si,
                &format!("const result = await handlers.{}", ep.name),
                &args,
                ";",
            );
            for h in &ep.response_headers {
                let set_args = vec![
                    format!("\"{}\"", h.wire_name),
                    format!("String(result.{})", h.name),
                ];
                if is_header_option(h) {
                    // Guard the optional header, then emit the (possibly wrapped)
                    // `res.setHeader(...)` call one level deeper.
                    body.push_str(&format!("{si}if (result.{} !== undefined) {{\n", h.name));
                    emit_call_stmt(&mut body, ni, "res.setHeader", &set_args, ";");
                    body.push_str(&format!("{si}}}\n"));
                } else {
                    emit_call_stmt(&mut body, si, "res.setHeader", &set_args, ";");
                }
            }
            body.push_str(&format!("{si}res.json(result.body);\n"));
        } else if ep.response.is_some() {
            emit_call_stmt(
                &mut body,
                si,
                &format!("const result = await handlers.{}", ep.name),
                &args,
                ";",
            );
            body.push_str(&format!("{si}res.json(result);\n"));
        } else {
            emit_call_stmt(
                &mut body,
                si,
                &format!("await handlers.{}", ep.name),
                &args,
                ";",
            );
            body.push_str(&format!("{si}res.status(204).end();\n"));
        }

        // Catch validation errors from constrained bodies
        let has_body_constraints = ep
            .body
            .as_ref()
            .is_some_and(|b| b.fields.iter().any(|f| f.constraint.is_some()));

        // Error handling with status code mapping. The caught binding is only
        // referenced when there are body constraints or declared errors;
        // otherwise use an optional catch binding (`catch {`) so no-unused-vars
        // has nothing to flag.
        if has_body_constraints || !ep.errors.is_empty() {
            body.push_str(&format!("{ti}}} catch (error: unknown) {{\n"));
        } else {
            body.push_str(&format!("{ti}}} catch {{\n"));
        }
        if has_body_constraints {
            emit_guarded_block(
                &mut body,
                si,
                "error instanceof ValidationError",
                &[
                    "res.status(400).json({ error: error.message });".to_string(),
                    "return;".to_string(),
                ],
            );
        }

        if ep.errors.is_empty() {
            body.push_str(&format!(
                "{si}res.status(500).json({{ error: \"Internal Server Error\" }});\n"
            ));
        } else {
            body.push_str(&format!("{si}if (error instanceof Error) {{\n"));
            for (name, code) in &ep.errors {
                emit_guarded_block(
                    &mut body,
                    ni,
                    &format!("error.message === \"{name}\""),
                    &[
                        format!("res.status({code}).json({{ error: \"{name}\" }});"),
                        "return;".to_string(),
                    ],
                );
            }
            body.push_str(&format!("{si}}}\n"));
            body.push_str(&format!(
                "{si}res.status(500).json({{ error: \"Internal Server Error\" }});\n"
            ));
        }
        body.push_str(&format!("{ti}}}\n"));

        // Emit the route. When the inline opener fits, the whole `router.X(...)`
        // call stays on one line above the body; otherwise the call breaks one
        // argument per line, and the arrow function's own parameter list breaks
        // too if it overflows (Prettier style).
        if !wraps {
            self.server_out.push_str(&inline_opener);
            self.server_out.push('\n');
            self.server_out.push_str(&body);
            self.server_out.push_str("  });\n\n");
        } else {
            self.server_out
                .push_str(&format!("  router.{method}(\n    \"{express_path}\",\n"));
            emit_arrow_header(&mut self.server_out, "    ", &req_type);
            self.server_out.push_str(&body);
            self.server_out.push_str("    },\n  );\n\n");
        }
    }
}

// ── Helper functions ─────────────────────────────────────────────────

/// Whether a body field's resolved type is `Option<File>` (an optional upload).
fn field_ty_is_optional_file(ty: &Type) -> bool {
    matches!(ty, Type::Generic(name, args) if name == "Option" && args.len() == 1 && matches!(args[0], Type::File))
}

/// Emits a client-side `formData.append(...)` for one multipart body field.
///
/// File fields append the `Blob`/`File` value directly; scalar fields are
/// stringified (multipart form values are always text on the wire). Any
/// optional field — `Option<T>`, or a `partial`-relaxed field (`optional`) — is
/// guarded so a missing value is omitted entirely rather than appended as the
/// literal string `"undefined"` (which the server would then coerce to `NaN`,
/// `false`, or store verbatim).
fn emit_form_data_append(out: &mut String, indent: &str, name: &str, ty: &Type, optional: bool) {
    // `optional` covers `partial`-relaxed fields; `Option<T>`/`Option<File>` is
    // detected from the type itself.
    let is_optional = optional
        || field_ty_is_optional_file(ty)
        || matches!(ty, Type::Generic(n, _) if n == "Option");
    let value = if matches!(ty, Type::File) || field_ty_is_optional_file(ty) {
        format!("body.{name}")
    } else {
        format!("String(body.{name})")
    };
    if is_optional {
        out.push_str(&format!("{indent}if (body.{name} !== undefined) {{\n"));
        out.push_str(&format!(
            "{indent}  formData.append(\"{name}\", {value});\n"
        ));
        out.push_str(&format!("{indent}}}\n"));
    } else {
        out.push_str(&format!("{indent}formData.append(\"{name}\", {value});\n"));
    }
}

/// Server-side expression extracting one multipart field into its typed body
/// value. File fields read the parsed `Blob` from `multipart.files`; scalar
/// fields read the string from `multipart.body` and coerce to the field type.
///
/// `optional` is true for a `partial`-relaxed or `Option<T>` scalar: an absent
/// value stays `undefined` rather than coercing to `NaN`/`false`, matching the
/// `T | undefined` shape of the optional field in the generated body type.
fn multipart_field_extraction(name: &str, ty: &Type, optional: bool) -> String {
    if matches!(ty, Type::File) || field_ty_is_optional_file(ty) {
        return format!("multipart.files.{name}");
    }
    let is_option = matches!(ty, Type::Generic(n, _) if n == "Option");
    let inner = match ty {
        Type::Generic(n, args) if n == "Option" && args.len() == 1 => &args[0],
        _ => ty,
    };
    let raw = format!("multipart.body.{name}");
    let coerced = match inner {
        Type::Int | Type::Float => format!("Number({raw})"),
        Type::Bool => format!("{raw} === \"true\""),
        _ => raw.clone(),
    };
    if optional || is_option {
        format!("{raw} !== undefined ? {coerced} : undefined")
    } else {
        coerced
    }
}

/// Generates a TypeScript expression that extracts and coerces a query
/// parameter from `req.query`, applying the default value if the parameter
/// is absent.
fn query_param_coercion(qp: &phoenix_sema::checker::QueryParamInfo) -> String {
    let raw = format!("req.query.{}", qp.name);
    let is_option = matches!(&qp.ty, Type::Generic(name, _) if name == "Option");

    // Determine the coercion expression based on the resolved type
    let coerced = match &qp.ty {
        Type::Int | Type::Float => format!("Number({raw})"),
        Type::Bool => format!("{raw} === \"true\""),
        Type::String => format!("{raw} as string"),
        Type::Generic(name, args) if name == "Option" && !args.is_empty() => {
            // For Option<T>, coerce the inner type if present
            match &args[0] {
                Type::Int | Type::Float => {
                    format!("{raw} !== undefined ? Number({raw}) : undefined")
                }
                Type::Bool => format!("{raw} !== undefined ? {raw} === \"true\" : undefined"),
                _ => format!("{raw} as string | undefined"),
            }
        }
        _ => format!("{raw} as string"),
    };

    // Apply default value if present
    if is_option {
        return coerced;
    }
    if let Some(ref default) = qp.default_value {
        let default_ts = default_value_to_ts(default);
        format!("{raw} !== undefined ? {coerced} : {default_ts}")
    } else {
        coerced
    }
}

/// Converts a [`DefaultValue`] to a TypeScript literal.
///
/// Unlike the Python generator (which forces a decimal point so a float reads as
/// a `float`), `Float` is rendered with a plain `to_string()` here on purpose:
/// JavaScript has a single `number` type, so `0` and `0.0` are identical and no
/// fix-up is needed. Keep this divergence from `python.rs` intentional.
fn default_value_to_ts(val: &DefaultValue) -> String {
    match val {
        DefaultValue::Int(v) => v.to_string(),
        DefaultValue::Float(v) => v.to_string(),
        DefaultValue::String(v) => format!("\"{}\"", v),
        DefaultValue::Bool(v) => v.to_string(),
    }
}

/// Builds a [`ValidationField`] for a field of resolved type `ty`, unwrapping
/// `Option<T>` so the emitted `typeof` guard narrows the inner primitive (and the
/// field is treated as skippable when absent). `extra_optional` folds in any
/// *other* reason the field may be omitted — a `partial`-applied body field.
///
/// Shared by the struct validator ([`TsGenerator::emit_struct_validation`]) and
/// the derived-body validator ([`TsGenerator::emit_validation_function`]) so
/// their `Option` handling cannot drift. That drift is exactly what made the
/// body validator emit a `.length` access on an un-narrowed `unknown`
/// (TS18047 / TS2339) for a constrained `Option<T>` body field: it skipped the
/// `typeof` narrowing the struct validator applies.
fn validation_field(
    name: &str,
    ty: &Type,
    constraint: Option<&phoenix_parser::ast::Expr>,
    extra_optional: bool,
) -> ValidationField {
    let is_option = matches!(ty, Type::Generic(n, _) if n == "Option");
    let inner_ty = if is_option {
        match ty {
            Type::Generic(_, args) => &args[0],
            _ => ty,
        }
    } else {
        ty
    };
    ValidationField {
        name: name.to_string(),
        optional: extra_optional || is_option,
        ts_typeof: ts_typeof_of(inner_ty),
        constraint_guard: constraint.map(|c| {
            let (code, needs_conjunct_parens) = negated_constraint_to_ts(c, name);
            ConstraintGuard {
                code,
                needs_conjunct_parens,
            }
        }),
    }
}

/// Renders the negated constraint for a validation guard, with minimal
/// parentheses (Prettier style), returning the guard code plus whether it must be
/// wrapped in parens when AND-joined with an optional field's presence check (see
/// [`ValidationField::constraint_guard`]).
///
/// `!` (`PREC_UNARY`) only needs to wrap an operand whose precedence is lower, so
/// a method-call/atom constraint negates as `!obj.x.includes("/")` (no parens —
/// `!` binds looser than member/call) while a comparison negates as
/// `!(obj.x > 5)`. Emitting `!(…)` unconditionally would leave redundant parens
/// that `prettier --check` rejects. These `!`-rooted guards are unary-tight, so
/// they never need conjunct parens.
///
/// A constraint that is itself a `!x` collapses to `x` rather than the double
/// negation `!!x` (which eslint's `no-unnecessary-condition`/`no-extra-boolean-cast`
/// flags). `x` is emitted bare — clean standalone (`if (x)`) and as the right of
/// an `&&` (`if (obj.f !== undefined && x)`) for any `x` that binds at least as
/// tight as `&&`. The one exception is a `||`-rooted `x` (`!(a || b)` → `a || b`):
/// bare, `obj.f !== undefined && a || b` mis-parses as `(… && a) || b`, so the
/// `needs_conjunct_parens` flag is set and the caller wraps it to `(a || b)` in
/// the conjunct position only — wrapping it unconditionally would instead leave
/// the redundant `if ((a || b))` parens prettier rejects in the standalone case.
fn negated_constraint_to_ts(expr: &phoenix_parser::ast::Expr, field_name: &str) -> (String, bool) {
    use phoenix_parser::ast::{Expr, UnaryOp};
    if let Expr::Unary(un) = expr
        && matches!(un.op, UnaryOp::Not)
    {
        // Negating a `!x` constraint is just `x`. It needs conjunct parens exactly
        // when it binds looser than `&&` — i.e. a top-level `||`.
        let (code, prec) = constraint_expr_prec(&un.operand, field_name);
        return (code, prec < PREC_AND);
    }
    let (code, prec) = constraint_expr_prec(expr, field_name);
    let guard = if prec < PREC_UNARY {
        format!("!({code})")
    } else {
        format!("!{code}")
    };
    (guard, false)
}

/// Recursively converts a Phoenix constraint `Expr` to a TypeScript expression
/// string, replacing `self` with `obj.{field_name}` for use in validation
/// functions.
fn constraint_expr_to_ts(expr: &phoenix_parser::ast::Expr, field_name: &str) -> String {
    constraint_expr_prec(expr, field_name).0
}

/// JS operator-precedence tiers used to decide when parentheses are needed.
/// Higher binds tighter. Mirrors the standard JS grammar closely enough for the
/// expressions Phoenix constraints can produce, so output matches Prettier's
/// minimal-parens style.
const PREC_ATOM: u8 = 100;
const PREC_UNARY: u8 = 14;
const PREC_OR: u8 = 3;
const PREC_AND: u8 = 4;

/// Converts a constraint `Expr` to `(code, precedence)`. The precedence lets the
/// caller decide whether to wrap the child in parentheses.
fn constraint_expr_prec(expr: &phoenix_parser::ast::Expr, field_name: &str) -> (String, u8) {
    use phoenix_parser::ast::{BinaryOp, Expr, LiteralKind, UnaryOp};

    // Wraps `child` in parens only if its precedence is below `min`.
    fn paren(child: (String, u8), min: u8) -> String {
        if child.1 < min {
            format!("({})", child.0)
        } else {
            child.0
        }
    }

    match expr {
        Expr::Ident(ident) if ident.name == "self" => (format!("obj.{field_name}"), PREC_ATOM),
        Expr::Ident(ident) => (ident.name.clone(), PREC_ATOM),
        Expr::Literal(lit) => {
            let s = match &lit.kind {
                LiteralKind::Int(v) => v.to_string(),
                LiteralKind::Float(v) => v.to_string(),
                LiteralKind::String(v) => format!("\"{}\"", v),
                LiteralKind::Bool(v) => v.to_string(),
            };
            (s, PREC_ATOM)
        }
        Expr::Binary(bin) => {
            let (op, prec) = match bin.op {
                BinaryOp::Or => ("||", PREC_OR),
                BinaryOp::And => ("&&", PREC_AND),
                BinaryOp::Eq => ("===", 8),
                BinaryOp::NotEq => ("!==", 8),
                BinaryOp::Lt => ("<", 9),
                BinaryOp::Gt => (">", 9),
                BinaryOp::LtEq => ("<=", 9),
                BinaryOp::GtEq => (">=", 9),
                BinaryOp::Add => ("+", 11),
                BinaryOp::Sub => ("-", 11),
                BinaryOp::Mul => ("*", 12),
                BinaryOp::Div => ("/", 12),
                BinaryOp::Mod => ("%", 12),
            };
            // Left-associative: left child needs only >= prec, right child > prec.
            let left = paren(constraint_expr_prec(&bin.left, field_name), prec);
            let right = paren(constraint_expr_prec(&bin.right, field_name), prec + 1);
            (format!("{left} {op} {right}"), prec)
        }
        Expr::Unary(un) => {
            let operand = paren(constraint_expr_prec(&un.operand, field_name), PREC_UNARY);
            let s = match un.op {
                UnaryOp::Neg => format!("-{operand}"),
                UnaryOp::Not => format!("!{operand}"),
            };
            (s, PREC_UNARY)
        }
        Expr::FieldAccess(fa) => {
            let object = paren(constraint_expr_prec(&fa.object, field_name), PREC_ATOM);
            (format!("{object}.{}", fa.field), PREC_ATOM)
        }
        Expr::MethodCall(mc) => {
            let object = paren(constraint_expr_prec(&mc.object, field_name), PREC_ATOM);
            let args: Vec<String> = mc
                .args
                .iter()
                .map(|a| constraint_expr_to_ts(a, field_name))
                .collect();
            // Map Phoenix method names to JS equivalents
            let method = match mc.method.as_str() {
                "contains" => "includes",
                other => other,
            };
            (format!("{object}.{method}({})", args.join(", ")), PREC_ATOM)
        }
        _ => ("true".to_string(), PREC_ATOM),
    }
}

/// Renders `text` as a JSDoc comment at `indent`. A single-line comment stays on
/// one line (`/** text */`); a multi-line doc comment (the lexer joins its lines
/// with `\n`) expands to the block form with each line on its own ` * ` row, so
/// continuation lines stay inside the comment instead of leaking as code. Matches
/// Prettier's JSDoc layout in both cases.
fn render_jsdoc(indent: &str, text: &str) -> String {
    if !text.contains('\n') {
        return format!("{indent}/** {text} */\n");
    }
    let mut out = format!("{indent}/**\n");
    for line in text.split('\n') {
        // Trim per line so an empty (or whitespace-only) doc line renders as a
        // bare ` *` row with no trailing space, matching Prettier — and matching
        // the `trim_end` the Go (`render_line_comment`) and Python
        // (`render_hash_comment`) sibling helpers use.
        out.push_str(format!("{indent} * {line}").trim_end());
        out.push('\n');
    }
    out.push_str(&format!("{indent} */\n"));
    out
}

/// Converts a resolved Phoenix `Type` to a TypeScript type string.
fn type_to_ts(ty: &Type) -> String {
    match ty {
        Type::Int | Type::Float => "number".to_string(),
        Type::String => "string".to_string(),
        Type::Bool => "boolean".to_string(),
        // A `File` field in a body type is a binary upload/download. In TS the
        // wire value is a `Blob` (FormData entry / fetch body). Multipart request
        // assembly and binary response handling live in the body-codegen path
        // (branched on "body contains a File"); this is the field type.
        Type::File => "Blob".to_string(),
        Type::Void => "void".to_string(),
        Type::Named(name) => name.clone(),
        Type::Generic(name, args) if name == "List" && args.len() == 1 => {
            format!("{}[]", type_to_ts(&args[0]))
        }
        Type::Generic(name, args) if name == "Map" && args.len() == 2 => {
            format!("Record<{}, {}>", type_to_ts(&args[0]), type_to_ts(&args[1]))
        }
        Type::Generic(name, args) if name == "Option" && args.len() == 1 => {
            format!("{} | undefined", type_to_ts(&args[0]))
        }
        Type::Generic(name, args) => {
            let ts_args: Vec<String> = args.iter().map(type_to_ts).collect();
            format!("{}<{}>", name, ts_args.join(", "))
        }
        Type::Function(params, ret) => {
            let ps: Vec<String> = params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, type_to_ts(p)))
                .collect();
            format!("({}) => {}", ps.join(", "), type_to_ts(ret))
        }
        Type::TypeVar(name) => name.clone(),
        // Trait objects erase to the trait name on the TS side (structural
        // interface dispatch handles the runtime variance); sharper mappings
        // can replace this when specific traits get per-trait TS shims.
        Type::Dyn(name) => name.clone(),
        Type::Error => "unknown".to_string(),
    }
}

/// Converts a Phoenix `TypeExpr` (AST node) to a TypeScript type string.
/// Used for enum variant fields which only have AST-level type info.
fn type_expr_to_ts(te: &TypeExpr) -> String {
    match te {
        TypeExpr::Named(n) => match n.name.as_str() {
            "Int" | "Float" => "number".to_string(),
            "String" => "string".to_string(),
            "Bool" => "boolean".to_string(),
            "Void" => "void".to_string(),
            other => other.to_string(),
        },
        TypeExpr::Generic(g) => {
            let args: Vec<String> = g.type_args.iter().map(type_expr_to_ts).collect();
            match g.name.as_str() {
                "List" if args.len() == 1 => format!("{}[]", args[0]),
                "Option" if args.len() == 1 => format!("{} | undefined", args[0]),
                "Map" if args.len() == 2 => format!("Record<{}, {}>", args[0], args[1]),
                _ => format!("{}<{}>", g.name, args.join(", ")),
            }
        }
        TypeExpr::Function(f) => {
            let ps: Vec<String> = f
                .param_types
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, type_expr_to_ts(p)))
                .collect();
            format!("({}) => {}", ps.join(", "), type_expr_to_ts(&f.return_type))
        }
        TypeExpr::Dyn(d) => d.trait_name.clone(),
    }
}

/// Converts a resolved derived type to a TypeScript type expression.
///
/// Emits an inline object type to faithfully represent the derived fields
/// with their optionality. This covers all modifier combinations (omit,
/// pick, partial, selective partial).
fn derived_type_to_ts(body: &ResolvedDerivedType) -> String {
    let all_optional = !body.fields.is_empty() && body.fields.iter().all(|f| f.optional);

    if all_optional {
        // All optional — emit Partial with inline type for the fields
        let mut parts = Vec::new();
        for f in &body.fields {
            let ts = type_to_ts(&f.ty);
            parts.push(format!("  {}?: {};", f.name, ts));
        }
        return format!("{{\n{}\n}}", parts.join("\n"));
    }

    // Emit inline object type with the actual derived fields
    let mut parts = Vec::new();
    for f in &body.fields {
        let ts = type_to_ts(&f.ty);
        if f.optional {
            parts.push(format!("  {}?: {};", f.name, ts));
        } else {
            parts.push(format!("  {}: {};", f.name, ts));
        }
    }
    format!("{{\n{}\n}}", parts.join("\n"))
}

/// Recursively collects user-defined type names that need to be imported.
///
/// Skips built-in generic wrappers (`List`, `Option`, `Map`, `Result`) since
/// they map to native TypeScript constructs, but descends into their type
/// arguments to find the actual user-defined types (e.g., `List<User>` imports
/// `User`, not `List`).
fn collect_import_names(ty: &Type, imports: &mut BTreeSet<String>) {
    match ty {
        Type::Named(name) => {
            imports.insert(name.clone());
        }
        Type::Generic(name, args) => {
            if !matches!(name.as_str(), "List" | "Option" | "Map" | "Result") {
                imports.insert(name.clone());
            }
            for arg in args {
                collect_import_names(arg, imports);
            }
        }
        _ => {}
    }
}

/// Returns whether a query parameter should be optional in the client function
/// signature (either it has a default value or its type is `Option<T>`).
fn is_query_param_optional(qp: &phoenix_sema::checker::QueryParamInfo) -> bool {
    qp.has_default || matches!(&qp.ty, Type::Generic(name, _) if name == "Option")
}

/// Returns whether a request header is `Option<T>` (i.e. an optional field on
/// the wire and in the handler signature). Defaults make the *client* field
/// optional too, but the handler always receives a value once the server
/// applies the default — mirroring query-param handling.
fn is_header_option(h: &phoenix_sema::checker::HeaderParamInfo) -> bool {
    matches!(&h.ty, Type::Generic(name, _) if name == "Option")
}

/// Returns whether a request header should be optional in the *client* method
/// signature (either it has a default value or its type is `Option<T>`).
fn is_header_client_optional(h: &phoenix_sema::checker::HeaderParamInfo) -> bool {
    h.has_default || is_header_option(h)
}

/// The TypeScript name of the response-header envelope type for an endpoint
/// (e.g. `getPost` → `GetPostResult`). Only emitted/used when the endpoint
/// declares response headers.
fn result_type_name(ep: &EndpointInfo) -> String {
    format!("{}Result", capitalize(&ep.name))
}

/// The TypeScript name of the pagination envelope type for an endpoint
/// (e.g. `listPosts` → `ListPostsPage`). Only emitted/used when the endpoint
/// declares a `pagination { }` block. Distinct from `result_type_name`
/// (pagination and response headers are mutually exclusive — sema rejects the
/// combination).
fn page_type_name(ep: &EndpointInfo) -> String {
    format!("{}Page", capitalize(&ep.name))
}

/// The TypeScript name of the multi-status envelope type for an endpoint
/// (e.g. `upsertUser` → `UpsertUserResponse`). Only emitted/used when the
/// endpoint declares a `response { }` block (`response_statuses` non-empty).
/// Distinct from `result_type_name` / `page_type_name` — multi-status is
/// mutually exclusive with response headers and pagination (sema rejects the
/// combinations), so this never collides with the other envelopes.
fn multi_status_type_name(ep: &EndpointInfo) -> String {
    format!("{}Response", capitalize(&ep.name))
}

/// Emits a `res.status(500).json({ error: "<message>" });` statement at indent
/// `ni`, breaking the member chain the way prettier does once the one-liner
/// exceeds [`PRINT_WIDTH`] (the route indent varies with the opener wrapping,
/// so the guard messages can land on either side of the limit).
fn emit_500_json(body: &mut String, ni: &str, message: &str) {
    let one_line = format!("{ni}res.status(500).json({{ error: \"{message}\" }});");
    if one_line.len() <= PRINT_WIDTH {
        body.push_str(&one_line);
        body.push('\n');
    } else {
        body.push_str(&format!(
            "{ni}res\n{ni}  .status(500)\n{ni}  .json({{ error: \"{message}\" }});\n"
        ));
    }
}

/// Generates an expression coercing a request header read server-side
/// (`req.header("Wire-Name")`, typed `string | undefined`) to its typed value,
/// applying the default when the header is absent. Mirrors
/// [`query_param_coercion`].
fn request_header_coercion(h: &phoenix_sema::checker::HeaderParamInfo) -> String {
    let raw = format!("req.header(\"{}\")", h.wire_name);
    let is_option = is_header_option(h);

    let coerced = match &h.ty {
        Type::Int | Type::Float => format!("Number({raw})"),
        Type::Bool => format!("{raw} === \"true\""),
        Type::String => format!("{raw} as string"),
        Type::Generic(name, args) if name == "Option" && !args.is_empty() => match &args[0] {
            Type::Int | Type::Float => {
                format!("{raw} !== undefined ? Number({raw}) : undefined")
            }
            Type::Bool => format!("{raw} !== undefined ? {raw} === \"true\" : undefined"),
            // `req.header(...)` is already typed `string | undefined`, so an
            // `as string | undefined` cast would be flagged by eslint's
            // no-unnecessary-type-assertion; use the raw read.
            _ => raw.clone(),
        },
        _ => format!("{raw} as string"),
    };

    if is_option {
        return coerced;
    }
    if let Some(ref default) = h.default_value {
        let default_ts = default_value_to_ts(default);
        format!("{raw} !== undefined ? {coerced} : {default_ts}")
    } else {
        coerced
    }
}

/// Generates an expression reading a response header on the client side from a
/// fetch `Response` (`response.headers.get("Wire-Name")`, typed
/// `string | null`) and coercing it to its typed value. Optional headers map a
/// missing value (`null`) to `undefined`; required headers assume the header is
/// present (the matching server always sets it).
fn response_header_coercion(h: &phoenix_sema::checker::HeaderParamInfo) -> String {
    let raw = format!("response.headers.get(\"{}\")", h.wire_name);
    let is_option = is_header_option(h);
    let inner = if is_option {
        match &h.ty {
            Type::Generic(_, args) if !args.is_empty() => &args[0],
            other => other,
        }
    } else {
        &h.ty
    };

    if is_option {
        match inner {
            Type::Int | Type::Float => {
                format!("{raw} !== null ? Number({raw}) : undefined")
            }
            Type::Bool => format!("{raw} !== null ? {raw} === \"true\" : undefined"),
            // `response.headers.get(...)` is already typed `string | null`, so a
            // cast would be an unnecessary-type-assertion; `?? undefined` maps the
            // missing case (null) to undefined for the optional field.
            _ => format!("{raw} ?? undefined"),
        }
    } else {
        // Required: the header is contractually present (a generated server
        // always sets a non-`Option` response header — the envelope field is
        // type-required, so the handler must supply it). The coercions below
        // therefore don't special-case a `null` read. NOTE: if a *non-conforming*
        // (e.g. third-party) server omits it, the string branch yields a runtime
        // `null` typed as `string`, where Go/Python fall back to `""`. This
        // cross-language divergence is unreachable against a generated server and
        // is left as-is rather than fabricating an empty-string default that would
        // mask the contract violation.
        match inner {
            Type::Int | Type::Float => format!("Number({raw})"),
            Type::Bool => format!("{raw} === \"true\""),
            _ => format!("{raw} as string"),
        }
    }
}

/// Builds a URL template expression with path parameter substitution.
///
/// `/api/users/{id}` → `/api/users/${id}`
fn build_url_expr(path: &str, _params: &[String]) -> String {
    path.replace('{', "${")
}

use crate::capitalize;

#[cfg(test)]
#[path = "typescript_tests.rs"]
mod tests;
